### ISSUE TITLE
No detections with Jetson inference code

### ISSUE THREAD

**Issue by Nexgensis** [triple-Mu/YOLOv8-TensorRT#100]
Thanks for sharing this ... this is wonderful.

I am using Jetson and using C++ code for inference, but there is no Detection, Can you please help here

**Comment by triple-Mu** [comment]
> 

Try to detect on your pc first.
And make sure your jetpack version >= 4.6.3

**Comment by Nexgensis** [comment]
Detect on PC with .pt?
if .pt it is working.

**Comment by triple-Mu** [comment]
> Detect on PC with .pt?
> 
> if .pt it is working.

No. Using tensorrt.
Please see docs.

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
