### ISSUE TITLE
How to pass a live stream to Jetson Detect with C++

### ISSUE THREAD

**Issue by Nexgensis** [triple-Mu/YOLOv8-TensorRT#101]
Can we pass a live stream to Jetson Detect with C++ ?

**Comment by triple-Mu** [comment]
> Can we pass a live stream to Jetson Detect with C++ ?

Maybe you can modify as:
``` c++
cv::VideoCapture cap("your url stream");
if (!cap.isOpened())
{
	printf("can not open %s\n", path.c_str());
	return -1;
}
....
```

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
