### ISSUE TITLE
TypeError: Argument 'thickness' is required to be an integer from infer-det.py

### ISSUE THREAD

**Issue by sirius2beta** [triple-Mu/YOLOv8-TensorRT#102]
Hello, I was running on Nvidia jetson xavier nx with jetpack 5.1.1 installed, I successfully exported Yolov8.onnx and .engine file and ran infer-det.py with good result. However, after I rebuild and installed opencv 4.7.0 with gstreamer support yesterday, I got " TypeError: Argument 'thickness' is required to be an integer " message. I tried to change bbox[:2] to tuple(bbox[:2]), and no more error message was noted. What seems to be the problem?
![截圖 2023-05-27 上午9 33 24](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/92342848/7c92161e-abce-4f99-836a-e2bfc99082ac)
![截圖 2023-05-27 上午9 41 19](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/92342848/2941d8e2-9333-49a9-8ce0-a96afef45ee5)

**Comment by triple-Mu** [comment]
I can not reproduct your error.
It seems like you opencv api bugs.
Suggest you installing opencv by `pip install opencv-python`

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
