### ISSUE TITLE
Sagfault at createExecutionContext on Jetson

### ISSUE THREAD

**Issue by Shassk** [triple-Mu/YOLOv8-TensorRT#103]
So I've tried this code (both regular detect and detect for Jetson) with a custom ONNX model (YOLOv8s with 42 classes). Both versions work on Windows PC (CUDA 11.4/TRT 8.5.2.2) with GTX 1070. However when I'm trying to run it on Jetson (CUDA 10.2/TRT 8.2.1.8) I'm getting segfault on `createExecutionContext` call, and gdb can't even backtrace it on a debug version. Tried on 2 Jetsons (thought might be an issue with one of them) to no luck.
Any ideas what could it be?

**Comment by triple-Mu** [comment]
I am sorry to hear that.
But do you try `csrc/jetson/detect` code on jetson.

**Comment by Shassk** [comment]
I've tried both:
`csrc/jetson/detect`
and
`csrc/detect/normal`
Same result.
I don't think it's a problem in your code, but maybe you have any ideas?

**Comment by triple-Mu** [comment]
> I've tried both: `csrc/jetson/detect` and `csrc/detect/normal` Same result. I don't think it's a problem in your code, but maybe you have any ideas?

But I run it well on my TX2.
What's your jetpack version?
Please update it to jetpack4.6.3+

**Comment by triple-Mu** [comment]
> I have 4.6.3-b17 version already

Your error message is too sparse for me to help pinpoint the location. Please send screenshots or other information

**Comment by triple-Mu** [comment]
> 7\. createExecutionContext

There are so few error messages that I can't help locating them.

**Comment by Shassk** [comment]
I cannot too. This is why I think it is library problem. I will try newer Jetpack now.

**Comment by triple-Mu** [comment]
> I cannot too. This is why I think it is library problem. I will try newer Jetpack now.

Okay. Hope you get the correct result soon!

**Comment by Plumess** [comment]
Hello, it appears that I'm encountering the same issue. Have you found a solution to this problem?

**Comment by Shassk** [comment]
Unfortunately no. I've spend many time rewriting a new code from several repositories including this one until eventually I've managed to get it to work. However it's a piece of larger product under NDA so I can't share it unfortunately.

**Comment by Plumess** [comment]
Okay, thanks for your reply.

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
