### ISSUE TITLE
How NMS is imported into the model through export-det.py

### ISSUE THREAD

**Issue by BouncyKnight12** [triple-Mu/YOLOv8-TensorRT#104]
I noticed that the model exported using export-det.py was end2end, and I was looking for where to import nms into the model.
```
    for m in model.modules():
        optim(m)
        m.to(args.device)
```
I found that properties were modified for a specific layer in the optim function.
```
    for _ in range(2):
        model(fake_input)
```
Later, because of the function model (fake_input), the PostDetect object is brought into the model. 
And because the return value of PostDetect is TRT_NMS, TRT::EfficientNMS_TRT is brought into the model. I don't know if I'm right to understand that. 
Also, I haven't figured out how the forward and symbolic functions work in TRT_NMS objects.

**Comment by triple-Mu** [comment]
Please see `optim` function.
