### ISSUE TITLE
C++ code broken, fix suggestion

### ISSUE THREAD

**Issue by cyrusbehr** [triple-Mu/YOLOv8-TensorRT#105]
`main` branch can't be compiled right now, fails on error:

```
/home/cyrus/work/repos/YOLOv8-TensorRT/csrc/detect/normal/./include/yolov8.hpp:407:6: error: #elif with no expression
  407 | #elif
      |      ^

```

On [this](https://github.com/triple-Mu/YOLOv8-TensorRT/blob/d9687b12c1a2756d48529d4f3f1fdd638630e361/csrc/detect/normal/include/yolov8.hpp#L407) line, need to change `#elif` to `#else`.

**Comment by triple-Mu** [comment]
> `main` branch can't be compiled right now, fails on error:
> 
> 
> 
> ```
> 
> /home/cyrus/work/repos/YOLOv8-TensorRT/csrc/detect/normal/./include/yolov8.hpp:407:6: error: #elif with no expression
> 
>   407 | #elif
> 
>       |      ^
> 
> 
> 
> ```
> 
> 
> 
> On [this](https://github.com/triple-Mu/YOLOv8-TensorRT/blob/d9687b12c1a2756d48529d4f3f1fdd638630e361/csrc/detect/normal/include/yolov8.hpp#L407) line, need to change `#elif` to `#else`. 

Thanks.
Could you please pr for this bug?

**Comment by cyrusbehr** [comment]
@triple-Mu sorry for delay, PR created.

**Comment by triple-Mu** [comment]
Thanks very much!
Then issue closed.
