### ISSUE TITLE
Infer with C++ 编译成功后，运行出错！

### ISSUE THREAD

**Issue by WYQ-Github** [triple-Mu/YOLOv8-TensorRT#106]
~~~
 ./yolov8 yolov8s.engine data

LLVM ERROR: out of memory
Aborted

~~~
请问是什么问题呢？如何解决呢？
谢谢您!

**Comment by triple-Mu** [comment]
> ~~~
> 
>  ./yolov8 yolov8s.engine data
> 
> 
> 
> LLVM ERROR: out of memory
> 
> Aborted
> 
> 
> 
> ~~~
> 
> 请问是什么问题呢？如何解决呢？
> 
> 谢谢您!

使用g++编译呢？

**Comment by GalSang17** [comment]
> > ```
> > 
> >  ./yolov8 yolov8s.engine data
> > 
> > 
> > 
> > LLVM ERROR: out of memory
> > 
> > Aborted
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 请问是什么问题呢？如何解决呢？
> > 谢谢您!
> 
> 使用g++编译呢？

你好，我也遇到了同样的问题

**Comment by triple-Mu** [comment]
> > > ```
> > > 
> > >  ./yolov8 yolov8s.engine data
> > > 
> > > 
> > > 
> > > LLVM ERROR: out of memory
> > > 
> > > Aborted
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 请问是什么问题呢？如何解决呢？
> > > 谢谢您!
> > 
> > 
> > 使用g++编译呢？
> 
> 你好，我也遇到了同样的问题

报错信息能否给详细一点？没有详细的信息我是无法定位问题的

**Comment by GalSang17** [comment]
> > > > ```
> > > > 
> > > >  ./yolov8 yolov8s.engine data
> > > > 
> > > > 
> > > > 
> > > > LLVM ERROR: out of memory
> > > > 
> > > > Aborted
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 请问是什么问题呢？如何解决呢？
> > > > 谢谢您!
> > > 
> > > 
> > > 使用g++编译呢？
> > 
> > 
> > 你好，我也遇到了同样的问题
> 
> 报错信息能否给详细一点？没有详细的信息我是无法定位问题的

不好意思，我犯了一个常识错误，推理加了-d参数，事实没有这个参数，我的代码现在可以正常工作了，我猜测提issue的人应该也是因为这个问题，非常感谢你及时回复。另外我想问问，可以在后处理部分参照yolov5-7.0版本的Trt代码优化下后处理部分吗，后续有这样的安排吗^_^

**Comment by WYQ-Github** [comment]
> > ```
> > 
> >  ./yolov8 yolov8s.engine data
> > 
> > 
> > 
> > LLVM ERROR: out of memory
> > 
> > Aborted
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 请问是什么问题呢？如何解决呢？
> > 谢谢您!
> 
> 使用g++编译呢？
 
您好g++ 编译同样问题，我重新修改了cuda cudnn tensorrt opencv版本后，可以了

**Comment by triple-Mu** [comment]
> > > > > ```
> > > > > 
> > > > >  ./yolov8 yolov8s.engine data
> > > > > 
> > > > > 
> > > > > 
> > > > > LLVM ERROR: out of memory
> > > > > 
> > > > > Aborted
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 请问是什么问题呢？如何解决呢？
> > > > > 谢谢您!
> > > > 
> > > > 
> > > > 使用g++编译呢？
> > > 
> > > 
> > > 你好，我也遇到了同样的问题
> > 
> > 
> > 报错信息能否给详细一点？没有详细的信息我是无法定位问题的
> 
> 不好意思，我犯了一个常识错误，推理加了-d参数，事实没有这个参数，我的代码现在可以正常工作了，我猜测提issue的人应该也是因为这个问题，非常感谢你及时回复。另外我想问问，可以在后处理部分参照yolov5-7.0版本的Trt代码优化下后处理部分的处理速度吗，后续有这样的安排吗^_^

目前工作比较多，暂时没有计划。
如果您有兴趣可以pr来我们合作完成。谢谢！

**Comment by triple-Mu** [comment]
> > > ```
> > > 
> > >  ./yolov8 yolov8s.engine data
> > > 
> > > 
> > > 
> > > LLVM ERROR: out of memory
> > > 
> > > Aborted
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 请问是什么问题呢？如何解决呢？
> > > 谢谢您!
> > 
> > 
> > 使用g++编译呢？
> 
> 您好g++ 编译同样问题，我重新修改了cuda cudnn tensorrt opencv版本后，可以了

Ok.
那我就关闭 issue 了。

**Comment by lunalulu** [comment]
@WYQ-Github 请问具体是怎么修改的？我的cuda11.6,cudnn8.2.0,tensorrt 8.5.3.1, opencv4.6.0，也遇到了同样的问题

**Comment by WYQ-Github** [comment]
> @WYQ-Github 请问具体是怎么修改的？我的cuda11.6,cudnn8.2.0,tensorrt 8.5.3.1, opencv4.6.0，也遇到了同样的问题

当时，我自己主机没跑起来demo，在同学cuda11.4, cudnn8.2.4, tensorrt 8.4.3.1, opencv3.4.16的主机跑起来的demo，但我觉得不是版本问题。您可以参考下。

**Comment by lunalulu** [comment]
@WYQ-Github 好滴，谢谢你~

**Comment by triple-Mu** [comment]
> @WYQ-Github 请问具体是怎么修改的？我的cuda11.6,cudnn8.2.0,tensorrt 8.5.3.1, opencv4.6.0，也遇到了同样的问题

能否给出详细报错。

**Comment by XianYang2547** [comment]
> > > > > ```
> > > > > 
> > > > >  ./yolov8 yolov8s.engine data
> > > > > 
> > > > > 
> > > > > 
> > > > > LLVM ERROR: out of memory
> > > > > 
> > > > > Aborted
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 请问有什么问题呢？如何解决呢？
> > > > > 谢谢您！
> > > > 
> > > > 
> > > > 使用g++编译吗？
> > > 
> > > 
> > > 你好，我也遇到了同样的问题
> > 
> > 
> > 报错信息能否给详细情况？没有详细信息是无法定位问题的
> 
> 不好意思，我犯了一个常识错误，推理了-d参数，事实上没有这个参数，我的代码现在可以写了，我猜测issue的人也应该知道这个问题，非常感谢你及时回复。另外我想问问，可以在后处理部分yolov5-7.0版本Trt代码优化下后处理部分处理速度，后续有这样的安排吗^_^

niha

> > > > > ```
> > > > > 
> > > > >  ./yolov8 yolov8s.engine data
> > > > > 
> > > > > 
> > > > > 
> > > > > LLVM ERROR: out of memory
> > > > > 
> > > > > Aborted
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 请问是什么问题呢？如何解决呢？
> > > > > 谢谢您!
> > > > 
> > > > 
> > > > 使用g++编译呢？
> > > 
> > > 
> > > 你好，我也遇到了同样的问题
> > 
> > 
> > 报错信息能否给详细一点？没有详细的信息我是无法定位问题的
> 
> 不好意思，我犯了一个常识错误，推理加了-d参数，事实没有这个参数，我的代码现在可以正常工作了，我猜测提issue的人应该也是因为这个问题，非常感谢你及时回复。另外我想问问，可以在后处理部分参照yolov5-7.0版本的Trt代码优化下后处理部分的处理速度吗，后续有这样的安排吗^_^

你好，我也遇到了一样的错误：我在segment/normal中，使用yolo导出了onnx，然后通过自己的代码转换得到了engine文件，使用cmake.. make后，执行./yolov8-seg seg.engine test1.jpg，得到了LLVM ERROR: out of memory
已放弃
结果，我该怎样修改呢。另外在detect的normal中，使用同样的方法，可以正常推理，但是结果完全错误

**Comment by triple-Mu** [comment]
> > @WYQ-Github 请问具体是怎么修改的？我的cuda11.6,cudnn8.2.0,tensorrt 8.5.3.1, opencv4.6.0，也遇到了同样的问题
> 
> 
> 
> 能否给出详细报错。

norm是否有修改类别数量，类别名称呢？能否给出你的onnx呢，我需要复现这个问题

**Comment by ljl02521** [comment]
LLVM ERROR: out of memory,这个错误我也遇到了，我的错误的原因是多传进去一个参数，执行的是./yolov8-pose engine yolov8s-pose.engine data/bus.jpg，正确的命令应该是./yolov8-pose yolov8s-pose.engine data/bus.jpg，你们遇到这样的错误自己检查下
