### ISSUE TITLE
jetson detect中的trtModelStream不需要释放吗

### ISSUE THREAD

**Issue by NLPOR** [triple-Mu/YOLOv8-TensorRT#107]
https://github.com/triple-Mu/YOLOv8-TensorRT/tree/main/csrc/jetson/detect/include/yolov8.hpp
 中第59行：char* trtModelStream = new char[size];

不需要进行delete吗

**Comment by triple-Mu** [comment]
> https://github.com/triple-Mu/YOLOv8-TensorRT/tree/main/csrc/jetson/detect/include/yolov8.hpp 中第59行：char* trtModelStream = new char[size];
> 
> 不需要进行delete吗

需要，是个bug。您想pr帮忙修复吗？
