### ISSUE TITLE
detect in win10 error

### ISSUE THREAD

**Issue by OnlySoaring** [triple-Mu/YOLOv8-TensorRT#109]
Win10
torch:2.0.0
cuda:11.8
cudnn:8.6.0
tensorrt:8.6.1.6

I use ultralytics-master to export engine. The model is yolov8n.pt
def test_export_onnx():
    model = YOLO(MODEL)
    model.export(format='TensorRT',opset=11,device=0)

then i use csrc->detect->normal in Visual studio and modify the code：
	//const std::string engine_file_path{ argv[1] };
	//const std::string path{ argv[2] };
	const std::string engine_file_path= "C:/Users/123/Desktop/yolov8n.engine";
	const std::string path= "C:\\Users\\123\\Desktop\\YOLOv8-TensorRT-main\\YOLOv8-TensorRT-main\\data\\bus.jpg";

but the engine init error:
ERROR: 1: [runtime.cpp::nvinfer1::Runtime::parsePlan::314] Error Code 1: Serialization (Serialization assertion plan->header.magicTag == rt::kPLAN_MAGIC_TAG failed.)
Assertion failed: this->engine != nullptr, file C:\Users\123\source\repos\Project1\yolov8.h, line 74

**Comment by triple-Mu** [comment]
Please export onnx and using `trtexec` to convert to engine.
Please do not use `yolo export format=engine`!
It seems that you install tensorrt-python by `pip install tensorrt` and your py-tensorrt doesn't match your cpp-tensorrt.

**Comment by OnlySoaring** [comment]
i find the export list in ultralytics-master:
                       Format     Argument           Suffix    CPU    GPU
    0                 PyTorch            -              .pt   True   True
    1             TorchScript  torchscript     .torchscript   True   True
    2                    ONNX         onnx            .onnx   True   True
    3                OpenVINO     openvino  _openvino_model   True  False
    4                TensorRT       engine          .engine  False   True
    5                  CoreML       coreml         .mlmodel   True  False
    6   TensorFlow SavedModel  saved_model     _saved_model   True   True
    7     TensorFlow GraphDef           pb              .pb   True   True
    8         TensorFlow Lite       tflite          .tflite   True  False
    9     TensorFlow Edge TPU      edgetpu  _edgetpu.tflite  False  False
    10          TensorFlow.js         tfjs       _web_model  False  False
    11           PaddlePaddle       paddle    _paddle_model   True   True

how to export .trt? I cant find the format "trtexec" in ultralytics-master or your code "build.py"
and I try to export by "build.py". It also is .engine, but detect is work.

then the new error is:
OpenCV(4.5.5) Error: Bad argument (Matrix operand is an empty matrix.) in cv::checkOperandsExist, file C:\build\master_winpack-build-win64-vc15\opencv\modules\core\src\matrix_expressions.cpp, line 24
:(
the code stop at yolov8.h line 365:  output = output.t();

**Comment by OnlySoaring** [comment]
![企业微信截图_16865354575447](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/136061683/61cfa237-c9ea-4023-9c6b-aa3a997057bf)
that is the log and variable. i think the output is empty
i didnt use `pip install tensorrt` but i use `pip install tensorrt-8.6.1-cp39-none-win_amd64.whl` in `TensorRT-8.6.1.6.tar.gz`

**Comment by OnlySoaring** [comment]
ohhh,i use your `build.py` to export engine and detect by `end2end`. it is work and detect successfully.
:)))
but i am still not clear why the error `Assertion failed: this->engine != nullptr, file C:\Users\123\source\repos\Project1\yolov8.h, line 74` occurrs when i use `ultralytics` to export and use `normal` to detect.

**Comment by triple-Mu** [comment]
> ohhh,i use your `build.py` to export engine and detect by `end2end`. it is work and detect successfully.
> 
> :)))
> 
> but i am still not clear why the error `Assertion failed: this->engine != nullptr, file C:\Users\123\source\repos\Project1\yolov8.h, line 74` occurrs when i use `ultralytics` to export and use `normal` to detect.

pip install tensorrt will install a only python readable engine.
It mismatch the cpp tensorrt verson.

**Comment by OnlySoaring** [comment]
I use `pip install tensorrt-8.6.1-cp39-none-win_amd64.whl` in TensorRT-8.6.1.6.tar.gz. Is this the same as `pip install tensorrt`?
I never used `pip install tensorrt`.  Your code `YOLOv8-TensorRT` and `ultralytics-master` are in the same python path.

**Comment by triple-Mu** [comment]
> I use `pip install tensorrt-8.6.1-cp39-none-win_amd64.whl` in TensorRT-8.6.1.6.tar.gz. Is this the same as `pip install tensorrt`?
> 
> I never used `pip install tensorrt`.  Your code `YOLOv8-TensorRT` and `ultralytics-master` are in the same python path.

I can't give the answer to the environmental problem, please solve it yourself.

**Comment by OnlySoaring** [comment]
Okay，thanks your answer that it help me a lot. 
:)
