### ISSUE TITLE
loss precision when export to onnx and engine

### ISSUE THREAD

**Issue by MoussaGRICHE** [triple-Mu/YOLOv8-TensorRT#110]
Hello,

I have trained a yolov8 model to detect cars and motorcycles. The detection is very good using .pt or .onnx from yolo.

When I export the pt model to onnx using export-det.py, and then convert to engine, the detection became not good and I loss almost all the class motorcycle. I have this problem in PC and Jetson Nano.

Do you have an idea?
Could I use the onnx from yolo?

Thank you.

**Comment by triple-Mu** [comment]
> 

What's your motorcycles score in pt model?
If you want to detect low score object, please add `--score-thres 0.1`

**Comment by MoussaGRICHE** [comment]
even with --score-thres 0.1 the inference for motorcycle is not good.

I am trying using the normal code to use en engine from yolo but i get this error:

      include/yolov8.hpp:407:6: error: #elif with no expression
        407 | #elif

I think a condition s missing!!!

**Comment by triple-Mu** [comment]
https://github.com/triple-Mu/YOLOv8-TensorRT/issues/105
Here

**Comment by MoussaGRICHE** [comment]
@triple-Mu Thank you for your response.

I have maked the normal yolov8 executable file but when I run it with the engine from yolov8 I get this :

      ERROR: 1: [stdArchiveReader.cpp::StdArchiveReader::32] Error Code 1: Serialization (Serialization assertion magicTagRead == kMAGIC_TAG failed.Magic tag does not match)
      ERROR: 4: [runtime.cpp::deserializeCudaEngine::66] Error Code 4: Internal Error (Engine deserialization failed.)
      Segmentation fault (core dumped)

**Comment by MoussaGRICHE** [comment]
@triple-Mu Now it works when I export .onnx with yolov8 and then convert to .engine with trtexec.

Otherwise, I don't understand what happen with my custom yolov8_last model.

I export my custom yolov8n_last.onnx using yolov8 and then converted to yolov8n_last.engine using trtexec and the results of the inference is string.

Here the result of the inference using yolov8n_last.onnx

![test](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/103992437/1d01cdfc-6b47-47f8-893d-635b717f0173)


Here the result of the inference using yolov8n_last.engine
![Screenshot from 2023-06-10 16-11-24](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/103992437/b8ee040c-fa78-4c0d-adb7-6dc4ea4a8951)

I can't understand why with the pre-trained yolov8n model the inference works great and with my custom yolov8n_last the inference results are string.

Thank you.

**Comment by triple-Mu** [comment]
> @triple-Mu Now it works when I export .onnx with yolov8 and then convert to .engine with trtexec.
> 
> Otherwise, I don't understand what happen with my custom yolov8_last model.
> 
> I export my custom yolov8n_last.onnx using yolov8 and then converted to yolov8n_last.engine using trtexec and the results of the inference is string.
> 
> Here the result of the inference using yolov8n_last.onnx
> 
> ![test](https://user-images.githubusercontent.com/103992437/244875757-1d01cdfc-6b47-47f8-893d-635b717f0173.jpg)
> 
> Here the result of the inference using yolov8n_last.engine ![Screenshot from 2023-06-10 16-11-24](https://user-images.githubusercontent.com/103992437/244875744-b8ee040c-fa78-4c0d-adb7-6dc4ea4a8951.png)
> 
> I can't understand why with the pre-trained yolov8n model the inference works great and with my custom yolov8n_last the inference results are string.
> 
> Thank you.

You can give me your yolov8n_last.pt for testing.
My email is gpu@163.com

**Comment by triple-Mu** [comment]
I can not download. please send in appendix.

**Comment by MoussaGRICHE** [comment]
Could you download it now?

**Comment by triple-Mu** [comment]
It work well in end2end:
![image](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/92794867/31704a82-920f-44f3-b132-f64dee800195)

``` shell
python3 export-det.py --weights yolov8n_last.pt --sim
trtexec --onnx=yolov8n_last.onnx --saveEngine=yolov8n_last.plan --fp16

cd csrc/detect/end2end/
mkdir build
cd build
cmake ..
make -j4
./build/yolov8 yolov8n_last.plan test.jpg
```

**Comment by MoussaGRICHE** [comment]
Thank you @triple-Mu 

Tell me please, does yolov8n_last.pt work (good inference) with normal in your side?

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
