### ISSUE TITLE
这个库支持在win10上运行吗？

### ISSUE THREAD

**Issue by erhaa233** [triple-Mu/YOLOv8-TensorRT#112]
<unistd.h>这个头文件，windows上应该没有吧

**Comment by triple-Mu** [comment]
> <unistd.h>这个头文件，windows上应该没有吧

支持，不过需要自己适配一下。
这个库是负责路径相关的操作的。win可能没有。

**Comment by erhaa233** [comment]
好吧




***@***.***
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "triple-Mu/YOLOv8-TensorRT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月13日(星期二) 中午1:23
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [triple-Mu/YOLOv8-TensorRT] 这个库支持在win10上运行吗？ (Issue #112)





  
<unistd.h&gt;这个头文件，windows上应该没有吧
  
支持，不过需要自己适配一下。
 这个库是负责路径相关的操作的。win可能没有。

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
