### ISSUE TITLE
Build Error while trying to use C++ inference

### ISSUE THREAD

**Issue by jyothir07** [triple-Mu/YOLOv8-TensorRT#113]
Jetson Nano 4GB
Jetpack 4.6.3
CUDA-10.2
CUDNN-8.2.1
TensorRT-8.2.1
DeepStream-6.0.1
I have created the engine file and tested with infer-detect-without-torch.py and the detections were correct. But when i try to use the c++ code, while building i face the following error in jetson nano.
cd src/jetson/detect
mkdir build
cmake ..
make

jr_rose@jr_rose-desktop:~/Documents/YOLOv8-TensorRT/csrc/jetson/detect$ make
[ 50%] Building CXX object CMakeFiles/yolov8.dir/main.cpp.o
In file included from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:0:
/home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/yolov8.hpp: In destructor ‘YOLOv8::~YOLOv8()’:
/home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/yolov8.hpp:114:25: warning: ‘void nvinfer1::IExecutionContext::destroy()’ is deprecated [-Wdeprecated-declarations]
  this->context->destroy();
                         ^
In file included from /usr/include/aarch64-linux-gnu/NvInfer.h:54:0,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/common.hpp:10,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/yolov8.hpp:7,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:
/usr/include/aarch64-linux-gnu/NvInferRuntime.h:1960:25: note: declared here
     TRT_DEPRECATED void destroy() noexcept
                         ^~~~~~~
In file included from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:0:
/home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/yolov8.hpp:115:24: warning: ‘void nvinfer1::ICudaEngine::destroy()’ is deprecated [-Wdeprecated-declarations]
  this->engine->destroy();
                        ^
In file included from /usr/include/aarch64-linux-gnu/NvInfer.h:54:0,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/common.hpp:10,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/yolov8.hpp:7,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:
/usr/include/aarch64-linux-gnu/NvInferRuntime.h:1485:25: note: declared here
     TRT_DEPRECATED void destroy() noexcept
                         ^~~~~~~
In file included from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:0:
/home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/yolov8.hpp:116:25: warning: ‘void nvinfer1::IRuntime::destroy()’ is deprecated [-Wdeprecated-declarations]
  this->runtime->destroy();
                         ^
In file included from /usr/include/aarch64-linux-gnu/NvInfer.h:54:0,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/common.hpp:10,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/yolov8.hpp:7,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:
/usr/include/aarch64-linux-gnu/NvInferRuntime.h:716:25: note: declared here
     TRT_DEPRECATED void destroy() noexcept
                         ^~~~~~~
In file included from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:0:
/home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/yolov8.hpp: In member function ‘void YOLOv8::letterbox(const cv::Mat&, cv::Mat&, cv::Size&)’:
/home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/yolov8.hpp:238:2: error: no matching function for call to ‘blobFromImage(cv::Mat&, cv::Mat&, float, cv::Size, cv::Scalar, bool, bool, int)’
  );
  ^
In file included from /usr/local/include/opencv2/dnn.hpp:62:0,
                 from /usr/local/include/opencv2/opencv.hpp:62,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/common.hpp:7,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/yolov8.hpp:7,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:
/usr/local/include/opencv2/dnn/dnn.hpp:705:22: note: candidate: cv::Mat cv::dnn::experimental_dnn_v4::blobFromImage(cv::InputArray, double, const Size&, const Scalar&, bool, bool)
     CV_EXPORTS_W Mat blobFromImage(InputArray image, double scalefactor=1.0, const Size& size = Size(),
                      ^~~~~~~~~~~~~
/usr/local/include/opencv2/dnn/dnn.hpp:705:22: note:   candidate expects 6 arguments, 8 provided
/usr/local/include/opencv2/dnn/dnn.hpp:712:21: note: candidate: void cv::dnn::experimental_dnn_v4::blobFromImage(cv::InputArray, cv::OutputArray, double, const Size&, const Scalar&, bool, bool)
     CV_EXPORTS void blobFromImage(InputArray image, OutputArray blob, double scalefactor=1.0,
                     ^~~~~~~~~~~~~
/usr/local/include/opencv2/dnn/dnn.hpp:712:21: note:   candidate expects 7 arguments, 8 provided
/home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp: In function ‘int main(int, char**)’:
/home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:99:42: error: invalid initialization of reference of type ‘std::vector<cv::String>&’ from expression of type ‘std::vector<std::__cxx11::basic_string<char> >’
   cv::glob(path + "/*.jpg", imagePathList);
                                          ^
In file included from /usr/local/include/opencv2/core.hpp:3261:0,
                 from /usr/local/include/opencv2/opencv.hpp:52,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/common.hpp:7,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/yolov8.hpp:7,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:
/usr/local/include/opencv2/core/utility.hpp:186:17: note: in passing argument 2 of ‘void cv::glob(cv::String, std::vector<cv::String>&, bool)’
 CV_EXPORTS void glob(String pattern, std::vector<String>& result, bool recursive = false);
                 ^~~~
CMakeFiles/yolov8.dir/build.make:62: recipe for target 'CMakeFiles/yolov8.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/yolov8.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/yolov8.dir/all' failed
make[1]: *** [CMakeFiles/yolov8.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by triple-Mu** [comment]
It seems that you have old opencv version.
How about `apt-get install libopencv-dev` to upgrade your opencv?

**Comment by jyothir07** [comment]
After updating:
jr_rose@jr_rose-desktop:~/Documents/YOLOv8-TensorRT/csrc/jetson/build$ make
Scanning dependencies of target yolov8
make[2]: *** No rule to make target 'CMakeFiles/yolov8.dir/build'.  Stop.
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/yolov8.dir/all' failed
make[1]: *** [CMakeFiles/yolov8.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by triple-Mu** [comment]
> After updating:
> 
> jr_rose@jr_rose-desktop:~/Documents/YOLOv8-TensorRT/csrc/jetson/build$ make
> 
> Scanning dependencies of target yolov8
> 
> make[2]: *** No rule to make target 'CMakeFiles/yolov8.dir/build'.  Stop.
> 
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/yolov8.dir/all' failed
> 
> make[1]: *** [CMakeFiles/yolov8.dir/all] Error 2
> 
> Makefile:83: recipe for target 'all' failed
> 
> make: *** [all] Error 2
> 
> 

rm -rf build
mkdir build
cmake ..
make -j4

**Comment by jyothir07** [comment]
> > After updating:
> > jr_rose@jr_rose-desktop:~/Documents/YOLOv8-TensorRT/csrc/jetson/build$ make
> > Scanning dependencies of target yolov8
> > make[2]: *** No rule to make target 'CMakeFiles/yolov8.dir/build'.  Stop.
> > CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/yolov8.dir/all' failed
> > make[1]: *** [CMakeFiles/yolov8.dir/all] Error 2
> > Makefile:83: recipe for target 'all' failed
> > make: *** [all] Error 2
> 
> rm -rf build mkdir build cmake .. make -j4

tried this way only. Still the same error

**Comment by jyothir07** [comment]
> > > After updating:
> > > jr_rose@jr_rose-desktop:~/Documents/YOLOv8-TensorRT/csrc/jetson/build$ make
> > > Scanning dependencies of target yolov8
> > > make[2]: *** No rule to make target 'CMakeFiles/yolov8.dir/build'.  Stop.
> > > CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/yolov8.dir/all' failed
> > > make[1]: *** [CMakeFiles/yolov8.dir/all] Error 2
> > > Makefile:83: recipe for target 'all' failed
> > > make: *** [all] Error 2
> > 
> > 
> > rm -rf build mkdir build cmake .. make -j4
> 
> tried this way only. Still the same error
> 
> So less message you provide. Please solve by yourself.

jr_rose@jr_rose-desktop:~/Documents/YOLOv8-TensorRT/csrc/jetson/detect/build$ make -j4
Scanning dependencies of target yolov8
[ 50%] Building CXX object CMakeFiles/yolov8.dir/main.cpp.o
In file included from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:0:
/home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/yolov8.hpp: In destructor ‘YOLOv8::~YOLOv8()’:
/home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/yolov8.hpp:114:25: warning: ‘void nvinfer1::IExecutionContext::destroy()’ is deprecated [-Wdeprecated-declarations]
  this->context->destroy();
                         ^
In file included from /usr/include/aarch64-linux-gnu/NvInfer.h:54:0,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/common.hpp:10,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/yolov8.hpp:7,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:
/usr/include/aarch64-linux-gnu/NvInferRuntime.h:1960:25: note: declared here
     TRT_DEPRECATED void destroy() noexcept
                         ^~~~~~~
In file included from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:0:
/home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/yolov8.hpp:115:24: warning: ‘void nvinfer1::ICudaEngine::destroy()’ is deprecated [-Wdeprecated-declarations]
  this->engine->destroy();
                        ^
In file included from /usr/include/aarch64-linux-gnu/NvInfer.h:54:0,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/common.hpp:10,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/yolov8.hpp:7,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:
/usr/include/aarch64-linux-gnu/NvInferRuntime.h:1485:25: note: declared here
     TRT_DEPRECATED void destroy() noexcept
                         ^~~~~~~
In file included from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:0:
/home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/yolov8.hpp:116:25: warning: ‘void nvinfer1::IRuntime::destroy()’ is deprecated [-Wdeprecated-declarations]
  this->runtime->destroy();
                         ^
In file included from /usr/include/aarch64-linux-gnu/NvInfer.h:54:0,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/common.hpp:10,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/yolov8.hpp:7,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:
/usr/include/aarch64-linux-gnu/NvInferRuntime.h:716:25: note: declared here
     TRT_DEPRECATED void destroy() noexcept
                         ^~~~~~~
In file included from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:0:
/home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/yolov8.hpp: In member function ‘void YOLOv8::letterbox(const cv::Mat&, cv::Mat&, cv::Size&)’:
/home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/yolov8.hpp:238:2: error: no matching function for call to ‘blobFromImage(cv::Mat&, cv::Mat&, float, cv::Size, cv::Scalar, bool, bool, int)’
  );
  ^
In file included from /usr/local/include/opencv2/dnn.hpp:62:0,
                 from /usr/local/include/opencv2/opencv.hpp:62,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/common.hpp:7,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/yolov8.hpp:7,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:
/usr/local/include/opencv2/dnn/dnn.hpp:705:22: note: candidate: cv::Mat cv::dnn::experimental_dnn_v4::blobFromImage(cv::InputArray, double, const Size&, const Scalar&, bool, bool)
     CV_EXPORTS_W Mat blobFromImage(InputArray image, double scalefactor=1.0, const Size& size = Size(),
                      ^~~~~~~~~~~~~
/usr/local/include/opencv2/dnn/dnn.hpp:705:22: note:   candidate expects 6 arguments, 8 provided
/usr/local/include/opencv2/dnn/dnn.hpp:712:21: note: candidate: void cv::dnn::experimental_dnn_v4::blobFromImage(cv::InputArray, cv::OutputArray, double, const Size&, const Scalar&, bool, bool)
     CV_EXPORTS void blobFromImage(InputArray image, OutputArray blob, double scalefactor=1.0,
                     ^~~~~~~~~~~~~
/usr/local/include/opencv2/dnn/dnn.hpp:712:21: note:   candidate expects 7 arguments, 8 provided
/home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp: In function ‘int main(int, char**)’:
/home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:99:42: error: invalid initialization of reference of type ‘std::vector<cv::String>&’ from expression of type ‘std::vector<std::__cxx11::basic_string<char> >’
   cv::glob(path + "/*.jpg", imagePathList);
                                          ^
In file included from /usr/local/include/opencv2/core.hpp:3261:0,
                 from /usr/local/include/opencv2/opencv.hpp:52,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/common.hpp:7,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/yolov8.hpp:7,
                 from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:
/usr/local/include/opencv2/core/utility.hpp:186:17: note: in passing argument 2 of ‘void cv::glob(cv::String, std::vector<cv::String>&, bool)’
 CV_EXPORTS void glob(String pattern, std::vector<String>& result, bool recursive = false);
                 ^~~~
CMakeFiles/yolov8.dir/build.make:62: recipe for target 'CMakeFiles/yolov8.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/yolov8.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/yolov8.dir/all' failed
make[1]: *** [CMakeFiles/yolov8.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by triple-Mu** [comment]
> > > > After updating:
> 
> > > > jr_rose@jr_rose-desktop:~/Documents/YOLOv8-TensorRT/csrc/jetson/build$ make
> 
> > > > Scanning dependencies of target yolov8
> 
> > > > make[2]: *** No rule to make target 'CMakeFiles/yolov8.dir/build'.  Stop.
> 
> > > > CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/yolov8.dir/all' failed
> 
> > > > make[1]: *** [CMakeFiles/yolov8.dir/all] Error 2
> 
> > > > Makefile:83: recipe for target 'all' failed
> 
> > > > make: *** [all] Error 2
> 
> > > 
> 
> > > 
> 
> > > rm -rf build mkdir build cmake .. make -j4
> 
> > 
> 
> > tried this way only. Still the same error
> 
> > 
> 
> > So less message you provide. Please solve by yourself.
> 
> It was showing the same error message i've posted above. :) 
> 
> 
> 
> jr_rose@jr_rose-desktop:~/Documents/YOLOv8-TensorRT/csrc/jetson/detect/build$ make -j4
> 
> Scanning dependencies of target yolov8
> 
> [ 50%] Building CXX object CMakeFiles/yolov8.dir/main.cpp.o
> 
> In file included from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:0:
> 
> /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/yolov8.hpp: In destructor ‘YOLOv8::~YOLOv8()’:
> 
> /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/yolov8.hpp:114:25: warning: ‘void nvinfer1::IExecutionContext::destroy()’ is deprecated [-Wdeprecated-declarations]
> 
>   this->context->destroy();
> 
>                          ^
> 
> In file included from /usr/include/aarch64-linux-gnu/NvInfer.h:54:0,
> 
>                  from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/common.hpp:10,
> 
>                  from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/yolov8.hpp:7,
> 
>                  from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:
> 
> /usr/include/aarch64-linux-gnu/NvInferRuntime.h:1960:25: note: declared here
> 
>      TRT_DEPRECATED void destroy() noexcept
> 
>                          ^~~~~~~
> 
> In file included from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:0:
> 
> /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/yolov8.hpp:115:24: warning: ‘void nvinfer1::ICudaEngine::destroy()’ is deprecated [-Wdeprecated-declarations]
> 
>   this->engine->destroy();
> 
>                         ^
> 
> In file included from /usr/include/aarch64-linux-gnu/NvInfer.h:54:0,
> 
>                  from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/common.hpp:10,
> 
>                  from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/yolov8.hpp:7,
> 
>                  from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:
> 
> /usr/include/aarch64-linux-gnu/NvInferRuntime.h:1485:25: note: declared here
> 
>      TRT_DEPRECATED void destroy() noexcept
> 
>                          ^~~~~~~
> 
> In file included from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:0:
> 
> /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/yolov8.hpp:116:25: warning: ‘void nvinfer1::IRuntime::destroy()’ is deprecated [-Wdeprecated-declarations]
> 
>   this->runtime->destroy();
> 
>                          ^
> 
> In file included from /usr/include/aarch64-linux-gnu/NvInfer.h:54:0,
> 
>                  from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/common.hpp:10,
> 
>                  from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/yolov8.hpp:7,
> 
>                  from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:
> 
> /usr/include/aarch64-linux-gnu/NvInferRuntime.h:716:25: note: declared here
> 
>      TRT_DEPRECATED void destroy() noexcept
> 
>                          ^~~~~~~
> 
> In file included from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:0:
> 
> /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/yolov8.hpp: In member function ‘void YOLOv8::letterbox(const cv::Mat&, cv::Mat&, cv::Size&)’:
> 
> /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/yolov8.hpp:238:2: error: no matching function for call to ‘blobFromImage(cv::Mat&, cv::Mat&, float, cv::Size, cv::Scalar, bool, bool, int)’
> 
>   );
> 
>   ^
> 
> In file included from /usr/local/include/opencv2/dnn.hpp:62:0,
> 
>                  from /usr/local/include/opencv2/opencv.hpp:62,
> 
>                  from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/common.hpp:7,
> 
>                  from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/yolov8.hpp:7,
> 
>                  from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:
> 
> /usr/local/include/opencv2/dnn/dnn.hpp:705:22: note: candidate: cv::Mat cv::dnn::experimental_dnn_v4::blobFromImage(cv::InputArray, double, const Size&, const Scalar&, bool, bool)
> 
>      CV_EXPORTS_W Mat blobFromImage(InputArray image, double scalefactor=1.0, const Size& size = Size(),
> 
>                       ^~~~~~~~~~~~~
> 
> /usr/local/include/opencv2/dnn/dnn.hpp:705:22: note:   candidate expects 6 arguments, 8 provided
> 
> /usr/local/include/opencv2/dnn/dnn.hpp:712:21: note: candidate: void cv::dnn::experimental_dnn_v4::blobFromImage(cv::InputArray, cv::OutputArray, double, const Size&, const Scalar&, bool, bool)
> 
>      CV_EXPORTS void blobFromImage(InputArray image, OutputArray blob, double scalefactor=1.0,
> 
>                      ^~~~~~~~~~~~~
> 
> /usr/local/include/opencv2/dnn/dnn.hpp:712:21: note:   candidate expects 7 arguments, 8 provided
> 
> /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp: In function ‘int main(int, char**)’:
> 
> /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:99:42: error: invalid initialization of reference of type ‘std::vector<cv::String>&’ from expression of type ‘std::vector<std::__cxx11::basic_string<char> >’
> 
>    cv::glob(path + "/*.jpg", imagePathList);
> 
>                                           ^
> 
> In file included from /usr/local/include/opencv2/core.hpp:3261:0,
> 
>                  from /usr/local/include/opencv2/opencv.hpp:52,
> 
>                  from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/common.hpp:7,
> 
>                  from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/./include/yolov8.hpp:7,
> 
>                  from /home/jr_rose/Documents/YOLOv8-TensorRT/csrc/jetson/detect/main.cpp:5:
> 
> /usr/local/include/opencv2/core/utility.hpp:186:17: note: in passing argument 2 of ‘void cv::glob(cv::String, std::vector<cv::String>&, bool)’
> 
>  CV_EXPORTS void glob(String pattern, std::vector<String>& result, bool recursive = false);
> 
>                  ^~~~
> 
> CMakeFiles/yolov8.dir/build.make:62: recipe for target 'CMakeFiles/yolov8.dir/main.cpp.o' failed
> 
> make[2]: *** [CMakeFiles/yolov8.dir/main.cpp.o] Error 1
> 
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/yolov8.dir/all' failed
> 
> make[1]: *** [CMakeFiles/yolov8.dir/all] Error 2
> 
> Makefile:83: recipe for target 'all' failed
> 
> make: *** [all] Error 2
> 
> 


pkg-config --modversion opencv4
Show me your opencv version

**Comment by triple-Mu** [comment]
Make you are in csrc/jetson/detect/end2end

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
