### ISSUE TITLE
能不能新增个分类模型？

### ISSUE THREAD

**Issue by tendrillion** [triple-Mu/YOLOv8-TensorRT#114]
我没有找到分类模型，能不能新增个图像分类模型？

**Comment by triple-Mu** [comment]
> 我没有找到分类模型，能不能新增个图像分类模型？

分类的比较简单。后处理基本上没什么操作，所以目前没打算做。

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
