### ISSUE TITLE
Worse detection precision compared to pytorch inference

### ISSUE THREAD

**Issue by HauJulian** [triple-Mu/YOLOv8-TensorRT#115]
The average precision on the coco dataset (IoU=0.50:0.95) drops by about 5 % when using tensorrt compared to the pytorch inference. Is there something wrong with my model or is this expected behaviour?
When generating the engine, I get the following warning:
`[TRT] [W]  - Subnormal FP16 values detected.`
`[TRT] [W] If this is not the desired behavior, please modify the weights or retrain with regularization to reduce the magnitude of the weights.`

**Comment by triple-Mu** [comment]
> The average precision on the coco dataset (IoU=0.50:0.95) drops by about 5 % when using tensorrt compared to the pytorch inference. Is there something wrong with my model or is this expected behaviour?
> 
> When generating the engine, I get the following warning:
> 
> `[TRT] [W]  - Subnormal FP16 values detected.`
> 
> `[TRT] [W] If this is not the desired behavior, please modify the weights or retrain with regularization to reduce the magnitude of the weights.`
> 
> 

Try to decrease conf-thres such as 0.01 and then verify your map result.

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
