### ISSUE TITLE
Cannot detect any object on Jetson NX

### ISSUE THREAD

**Issue by codedao360** [triple-Mu/YOLOv8-TensorRT#117]
I followed the steps, but no objects were detected when conducting inference with pictures, video, and cameras.
![Screenshot from 2023-06-19 09-24-59](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/67302134/eebb2348-e615-4b39-969e-9a84f1c96d3c)
System:
-Jetson NX 8GB
- Deepstream 6.2
- Jetpack 5.1.1
- Cuda 11.4
- Tensorrt 8.5.2.2

```
~/temp/YOLOv8-TensorRT$ ./yolov8 yolov8s.engine data/bus.jpg
model warmup 10 times
cost 40.8140 ms

```

**Comment by triple-Mu** [comment]
How do you get engine?
Do you using export-det.py?

**Comment by codedao360** [comment]
Yes. I followed the guideline here: https://github.com/triple-Mu/YOLOv8-TensorRT/blob/main/docs/Jetson.md
I tried to get ONNX two methods: 
- from Jetson NX
- from Ubuntu PC
by using export-det.py
but the two methods are both not work.

Of course, I used trtexec from Jetson to generate .engine files as the guideline.

**Comment by triple-Mu** [comment]
> Yes. I followed the guideline here: https://github.com/triple-Mu/YOLOv8-TensorRT/blob/main/docs/Jetson.md I tried to get ONNX two methods:
> 
> * from Jetson NX
> * from Ubuntu PC
>   by using export-det.py
>   but the two methods are both not work.
> 
> Of course, I used trtexec from Jetson to generate .engine files as the guideline.

Have you test the onnx convert engine on your pc?
Suggest you testing acc on pc and then verify it on jetson.

**Comment by codedao360** [comment]
I have an error when infer using infer-det.py by using PC (GPU 2060 Super)
**When convert ONNX**
`OLOv8s summary (fused): 168 layers, 11156544 parameters, 0 gradients, 28.6 GFLOPs
[W shape_type_inference.cpp:1920] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
[W shape_type_inference.cpp:1920] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
[W shape_type_inference.cpp:1920] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
[W shape_type_inference.cpp:1920] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
============= Diagnostic Run torch.onnx.export version 2.0.1+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 4 WARNING 0 ERROR ========================
4 WARNING were not printed due to the log level.`

When using tensorrt trtexec .engine is okie.
But when I used infer-det
`[06/19/2023-20:33:53] [TRT] [E] 1: [stdArchiveReader.cpp::StdArchiveReader::30] Error Code 1: Serialization (Serialization assertion magicTagRead == kMAGIC_TAG failed.Magic tag does not match)
[06/19/2023-20:33:53] [TRT] [E] 4: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)
Traceback (most recent call last):
  File "/home/tungpx2/temp/YOLOv8-TensorRT/infer-det.py", line 82, in <module>
    main(args)
  File "/home/tungpx2/temp/YOLOv8-TensorRT/infer-det.py", line 15, in main
    Engine = TRTModule(args.engine, device)
  File "/home/tungpx2/temp/YOLOv8-TensorRT/models/engine.py", line 218, in __init__
    self.__init_engine()
  File "/home/tungpx2/temp/YOLOv8-TensorRT/models/engine.py", line 227, in __init_engine
    context = model.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'`

**Comment by triple-Mu** [comment]
trtexec's trt version is mismatch python tensorrt.
Suggest using build.py for building engine.

**Comment by triple-Mu** [comment]
Do not install tensorrt by pip install tensorrt if you want to use c++ api.
You can download TensorRT.xxxx.tar.gz and find package in TensorRT.xxxx/python.

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
