### ISSUE TITLE
segmentation fault on jetson

### ISSUE THREAD

**Issue by asflower** [triple-Mu/YOLOv8-TensorRT#118]
System:
-Jetson NX 8GB

* Deepstream 6.2
* Jetpack 5.1.1
* Cuda 11.4
* Tensorrt 8.5.2.2

after build the jetson code in csrc/jetson/detect, when i run the command line: ./yolov8 <engine> <image-folder>
segmentation fault occurred on postprocess

does anybody has the same issue?

**Comment by triple-Mu** [comment]
Could you please show me detail log.

**Comment by asflower** [comment]
sure, here is the gdb debug output:

![image](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/16401446/e1d2fe9c-3459-4d13-9e90-30a1f579bad8)

**Comment by pacientes** [comment]
check `ptr` `boxes` `scores` memory address

**Comment by triple-Mu** [comment]
Please use `export-det.py` for end2end export and then use `csrc/detect/end2end`.

**Comment by jscottsf** [comment]
Late to the party here. Having the exact same issue on Jetpack 4.6.4 with the Nano.
