### ISSUE TITLE
build on tensorrt 7.1 will get error, NMS plugin not supported

### ISSUE THREAD

**Issue by ywangwxd** [triple-Mu/YOLOv8-TensorRT#121]
Can NMS plugin be adpated to tenssort 7.x? Get old tx2 jetson device here, only support trt 7.x.

**Comment by triple-Mu** [comment]
Sorry. This repo only support trt8.x+.
If you want to use in trt7.x. You should modify the nms plugin to batchednmsplugin by yourself.

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
