### ISSUE TITLE
batch inferencing

### ISSUE THREAD

**Issue by slgao** [triple-Mu/YOLOv8-TensorRT#123]
Can you please add batch inferencing on the C++ YOLOv8 segmentation part ?  (csrc/segment/normal/)
Thank you very much!

**Comment by triple-Mu** [comment]
> Can you please add batch inferencing on the C++ YOLOv8 segmentation part ?  (csrc/segment/normal/)
> 
> Thank you very much!

You can try cv::dnn::blobFromImage then a list of mat will convert to nchw format.
And using for loop for postprocess.

**Comment by slgao** [comment]
I tried with continuously copying the memory from cpu to gpu by using a list of nchw objects, like below

![image](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/1963614/1810b51e-ffa4-4809-9613-f341f6b002db)


but the output dimension is not correct, I still have couple of questions, can I add your wechat account to ask you ? thank you!

**Comment by slgao** [comment]
> Referen
you meant the cv::dnn::blobFromImages API for image arrays ?

**Comment by slgao** [comment]
I am able to do the Batch inferencing with the cpp code from (csrc/segment/normal/), but the copyMat function takes more time than linear for multiple images. that means for example if I use one image, the copyMat function takes 0,004 seconds, but If I use a batch size  equals to 16 images, it would take around 0.17 seconds, which is far more larger than the linear increase 0.004x16 = 0.064 seconds, any ideas of how to make the preprocessing  faster ? I would appreciate it very much.

**Comment by triple-Mu** [comment]
> I am able to do the Batch inferencing with the cpp code from (csrc/segment/normal/), but the copyMat function takes more time than linear for multiple images. that means for example if I use one image, the copyMat function takes 0,004 seconds, but If I use a batch size equals to 16 images, it would take around 0.17 seconds, which is far more larger than the linear increase 0.004x16 = 0.064 seconds, any ideas of how to make the preprocessing faster ? I would appreciate it very much.

Maybe you can try `openmp`.
Or you can use cuda to accelerate.

**Comment by slgao** [comment]
Is it possible to use CUDA to accelarate the cv::dnn:blobFromImage function ?  
I have no idea how to do that, Could you please give me some hint? Thank you!

OpenMP to my knowledge is to parallel to the cpu cores, correct ?

**Comment by triple-Mu** [comment]
> Is it possible to use CUDA to accelarate the cv::dnn:blobFromImage function ?  
> 
> I have no idea how to do that, Could you please give me some hint? Thank you!
> 
> 
> 
> OpenMP to my knowledge is to parallel to the cpu cores, correct ? 

I mean using cuda kernel for doing preprocess.
Openmp is cpu base. You can easy use it to convert every image format to nchw in independent thread.

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!

**Comment by Egorundel** [comment]
@triple-Mu Hello! Do you have an example of using batch inferencing in your code?
