### ISSUE TITLE
YOLOV8 pose for multi classes

### ISSUE THREAD

**Issue by lishiyu005** [triple-Mu/YOLOv8-TensorRT#124]
Dear author,

I train YOLOv8 pose for multi-class labels (not only person, but also some other objects). However, when I convert the .pt model to tensorrt, the result is not correct. There is no detection output. How can I change the script to fix this issue?

Another question I have is the parameter topk. In your script, there are parameters:
    int topk = 100;
    float score_thres = 0.25f;
    float iou_thres = 0.65f;
What is topk? I do not understand this variable.

Thank you very much.

Best regards

**Comment by triple-Mu** [comment]
> Dear author,
> 
> 
> 
> I train YOLOv8 pose for multi-class labels (not only person, but also some other objects). However, when I convert the .pt model to tensorrt, the result is not correct. There is no detection output. How can I change the script to fix this issue?
> 
> 
> 
> Another question I have is the parameter topk. In your script, there are parameters:
> 
>     int topk = 100;
> 
>     float score_thres = 0.25f;
> 
>     float iou_thres = 0.65f;
> 
> What is topk? I do not understand this variable.
> 
> 
> 
> Thank you very much.
> 
> 
> 
> Best regards

You should modify pose postprocess.
Default is only one class so that the score is only for person.
But if enable multiclass you should use argmax and max to find the highest score and label.

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
