### ISSUE TITLE
why tensorrt engine model  输出的box是大于1的数？

### ISSUE THREAD

**Issue by northeastsquare** [triple-Mu/YOLOv8-TensorRT#125]
我理解 tensorrt engine model box输出应该是[0, 1], 但是 https://github.com/triple-Mu/YOLOv8-TensorRT/blob/main/csrc/pose/normal/include/yolov8-pose.hpp#L361 ，中dw是原图resize后填充的一半，是整数，
应该对网络输出 x image_width，后才能相加减。
我打印出 float x = *bboxes_ptr++ - dw;
中bboxes_ptr指向的值，竟然是几十的数，为什么会这样？

**Comment by triple-Mu** [comment]
> 我理解 tensorrt engine model box输出应该是[0, 1], 但是 https://github.com/triple-Mu/YOLOv8-TensorRT/blob/main/csrc/pose/normal/include/yolov8-pose.hpp#L361 ，中dw是原图resize后填充的一半，是整数， 应该对网络输出 x image_width，后才能相加减。 我打印出 float x = *bboxes_ptr++ - dw; 中bboxes_ptr指向的值，竟然是几十的数，为什么会这样？

因为decoder放在模型里面了。所以输出的就是正常尺寸的box
