### ISSUE TITLE
nvinfer1::SerializationError

### ISSUE THREAD

**Issue by dulishu1999** [triple-Mu/YOLOv8-TensorRT#128]
I directly used the engine model exported by yolov8, and then used tensorrt8.6 to do inference, and reported an error after running

**Comment by triple-Mu** [comment]
> I directly used the engine model exported by yolov8, and then used tensorrt8.6 to do inference, and reported an error after running

Try to export onnx first and use `trtexec` to convert to engine.

**Comment by dulishu1999** [comment]
the same error was reported

**Comment by dulishu1999** [comment]
I'm about to crash

**Comment by dulishu1999** [comment]
have you verified it in Windows？

**Comment by triple-Mu** [comment]
> have you verified it in Windows？

Sorry. I don't use windows for coding..

**Comment by dulishu1999** [comment]
Sorry I may have a bad attitude, I just wanted to fix this, I tried running your /csrc/segment/normal code on windows, but it doesn't seem to work

**Comment by dulishu1999** [comment]
Sorry I may have a bad attitude, I just wanted to fix this, I tried running your /csrc/segment/normal code on windows, but it doesn't seem to work

**Comment by dulishu1999** [comment]
and i didnt know how to fix this

**Comment by triple-Mu** [comment]
> and i didnt know how to fix this

If you need my help, please provide detailed operation steps and corresponding logs. Otherwise, there's nothing I can do

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
