### ISSUE TITLE
Pytorch dependency

### ISSUE THREAD

**Issue by DirkKramer** [triple-Mu/YOLOv8-TensorRT#13]
First of all, great work on this repository. I managed to export an instance segmentation model to TensorRT and it works perfectly.

My question is: Is it possible to create an inference script without a dependency to Pytorch?

**Comment by triple-Mu** [comment]
PyTorch's forward function executes faster and is a good choice if you reason through Python. 
In addition, you can also use `cupy` or `cuda-python` or `pycuda`, but I think their performance is not as good as Pytorch.

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!

**Comment by triple-Mu** [comment]
Good news !
Now we support tensorrt inference without pytorch.
See more in [`infer-no-torch.py`](https://github.com/triple-Mu/YOLOv8-TensorRT/blob/main/infer-no-torch.py)

**Comment by DirkKramer** [comment]
> @DirkKramer Good news ! Now we support tensorrt inference without pytorch. See more in [`infer-no-torch.py`](https://github.com/triple-Mu/YOLOv8-TensorRT/blob/main/infer-no-torch.py)

Looks good, I will try this out later!
