### ISSUE TITLE
Win10可以部署成功，除修改Cmake路径外，还需如下修改。

### ISSUE THREAD

**Issue by WYQ-Github** [triple-Mu/YOLOv8-TensorRT#130]
1. 新建unistd.h头文件放入`C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include`中
~~~
#ifndef _UNISTD_H
#define _UNISTD_H
constexpr auto F_OK = 0;
#endif /* _UNISTD_H */
~~~
2. common.hpp修改
~~~
return (stat(path.c_str(), &buffer) == 0 && S_IFREG*(buffer.st_mode));
return (stat(path.c_str(), &buffer) == 0 && S_IFDIR*(buffer.st_mode));
~~~

**Comment by triple-Mu** [comment]
您可以在`csrc`下pr一个检测的例子然后加一个readme，我会尽快合并。不知道您是否有兴趣呢？

**Comment by ccplanet** [comment]
改过之后，unistd.h里还缺少access()方法，改用win10的#include <io.h> 里面的_access()，还是运行报错，求怎样能在windows上正确运行的方法

**Comment by Zigars** [comment]
@WYQ-Github 能分享一下cmake文件嘛

**Comment by mwcheng1994** [comment]
ERROR: 1: [runtime.cpp::nvinfer1::Runtime::parsePlan::314] Error Code 1: Serialization (Serialization assertion plan->header.magicTag == rt::kPLAN_MAGIC_TAG failed.) 我修改下代码，模型和图片硬编码，跑起来出现这样的错误！

**Comment by triple-Mu** [comment]
> ERROR: 1: [runtime.cpp::nvinfer1::Runtime::parsePlan::314] Error Code 1: Serialization (Serialization assertion plan->header.magicTag == rt::kPLAN_MAGIC_TAG failed.) 我修改下代码，模型和图片硬编码，跑起来出现这样的错误！

请使用trtexec转换onnx到engine.因为需要保证转换的tensorrt跟c++加载的一致，你这个问题可能是python版本不同导致的
