### ISSUE TITLE
No detections found with custom segmentation model

### ISSUE THREAD

**Issue by Terizian** [triple-Mu/YOLOv8-TensorRT#131]
I've trained a custom segmentation model using the yolov8 repository and followed the steps in the Segment.md file. Even though the pt model results in detections, after converting to engine and running the infer-seg.py script on my images, I am getting "no object!".

**Comment by Terizian** [comment]
Actually, I just tested on the yolov8m-seg original model and same scenario. The nano model works fine

**Comment by triple-Mu** [comment]
> Actually, I just tested on the yolov8m-seg original model and same scenario. The nano model works fine

Do you modify the class names?
Could you please upload your onnx and one image ?

**Comment by Terizian** [comment]
> > Actually, I just tested on the yolov8m-seg original model and same scenario. The nano model works fine
> 
> 
> 
> Do you modify the class names?
> 
> Could you please upload your onnx and one image ?

Sorry for the late reply. Yes, I did modify the class names. I can share the model, but unfortunately the image is not something I can share. How can we proceed?

**Comment by triple-Mu** [comment]
> > > Actually, I just tested on the yolov8m-seg original model and same scenario. The nano model works fine
> > 
> > 
> > Do you modify the class names?
> > Could you please upload your onnx and one image ?
> 
> Sorry for the late reply. Yes, I did modify the class names. I can share the model, but unfortunately the image is not something I can share. How can we proceed?

You can give me a test image and your pt model or onnx model.

**Comment by kishcs** [comment]
I am facing similar issue. Trained a custom Yolov8 Seg model.
Converted `pt` to `onnx` with `export-seg.py` and `onnx` to `engine` with `build.py`.
It works in TensorRT version `8.4.0.6`, but when I convert in TensorRT version `8.4.1.5` or `8.4.2.4`., it gives all classes as class 0.

I am not able to understand what is the issue?
What could be the issue?

**Comment by triple-Mu** [comment]
> I am facing similar issue. Trained a custom Yolov8 Seg model. Converted `pt` to `onnx` with `export-seg.py` and `onnx` to `engine` with `build.py`. It works in TensorRT version `8.4.0.6`, but when I convert in TensorRT version `8.4.1.5` or `8.4.2.4`., it gives all classes as class 0.
> 
> I am not able to understand what is the issue? What could be the issue?

could you please upload your onnx model?
