### ISSUE TITLE
`cv::dnn::blobFromImage` cost too much too much time In csrc/detect

### ISSUE THREAD

**Issue by willwang-cv** [triple-Mu/YOLOv8-TensorRT#136]
as is shown in the image below:
![2023-08-16 17-09-33 的屏幕截图](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/29682883/d67889cc-92fc-44c8-bae4-15ebacbd7a6c)
for every frame, **pre-process** cost almost **9.67ms**(while the sum of pre-process、infer-process、post_process is **just 10.96ms**), and the function `cv::dnn::blobFromImage` cost almost 5~9ms, and it is a huge loss for performance...
![2023-08-16 17-15-10 的屏幕截图](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/29682883/13f06c73-ce3d-492d-9072-62f3f7d3b58e)

Are there any alternative solutions to improve FPS based on `cv::dnn::blobFromImage`?  3Q 😁😁😁

**Comment by willwang-cv** [comment]
> > as is shown in the image below: ![2023-08-16 17-09-33 的屏幕截图](https://user-images.githubusercontent.com/29682883/260960173-d67889cc-92fc-44c8-bae4-15ebacbd7a6c.png) for every frame, **pre-process** cost almost **9.67ms**(while the sum of pre-process、infer-process、post_process is **just 10.96ms**), and the function `cv::dnn::blobFromImage` cost almost 5~9ms, and it is a huge loss for performance... ![2023-08-16 17-15-10 的屏幕截图](https://user-images.githubusercontent.com/29682883/260961637-13f06c73-ce3d-492d-9072-62f3f7d3b58e.png)
> > Are there any alternative solutions to improve FPS based on `cv::dnn::blobFromImage`? 3Q 😁😁😁
> 
> WarpAffine cuda kernel.

Good Idea, Thank you and your repo.

**Comment by AntoineChauviere** [comment]
Hello ! How did you replace your blobfromimage function with CUDA's warp affine to optimize performance, please?
