### ISSUE TITLE
infer-seg-without-torch 推理错误

### ISSUE THREAD

**Issue by Zigars** [triple-Mu/YOLOv8-TensorRT#143]
你好 我在使用infer-seg-without-torch推理trt模型时出现错误。

![image](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/32835472/6a070a89-843e-4fda-a072-d97226520e0e)

我的模型是通过u版的export转成onnx，再通过trtexec转为engine，class是32类，images_size是1280，对应的代码是这一块，我不太理解图中红框这句操作的作用。

![image](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/32835472/c003eebe-e519-42dd-ba7e-29da0d481b73)

**Comment by triple-Mu** [comment]
> 你好 我在使用infer-seg-without-torch推理trt模型时出现错误。
> 
> 
> 
> ![image](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/32835472/6a070a89-843e-4fda-a072-d97226520e0e)
> 
> 
> 
> 我的模型是通过u版的export转成onnx，再通过trtexec转为engine，class是32类，images_size是1280，对应的代码是这一块，我不太理解图中红框这句操作的作用。
> 
> 
> 
> ![image](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/32835472/c003eebe-e519-42dd-ba7e-29da0d481b73)
> 
> 

请仔细查看readme中的介绍。
我提供的推理代码不能直接推理v8仓库导出的onnx，请使用export-seg.py导出在做转换。

**Comment by Zigars** [comment]
> > 你好 我在使用infer-seg-without-torch推理trt模型时出现错误。
> > ![image](https://user-images.githubusercontent.com/32835472/263221253-6a070a89-843e-4fda-a072-d97226520e0e.png)
> > 我的模型是通过u版的export转成onnx，再通过trtexec转为engine，class是32类，images_size是1280，对应的代码是这一块，我不太理解图中红框这句操作的作用。
> > ![image](https://user-images.githubusercontent.com/32835472/263221977-c003eebe-e519-42dd-ba7e-29da0d481b73.png)
> 
> 请仔细查看readme中的介绍。 我提供的推理代码不能直接推理v8仓库导出的onnx，请使用export-seg.py导出在做转换。

我需要使用你这边export-seg.py导出onnx，再转换trt，c++部署选择csrc\segment\simple，这个流程对嘛

**Comment by triple-Mu** [comment]
是的

**Comment by Zigars** [comment]
感谢大佬的回答！因为我这边按照normal的方式跑通了C++，但是想先用python版本做pipeline，然后推理的时候发现后处理部分有些问题，我后面换成simple的方式试一下！
