### ISSUE TITLE
infer-seg.py 

### ISSUE THREAD

**Issue by Addoxx** [triple-Mu/YOLOv8-TensorRT#146]
Hey! 

Can we run the segmentation model using webcam? I tried to use opencv to read the frames and pass it through the script but seems like seg_postprocess function is returning an empty output_size tensor.

Traceback (most recent call last):
  File "infer-seg.py", line 117, in <module>
    main(args)
  File "infer-seg.py", line 41, in main
    bboxes, scores, labels, masks = seg_postprocess(
  File "YOLOv8-TensorRT/models/torch_utils.py", line 28, in seg_postprocess
    masks = F.interpolate(masks[None],
  File ".local/lib/python3.8/site-packages/torch/nn/functional.py", line 3921, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors)
RuntimeError: Non-empty 4D data tensor expected but got a tensor with sizes [1, 0, 160, 120]

Regards,
Adhok

**Comment by triple-Mu** [comment]
First run `export-seg.py` export onnx.
Second run `trtexec` to convert onnx to engine.
Third run `infer-seg.py`.

**Comment by Addoxx** [comment]
It works for images but I am trying to run the segmentation inference on my webcam. Please help me out or point me in the right direction.

I really appreciate any help you can provide.

Best regards,
Adhok

**Comment by triple-Mu** [comment]
> 

Maybe the webcam is the same as photos.
You can get per frame and infer with tensorrt in one loop.
``` python
capture = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    # frame forward and show
    ....
```
