### ISSUE TITLE
loading included nms onnx model on Triton 

### ISSUE THREAD

**Issue by whitewalker11** [triple-Mu/YOLOv8-TensorRT#148]
while loading model on triton error is coming 

 UNAVAILABLE: Internal: onnx runtime error 1: Load model from /models/yolov8_onnx/1/model.onnx failed:Fatal error: TRT:EfficientNMS_TRT(-1) is not a registered function/op |
 
 how to use EfficientNMS_TRT  plugin while loading model in TRITON

**Comment by triple-Mu** [comment]
This is a tensorrt base repo.
So the plugin named 'EfficientNMS_TRT' is only for tensorrt and not for onnxruntime.

**Comment by whitewalker11** [comment]
how can we use plugin while loading model on Triton
