### ISSUE TITLE
Export model with dynamic batch_size, dynamic shapes and NMS plugin

### ISSUE THREAD

**Issue by Egorundel** [triple-Mu/YOLOv8-TensorRT#151]
Hi, I need to get out of `yolov8.pt` create ONNX-model with **dynamic batch_size** and **dynamic dimensions (dynamic shapes)**. Is it possible to do this with the help of your repository? Do I need to use the `triplemu/dynamic` branch for this? Is it working and does what I wrote above?

**Comment by Egorundel** [comment]
Yes, this is what I need, I apologize for the trouble, I close the issue.

**Comment by smsver2** [comment]
Hello @Egorundel. 
Did you find the answer to your question? If so, how did you manage to export your ONNX
Model with NMS plugin and dynamic dimensions?
