### ISSUE TITLE
推理之前image的shape不需要做从nhwc->nchw的转换吗

### ISSUE THREAD

**Issue by NLPOR** [triple-Mu/YOLOv8-TensorRT#153]
` image = cv::imread(path);
   yolov8->copy_from_Mat(image, size);
  auto start = std::chrono::system_clock::now();
   yolov8->infer();`
imread之后的image是nhwc的，在infer之前不需要转成nchw吗，这个转换代码在copy_from_Mat(image, size)中好像没有看到，请问是不用做转换吗

**Comment by triple-Mu** [comment]
> ` image = cv::imread(path); yolov8->copy_from_Mat(image, size); auto start = std::chrono::system_clock::now(); yolov8->infer();` imread之后的image是nhwc的，在infer之前不需要转成nchw吗，这个转换代码在copy_from_Mat(image, size)中好像没有看到，请问是不用做转换吗

`cv::dnn::blobFromImage` api

**Comment by NLPOR** [comment]
好的，谢谢
