### ISSUE TITLE
Problem with instance segmentation when resolution size is not square in C++ inference

### ISSUE THREAD

**Issue by Zigars** [triple-Mu/YOLOv8-TensorRT#154]
Inference have no problem in 2560*2560 resolution, but error in 1280*2560. 
models export to onnx’s input-shape is 1 3 1280 2560, and test in python infer success.

![image](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/32835472/58f669cb-1aa6-4206-8dc1-fedc9649025b)

![image](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/32835472/ad940663-349d-4e62-ac0a-166764dac12d)

**Comment by triple-Mu** [comment]
> Inference have no problem in 2560_2560 resolution, but error in 1280_2560. models export to onnx’s input-shape is 1 3 1280 2560, and test in python infer success.
> 
> ![image](https://user-images.githubusercontent.com/32835472/267007958-58f669cb-1aa6-4206-8dc1-fedc9649025b.png)
> 
> ![image](https://user-images.githubusercontent.com/32835472/267008044-ad940663-349d-4e62-ac0a-166764dac12d.png)

You should also modify the seg_h and seg_w to your own model size.
4x down sample
