### ISSUE TITLE
Color for mask in segmentation

### ISSUE THREAD

**Issue by vutuanhungkkk** [triple-Mu/YOLOv8-TensorRT#156]
Can I change the color of mask to not transparent , my purpose is to cover the detected object in black and that object can't be seen. I tried change the mask color and alpha in config.py but it still transparent and can be seen. Please help me.

**Comment by triple-Mu** [comment]
> Can I change the color of mask to not transparent , my purpose is to cover the detected object in black and that object can't be seen. I tried change the mask color and alpha in config.py but it still transparent and can be seen. Please help me.

You should modify here: https://github.com/triple-Mu/YOLOv8-TensorRT/blob/main/infer-seg.py#L56
