### ISSUE TITLE
Parameters for C++ Inference

### ISSUE THREAD

**Issue by Flippchen** [triple-Mu/YOLOv8-TensorRT#158]
Hey,

first of all nice project.

I have a question regarding the input parameters for the segmentation in c++

![image](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/91947480/08ee432b-9234-49e6-bed7-969c3b1a7586)

The size variable is the input size of the model right?

But what is seg_h, seg_w, and seg_channels?

I have a model with 608 (h) x 1280 (w) and want to segment on an image which is 1280 x 720p.

**Comment by Flippchen** [comment]
Hey, we also have a lot of problems with the mask and don't know why. The model worked fine in Python with perfect masks. The masks here are completely "random" and the resulting mask for the cone is pretty bad. 

![image](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/91947480/7b0340e3-c7c9-4108-9bc2-e3c717284621)
![image](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/91947480/005188fb-1649-4a60-ac2b-183210e66132)
![image](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/91947480/914014b7-48f2-45d2-bafd-1825bf14fa34)

```
if (masks.empty()) {
        printf("Mask empty");
        // masks is empty
    }
    else {
        printf("Mask not empty");
        cv::Mat matmulRes = (masks * protos).t();
        cv::Mat maskMat   = matmulRes.reshape(indices.size(), {seg_w, seg_h});

        std::vector<cv::Mat> maskChannels;
        cv::split(maskMat, maskChannels);
        printf("Num channels: %d", maskChannels.size());
        for (auto channel : maskChannels) {
            cv::imshow("channel", channel);
            cv::waitKey(0);
            cv::destroyAllWindows();
        }
```

**Comment by triple-Mu** [comment]
size is the network input size like 640*640
topk is the max number of results after postprocess
seg_h is the proto shape like (640/4) * (640/4) : 4x downsample
seg_channel is the proto channels.

If your network input shape is 608 * 1280
You may set seg_h as 608/4, set seg_w as 1280/4.

**Comment by Flippchen** [comment]
Thanks, that helped a lot :)
