### ISSUE TITLE
fatal error: NvInferPlugin.h: No files or folders of this type   

### ISSUE THREAD

**Issue by The-Quantum** [triple-Mu/YOLOv8-TensorRT#159]
I cloned and install the requirement for `YOLOv8-TensorRT`.  Following, I exported the onnx model by `ultralytics` using `export-det.py` package as recommanded in the readme. Then, I build End2End Engine from ONNX using `build.py` module. The python inference works well. However, the inference with c++ provides the following error.
```
In file included from /YOLOv8-TensorRT/csrc/detect/end2end/main.cpp:6:
/YOLOv8-TensorRT/csrc/detect/end2end/include/yolov8.hpp:6:10: fatal error: NvInferPlugin.h: Aucun fichier ou dossier de ce type
    6 | #include "NvInferPlugin.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/yolov8.dir/build.make:76 : CMakeFiles/yolov8.dir/main.cpp.o] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:83 : CMakeFiles/yolov8.dir/all] Erreur 2
make: *** [Makefile:91 : all] Erreur 2
```

I thing this is related to `tensorrt`. I installed the tensorrt package using pip `requirements.txt` file after uncommenting tensorrt, cuda-python and pycuda lines.   
I'm using ubuntu 22.04 and conda virtual env.

**Comment by triple-Mu** [comment]
Please set TensorRT include dir and lib dir in CMakeLists.txt
