### ISSUE TITLE
CMakeListe.txt for gcc10 on jetson nano

### ISSUE THREAD

**Issue by MoussaGRICHE** [triple-Mu/YOLOv8-TensorRT#161]
Hello triple-Mu,

Hope you are doing well.

I have updated the gcc to gcc 10 on my jetson nano because I need Coroutines in my code (c++ 20).

The actual CMakeLists.txt gives me error:

                          The CUDA compiler identification is unknown
                          -- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
                          -- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- broken
                          CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCUDACompiler.cmake:46 (message):
                            The CUDA compiler
                          
                              "/usr/local/cuda/bin/nvcc"
                          
                            is not able to compile a simple test program.
                          
                            It fails with the following output:
                          
                              Change Dir: /home/tts/Desktop/Mandelieu/comptage/build/CMakeFiles/CMakeTmp
                              
                              Run Build Command:"/usr/bin/make" "cmTC_833f9/fast"
                              /usr/bin/make -f CMakeFiles/cmTC_833f9.dir/build.make CMakeFiles/cmTC_833f9.dir/build
                              make[1]: Entering directory '/home/tts/Desktop/Mandelieu/comptage/build/CMakeFiles/CMakeTmp'
                              Building CUDA object CMakeFiles/cmTC_833f9.dir/main.cu.o
                              /usr/local/cuda/bin/nvcc     -x cu -c /home/tts/Desktop/Mandelieu/comptage/build/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_833f9.dir/main.cu.o
                              In file included from /usr/local/cuda/bin/../targets/aarch64-linux/include/cuda_runtime.h:83,
                                               from <command-line>:
                              /usr/local/cuda/bin/../targets/aarch64-linux/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
                                138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
                                    |  ^~~~~
                              CMakeFiles/cmTC_833f9.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_833f9.dir/main.cu.o' failed
                              make[1]: *** [CMakeFiles/cmTC_833f9.dir/main.cu.o] Error 1
                              make[1]: Leaving directory '/home/tts/Desktop/Mandelieu/comptage/build/CMakeFiles/CMakeTmp'
                              Makefile:126: recipe for target 'cmTC_833f9/fast' failed
                              make: *** [cmTC_833f9/fast] Error 2
                              
                          
                            
                          
                            CMake will not be able to correctly generate this project.
                          Call Stack (most recent call first):
                            CMakeLists.txt:6 (project)
                          
                          
                          -- Configuring incomplete, errors occurred!
                          See also "/home/tts/Desktop/Mandelieu/comptage/build/CMakeFiles/CMakeOutput.log".
                          See also "/home/tts/Desktop/Mandelieu/comptage/build/CMakeFiles/CMakeError.log".

I would ask you how should I do to change the CMakesListes.txt in order to use gcc10 and c++20.

Thank you

**Comment by triple-Mu** [comment]
> Hello triple-Mu,
> 
> Hope you are doing well.
> 
> I have updated the gcc to gcc 10 on my jetson nano because I need Coroutines in my code (c++ 20).
> 
> The actual CMakeLists.txt gives me error:
> 
> ```
>                       The CUDA compiler identification is unknown
>                       -- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
>                       -- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- broken
>                       CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCUDACompiler.cmake:46 (message):
>                         The CUDA compiler
>                       
>                           "/usr/local/cuda/bin/nvcc"
>                       
>                         is not able to compile a simple test program.
>                       
>                         It fails with the following output:
>                       
>                           Change Dir: /home/tts/Desktop/Mandelieu/comptage/build/CMakeFiles/CMakeTmp
>                           
>                           Run Build Command:"/usr/bin/make" "cmTC_833f9/fast"
>                           /usr/bin/make -f CMakeFiles/cmTC_833f9.dir/build.make CMakeFiles/cmTC_833f9.dir/build
>                           make[1]: Entering directory '/home/tts/Desktop/Mandelieu/comptage/build/CMakeFiles/CMakeTmp'
>                           Building CUDA object CMakeFiles/cmTC_833f9.dir/main.cu.o
>                           /usr/local/cuda/bin/nvcc     -x cu -c /home/tts/Desktop/Mandelieu/comptage/build/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_833f9.dir/main.cu.o
>                           In file included from /usr/local/cuda/bin/../targets/aarch64-linux/include/cuda_runtime.h:83,
>                                            from <command-line>:
>                           /usr/local/cuda/bin/../targets/aarch64-linux/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
>                             138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
>                                 |  ^~~~~
>                           CMakeFiles/cmTC_833f9.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_833f9.dir/main.cu.o' failed
>                           make[1]: *** [CMakeFiles/cmTC_833f9.dir/main.cu.o] Error 1
>                           make[1]: Leaving directory '/home/tts/Desktop/Mandelieu/comptage/build/CMakeFiles/CMakeTmp'
>                           Makefile:126: recipe for target 'cmTC_833f9/fast' failed
>                           make: *** [cmTC_833f9/fast] Error 2
>                           
>                       
>                         
>                       
>                         CMake will not be able to correctly generate this project.
>                       Call Stack (most recent call first):
>                         CMakeLists.txt:6 (project)
>                       
>                       
>                       -- Configuring incomplete, errors occurred!
>                       See also "/home/tts/Desktop/Mandelieu/comptage/build/CMakeFiles/CMakeOutput.log".
>                       See also "/home/tts/Desktop/Mandelieu/comptage/build/CMakeFiles/CMakeError.log".
> ```
> 
> I would ask you how should I do to change the CMakesListes.txt in order to use gcc10 and c++20.
> 
> Thank you

Maybe you can upgrade your cmake?
