### ISSUE TITLE
 “unistd.h”: No such file or directory

### ISSUE THREAD

**Issue by Chlhacker** [triple-Mu/YOLOv8-TensorRT#168]
have u guys meet this problem?just after cmake, trying to build exe

**Comment by Chlhacker** [comment]
i had already fix it,u just need to modify the unistd.h and loack io.h

**Comment by Chlhacker** [comment]
i also wonder how can i trans it to dll,so that i can use in csharp

**Comment by triple-Mu** [comment]
It seems that you are using windows.
I have not test on windows.

**Comment by JuZi233** [comment]
> It seems that you are using windows. I have not test on windows.

u can try it on windows,  it's terrible

**Comment by pcycccccc** [comment]
> > It seems that you are using windows. I have not test on windows.
> 
> u can try it on windows, it's terrible

Won't it work on Windows?

**Comment by Dwinovo** [comment]
if you are running on Windows you just need to change "unish.d" to "io.h",then change the follow functions to what i write:
1:
inline bool IsPathExist(const std::string& path)
{
#ifndef F_OK
#define F_OK 0
#endif
    return _access(path.c_str(), F_OK) != -1;
}
2:
inline bool IsFile(const std::string& path)
{
    struct _stat buffer;
    if (_stat(path.c_str(), &buffer) != 0) {
        return false; 
    }
    return (buffer.st_mode & _S_IFREG) != 0; 
}
3:
inline bool IsFolder(const std::string& path)
{
    struct _stat buffer;
    if (_stat(path.c_str(), &buffer) != 0) {
        return false;
    }
    return (buffer.st_mode & _S_IFDIR) != 0;
}
then it will work out the problem!

**Comment by pcycccccc** [comment]
@Dwinovo Thank you. Your answer solved my problem.

**Comment by Dwinovo** [comment]
> @Dwinovo Thank you. Your answer solved my problem.

you are welcome^^

**Comment by triple-Mu** [comment]
Now this https://github.com/triple-Mu/YOLOv8-TensorRT/pull/221 will fix path operator by filesystem.
Welcome to try it and give valuable feedback!
