### ISSUE TITLE
Problem with instance segmentation output

### ISSUE THREAD

**Issue by advait2000** [triple-Mu/YOLOv8-TensorRT#173]
When I use the infer-seg.py or the c++ inference for the segmentation using engine file for inference all the detections are classified as the first class in the list(in this case for yolov8s-seg.enigne the person class).

![Screenshot from 2023-11-13 16-10-41](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/46642008/4f4923bf-fe4a-47c3-ab33-77e53888ee23)

**Comment by yuyang3478** [comment]
I also encountered the same problem...... export-seg not work.

**Comment by triple-Mu** [comment]
> I also encountered the same problem...... export-seg not work.

Could you upload your onnx model?
