### ISSUE TITLE
detect ：SIGSEGV (Segmentation fault)

### ISSUE THREAD

**Issue by cxy86121** [triple-Mu/YOLOv8-TensorRT#174]
Report an error when I run the csrc/detect/end2end，my environment is cuda12.1, trt8.6.1.6; 
down load model file from  [https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt](url);  
and transform .pt -> .onnx -> .engine 
```     from ultralytics import YOLO
      model = YOLO("yolov8s.pt")  
      success = model.export(format="onnx", opset=11, simplify=True)  # export the model to onnx format
      assert success
     /home/trt/TensorRT-8.6.1.6/bin/trtexec --onnx=yolov8s.onnx --saveEngine=yolov8s.engine --fp16
```
build project and run:  ./yolov8  yolov8s.engine /data/bus.jpg,however ,SIGSEGV (Segmentation fault).,Debugging information is as follows：
![3](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/44627542/b463b9d1-bb27-4732-a77d-1980bce3087a)

when I run the csrc/detect/normal it works properly.

**Comment by triple-Mu** [comment]
Do not use `yolo export`.
Please use `export-det.py` to export model to onnx.

**Comment by cxy86121** [comment]
> Do not use `yolo export`. Please use `export-det.py` to export model to onnx.

It works fine, thanks！

**Comment by triple-Mu** [comment]
> > Do not use `yolo export`. Please use `export-det.py` to export model to onnx.
> 
> It works fine, thanks！

Great! So closed.

**Comment by OPlincn** [comment]
If i use `yolo export`, the onnx file could be export successfully, but when i use `export-det.py` , occur error:
<img width="522" alt="image" src="https://github.com/user-attachments/assets/466df0fd-7737-4837-8e94-9d7ece110cca">

**Comment by OPlincn** [comment]
> > If i use `yolo export`, the onnx file could be export successfully, but when i use `export-det.py` , occur error: <img alt="image" width="522" src="https://private-user-images.githubusercontent.com/49088507/349071144-466df0fd-7737-4837-8e94-9d7ece110cca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzE3NjksIm5iZiI6MTcyMTEzMTQ2OSwicGF0aCI6Ii80OTA4ODUwNy8zNDkwNzExNDQtNDY2ZGYwZmQtNzczNy00ODM3LThlOTQtOWQ3ZWNlMTEwY2NhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDEyMDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4N2I3ZjNiODdmYmM1MzAwZjEzMDVjMGYzZjUyNjI3Y2UxM2E2OGJiNjVkMGUxNGUyYjUzYzRmZjIyMjgwZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UtL-K8YjAy6eaiZotUyg7Hm8kBc5v4J1DVUH7QesQJk">
> 
> what's your CUDA and Tensorrt version, pls check the environment, whether the version is compatible.

My PC environment is
Tensorrt 8.6.1
CUDA 11.5
Pytorch 1.13

Jetson environment
JetPack4.5
CUDA 10.2.89
TensorRT 7.1.3
OpenCV 4.1.1

May be my jetson nx's TensorRT version too old?

**Comment by triple-Mu** [comment]
> > > If i use `yolo export`, the onnx file could be export successfully, but when i use `export-det.py` , occur error: <img alt="image" width="522" src="https://private-user-images.githubusercontent.com/49088507/349071144-466df0fd-7737-4837-8e94-9d7ece110cca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzE3NjksIm5iZiI6MTcyMTEzMTQ2OSwicGF0aCI6Ii80OTA4ODUwNy8zNDkwNzExNDQtNDY2ZGYwZmQtNzczNy00ODM3LThlOTQtOWQ3ZWNlMTEwY2NhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDEyMDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4N2I3ZjNiODdmYmM1MzAwZjEzMDVjMGYzZjUyNjI3Y2UxM2E2OGJiNjVkMGUxNGUyYjUzYzRmZjIyMjgwZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UtL-K8YjAy6eaiZotUyg7Hm8kBc5v4J1DVUH7QesQJk">
> > 
> > 
> > what's your CUDA and Tensorrt version, pls check the environment, whether the version is compatible.
> 
> My PC environment is Tensorrt 8.6.1 CUDA 11.5 Pytorch 1.13
> 
> Jetson environment JetPack4.5 CUDA 10.2.89 TensorRT 7.1.3 OpenCV 4.1.1
> 
> May be my jetson nx's TensorRT version too old?

suggest cuda11.4+ and tensorrt8.4+

**Comment by OPlincn** [comment]
> > > > If i use `yolo export`, the onnx file could be export successfully, but when i use `export-det.py` , occur error: <img alt="image" width="522" src="https://private-user-images.githubusercontent.com/49088507/349071144-466df0fd-7737-4837-8e94-9d7ece110cca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzE3NjksIm5iZiI6MTcyMTEzMTQ2OSwicGF0aCI6Ii80OTA4ODUwNy8zNDkwNzExNDQtNDY2ZGYwZmQtNzczNy00ODM3LThlOTQtOWQ3ZWNlMTEwY2NhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDEyMDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4N2I3ZjNiODdmYmM1MzAwZjEzMDVjMGYzZjUyNjI3Y2UxM2E2OGJiNjVkMGUxNGUyYjUzYzRmZjIyMjgwZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UtL-K8YjAy6eaiZotUyg7Hm8kBc5v4J1DVUH7QesQJk">
> > > 
> > > 
> > > what's your CUDA and Tensorrt version, pls check the environment, whether the version is compatible.
> > 
> > 
> > My PC environment is Tensorrt 8.6.1 CUDA 11.5 Pytorch 1.13
> > Jetson environment JetPack4.5 CUDA 10.2.89 TensorRT 7.1.3 OpenCV 4.1.1
> > May be my jetson nx's TensorRT version too old?
> 
> suggest cuda11.4+ and tensorrt8.4+

I upgrade the Jetpack from 4.5 to 4.6, and It work now!
