### ISSUE TITLE
报错NMS。用yolov8 nms的pycuda模式时候，pycuda输出的是array，不是tensor；但是调用的后处理nms是torchvision的，需要tensor。

### ISSUE THREAD

**Issue by mytk2012** [triple-Mu/YOLOv8-TensorRT#175]
nms() Expected a value of type 'Tensor' for argument 'dets' but instead found type 'ndarray'.

**Comment by triple-Mu** [comment]
Fix now:
https://github.com/triple-Mu/YOLOv8-TensorRT/commit/6c396351551c3617286d3b3abac2d5b6d54a8833
