### ISSUE TITLE
Error when build with nvcr.io/nvidia/l4t-tensorrt:r8.5.2.2-devel on Jetson Xavier

### ISSUE THREAD

**Issue by minhhoai1001** [triple-Mu/YOLOv8-TensorRT#178]
I run Docker and build on Jetson Xavier. 
- Jetpack: 5.0.2
- TensorRT 8.4.1.5
- Docker image: nvcr.io/nvidia/l4t-tensorrt:r8.5.2.2-devel

sudo docker run -it --rm nvcr.io/nvidia/l4t-tensorrt:r8.5.2.2-devel
apt-install libopencv-dev
git clone https://github.com/triple-Mu/YOLOv8-TensorRT
cd YOLOv8-TensorRT/csrc/jetson/segment
mkdir build
cd build
cmake ..
make
I got error 
![Screenshot 2023-11-26 160451](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/20763443/a9fdbdc1-5fa1-4dba-b643-a31a91803cb6)

How to fix it.

**Comment by triple-Mu** [comment]
Try to find tensorrt lib `libnvinfer.so` and then link it to the project

**Comment by catslashbin** [comment]
I encountered the same issue while compiling the Jetson demo in the l4t Docker. A quick search revealed that `libnvdla_compiler.so` and other shared libraries are mounted into the Docker by the Nvidia Docker runtime (See this [post](https://forums.developer.nvidia.com/t/libnvdla-compiler-so-error-on-nvidia-jetson-container/235140/2)). If the Docker is built without the Nvidia runtime, these libraries won't be mounted, leading to errors.

To build the Docker without Nvidia support (i.e., in CI), simply include `-DCMAKE_EXE_LINKER_FLAGS="-Wl,--unresolved-symbols=ignore-all" -DCMAKE_SHARED_LINKER_FLAGS="-Wl,--unresolved-symbols=ignore-all"` in the cmake execution command. This will instruct the linker to ignore missing dynamic libraries.

**Comment by minhhoai1001** [comment]
Are you try run docker run --gpus all ...?

Vào 22:16, Th 6, 24 thg 5, 2024 triple-mu ***@***.***> đã
viết:
