### ISSUE TITLE
how to understand the result of onnx?

### ISSUE THREAD

**Issue by superbayes** [triple-Mu/YOLOv8-TensorRT#18]
![image](https://user-images.githubusercontent.com/56495942/214749551-fb7625d0-59a8-4d4d-a4de-18b565562797.png)

hi
how can i understand the result of onnx?
why 100?

**Comment by triple-Mu** [comment]
The onnx outputs are as shown :

<img src="https://user-images.githubusercontent.com/92794867/176650971-a4fa3d65-10d4-4b65-b8ef-00a2ff13406c.png" height="300px" />

```num_dets``` means the number of object in every image in its batch .

```bboxes``` means topk(100) object's location about [`x0`,`y0`,`x1`,`y1`] .

```scores``` means the confidence score of every topk(100) objects .

```labels``` means the category of every topk(100) objects .
