### ISSUE TITLE
我在推理时 auto* boxes = static_cast<float*>(this->host_ptrs[1]);这行代码报错，错误如下图！

### ISSUE THREAD

**Issue by whiteCupz** [triple-Mu/YOLOv8-TensorRT#180]
![QQ截图20231128131403](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/67994960/350a9fb2-f992-4df7-8f62-2a8b02475109)

**Comment by triple-Mu** [comment]
如何导出模型，转换模型的呢？请给出onnx以及大概流程

**Comment by mwcheng1994** [comment]
下面是我用yolov8官方代码导出的onnx：
from ultralytics import YOLO
model = YOLO('yolov8n.pt')  # load an official model
model.export(format="onnx", imgsz=(640, 640), device=0)
下面是我在cmd导出engine格式的命令：
trtexec --onnx=yolov8s.onnx --saveEngine=yolov8s.engine --fp16

**Comment by mwcheng1994** [comment]
1.这是用yolov8官方代码导出的onnx：
from ultralytics import YOLO
model = YOLO('yolov8n.pt') # load an official model
model.export(format="onnx", imgsz=(640, 640), device=0)
2.这是在cmd导出engine格式的命令：
trtexec --onnx=yolov8s.onnx --saveEngine=yolov8s.engine --fp16
3.这是我修改模型和图片为硬编码的代码：
 // cuda:0
 cudaSetDevice(0);
 const std::string engine_file_path = "yolov8n.engine";
 const std::string path = "bus.jpg";
 std::vector<std::string> imagePathList;
 bool isVideo{ false };
 YOLOv8* yolov8 = new YOLOv8(engine_file_path);
 yolov8->make_pipe(true);
当我启动代码后就报错
![image](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/67994960/f6e6bf21-7df2-4926-8cde-ca1074af2ebf)

**Comment by mwcheng1994** [comment]
end2end和normal有什么区别。

**Comment by triple-Mu** [comment]
> end2end和normal有什么区别。

end2end增加了nms插件
