### ISSUE TITLE
是否可以像yolov8一样，只推理一个类别呢?

### ISSUE THREAD

**Issue by qq923004243** [triple-Mu/YOLOv8-TensorRT#185]
是否可以像yolov8一样，只推理一个类别呢?我在大佬你的代码中查看了一下没貌似没有类似 model('bus.jpg',classes=0)这样的配置代码，而是一次性把所有类别的数据识别出来了，我现在的做法是通过label来进行判断，但是如果能只限制类别的话我感觉速度还能提升更多。
device = torch.device("cpu")
model = YOLO('yolov8n-seg.pt')  # 加载官方模型
#model = YOLO('path/to/best.pt')  # 加载自定义模型
model = model.to(device)
# 用模型进行预测
results = model('bus.jpg',classes=0)  # 在一张图片上预测

**Comment by triple-Mu** [comment]
嗷嗷，可以在可视化的代码中判断一下label，类如：
if label == 0:
   do_some_thing

**Comment by qq923004243** [comment]
目前我是按你说的这么做了，只是我在想如果运算还能像yolov8选择识别类的话速度会更快。感谢你的回答。
