### ISSUE TITLE
能否减少 anchor 的数量，以在嵌入式更好的运行

### ISSUE THREAD

**Issue by chenxinfeng4** [triple-Mu/YOLOv8-TensorRT#186]
大佬。请问模型部署的时候能否减少anchor的数量。640x640的图片，anchor数量在 8400。图片尺寸越大，anchor数量越多。这可能对模型运行速度造成很大拖累。能否设定合适的系数，减少anchor的数量？我想用在嵌入式芯片里面，它的计算能力有限。

**Comment by triple-Mu** [comment]
> 大佬。请问模型部署的时候能否减少anchor的数量。640x640的图片，anchor数量在 8400。图片尺寸越大，anchor数量越多。这可能对模型运行速度造成很大拖累。能否设定合适的系数，减少anchor的数量？我想用在嵌入式芯片里面，它的计算能力有限。

目前来看，因为jetson系列cuda核数量比cpu线程还是大的多，即使全算了也不会很慢。所以用plugin速度尚可。

**Comment by chenxinfeng4** [comment]
感谢解答
