### ISSUE TITLE
Warning when export onnx model

### ISSUE THREAD

**Issue by asflower** [triple-Mu/YOLOv8-TensorRT#189]
## Env

- onnx verson
1.15
- torch version
2.1.2
- tensorrt version
8.6.1

## Your problem

![image](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/16401446/f2444ade-6552-4007-88f6-9ad81bd053b3)

An warning occurred when the model is converted to an onnx model. Is this a serious problem?

**Comment by triple-Mu** [comment]
Just warnings.
Do not matter.
