### ISSUE TITLE
dynamic batch

### ISSUE THREAD

**Issue by jielanZhang** [triple-Mu/YOLOv8-TensorRT#19]
How to convert to dynamic batch？

**Comment by triple-Mu** [comment]
https://github.com/triple-Mu/YOLOv8-TensorRT/tree/triplemu/dynamic
Here is an example. It is not stable now.

**Comment by jielanZhang** [comment]
> https://github.com/triple-Mu/YOLOv8-TensorRT/tree/triplemu/dynamic Here is an example. It is not stable now.

ok
thanks......
