### ISSUE TITLE
No module named 'onnx'

### ISSUE THREAD

**Issue by ugkjkj** [triple-Mu/YOLOv8-TensorRT#191]
C:\Users\15258>python3 "C:\Users\15258\Downloads\YOLOv8-TensorRT-main\YOLOv8-TensorRT-main\infer-det.py" --engine "C:\Users\15258\Desktop\model++\runs\detect\train26\weights\best.engine" --imgs "C:\Users\15258\Desktop\model++\000002 copy.jpg" --out-dir outputs --device cuda:0
Traceback (most recent call last):
  File "C:\Users\15258\Downloads\YOLOv8-TensorRT-main\YOLOv8-TensorRT-main\infer-det.py", line 1, in <module>
    from models import TRTModule  # isort:skip
  File "C:\Users\15258\Downloads\YOLOv8-TensorRT-main\YOLOv8-TensorRT-main\models\__init__.py", line 1, in <module>
    from .engine import EngineBuilder, TRTModule, TRTProfilerV0, TRTProfilerV1  # isort:skip # noqa: E501
  File "C:\Users\15258\Downloads\YOLOv8-TensorRT-main\YOLOv8-TensorRT-main\models\engine.py", line 7, in <module>
    import onnx
ModuleNotFoundError: No module named 'onnx'

**Comment by triple-Mu** [comment]
> C:\Users\15258>python3 "C:\Users\15258\Downloads\YOLOv8-TensorRT-main\YOLOv8-TensorRT-main\infer-det.py" --engine "C:\Users\15258\Desktop\model++\runs\detect\train26\weights\best.engine" --imgs "C:\Users\15258\Desktop\model++\000002 copy.jpg" --out-dir outputs --device cuda:0 Traceback (most recent call last): File "C:\Users\15258\Downloads\YOLOv8-TensorRT-main\YOLOv8-TensorRT-main\infer-det.py", line 1, in from models import TRTModule # isort:skip File "C:\Users\15258\Downloads\YOLOv8-TensorRT-main\YOLOv8-TensorRT-main\models__init__.py", line 1, in from .engine import EngineBuilder, TRTModule, TRTProfilerV0, TRTProfilerV1 # isort:skip # noqa: E501 File "C:\Users\15258\Downloads\YOLOv8-TensorRT-main\YOLOv8-TensorRT-main\models\engine.py", line 7, in import onnx ModuleNotFoundError: No module named 'onnx'

pip install onnx

**Comment by ugkjkj** [comment]
(model) C:\Users\15258>pip install onnx
Requirement already satisfied: onnx in d:\anaconda\envs\model\lib\site-packages (1.15.0)
Requirement already satisfied: numpy in d:\anaconda\envs\model\lib\site-packages (from onnx) (1.26.2)
Requirement already satisfied: protobuf>=3.20.2 in d:\anaconda\envs\model\lib\site-packages (from onnx) (4.25.1)

**Comment by triple-Mu** [comment]
python -m pip install onnx

**Comment by ugkjkj** [comment]
(model) C:\Users\15258>python -m pip install onnx
Requirement already satisfied: onnx in d:\anaconda\envs\model\lib\site-packages (1.15.0)
Requirement already satisfied: numpy in d:\anaconda\envs\model\lib\site-packages (from onnx) (1.26.2)
Requirement already satisfied: protobuf>=3.20.2 in d:\anaconda\envs\model\lib\site-packages (from onnx) (4.25.1)

**Comment by ugkjkj** [comment]
Traceback (most recent call last):
  File "C:\Users\15258\Downloads\YOLOv8-TensorRT-main\YOLOv8-TensorRT-main\infer-det.py", line 1, in <module>
    from models import TRTModule  # isort:skip
  File "C:\Users\15258\Downloads\YOLOv8-TensorRT-main\YOLOv8-TensorRT-main\models\__init__.py", line 1, in <module>
    from .engine import EngineBuilder, TRTModule, TRTProfilerV0, TRTProfilerV1  # isort:skip # noqa: E501
  File "C:\Users\15258\Downloads\YOLOv8-TensorRT-main\YOLOv8-TensorRT-main\models\engine.py", line 7, in <module>
    import onnx
ModuleNotFoundError: No module named 'onnx'

**Comment by triple-Mu** [comment]
how about uninstall onnx and install then.
