### ISSUE TITLE
Yolov8 Classification

### ISSUE THREAD

**Issue by advait2000** [triple-Mu/YOLOv8-TensorRT#196]
Is there any way to convert yolov8 classification models to engine format and infer

**Comment by triple-Mu** [comment]
Yolov8 classification's postprocess is just a argmax op.
Maybe it is easy for you.

**Comment by monkeycc** [comment]
yolov8-cls +1

**Comment by triple-Mu** [comment]
support now
https://github.com/triple-Mu/YOLOv8-TensorRT/commit/a9236fc1599fabe5aa09a1aa2b31a7f6b819f92c
