### ISSUE TITLE
pic score not correct

### ISSUE THREAD

**Issue by dadada-123** [triple-Mu/YOLOv8-TensorRT#20]
![微信图片_20230130223518](https://user-images.githubusercontent.com/93700580/215506672-fd57da2f-aa23-41a0-9077-00516dda7cd0.png)
hello,the score doesn't look right, how can I modify it

**Comment by triple-Mu** [comment]
This is usually caused by you using fp16 under TensorRT < 8.2.4. This is its inherent bug.
You can update TensorRT>=8.2.4 or use fp32 instead

**Comment by dadada-123** [comment]
My TensorRT is 8.2.5.1,and how to use fp32 instead.
python  build.py --fp32 is wrong

**Comment by triple-Mu** [comment]
> My TensorRT is 8.2.5.1,and how to use fp32 instead. python build.py --fp32 is wrong
``` shell
python build.py --weights yolov8s.onnx
```
If you don't use `--fp16`, it will default use fp32

**Comment by dadada-123** [comment]
Thank you. The problem is solved

**Comment by triple-Mu** [comment]
> Thank you. The problem is solved

Thanks for your feedback !

**Comment by TwinkleYR** [comment]
My TensorRT is 8.2.5.1, and when I use fp16, the conf is negative， why？

**Comment by triple-Mu** [comment]
> My TensorRT is 8.2.5.1, and when I use fp16, the conf is negative， why？

This is caused by tensorrt internal error. 
If you want to avoid this situation, please use tensorrt>=8.4 or turn off fp16
