### ISSUE TITLE
Running RTDETR Model

### ISSUE THREAD

**Issue by shreejalt** [triple-Mu/YOLOv8-TensorRT#206]
Hi.
Thanks for your repo. I wanted to ask that I wanted to convert RTDETR with end2end NMS plugin. Can I use your repo to use the onnx model from the RTDETR repo of the ultralytics?

Your prompt help would be really appreciated

Thanks,
Shreejal

**Comment by triple-Mu** [comment]
> Hi. Thanks for your repo. I wanted to ask that I wanted to convert RTDETR with end2end NMS plugin. Can I use your repo to use the onnx model from the RTDETR repo of the ultralytics?
> 
> Your prompt help would be really appreciated
> 
> Thanks, Shreejal

Maybe not.
Because there are different postprocess in these two models
