### ISSUE TITLE
Negative confidence score

### ISSUE THREAD

**Issue by wsy-yjys** [triple-Mu/YOLOv8-TensorRT#21]
![6ce964d7ca18e9aa591196f291436e1](https://user-images.githubusercontent.com/78601159/215703572-7e7bb8af-2907-4e6d-8817-7c9d950ac8c8.png)
I used tensorrt 8.2.1 to derive the engine model on jetson nano, and got a negative confidence score after reasoning, why is this? Ask for help

**Comment by triple-Mu** [comment]
Here is a same issue 
https://github.com/triple-Mu/YOLOv8-TensorRT/issues/20.
Suggest you update tensorrt>8.2.4 or do not use fp16

**Comment by wsy-yjys** [comment]
Thank you very much. The problem is solved !

**Comment by wsy-yjys** [comment]
hello, but when I use fp32，the fps almost unchanged？Is there another way to speed up?

**Comment by triple-Mu** [comment]
> hello, but when I use fp32，the fps almost unchanged？Is there another way to speed up?

You can try the c++ inference code in `csrc/detect/end2end`

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
