### ISSUE TITLE
TensorRT10 Error

### ISSUE THREAD

**Issue by TTTiankun** [triple-Mu/YOLOv8-TensorRT#218]
I install TensorRT10 which was released 3 weeks ago, but I find some errors when I make the C++ programme. Maybe the API update in this nbew version. Need Help!
![error](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/138654631/2a1eb065-870f-4def-a51f-eb1e6135bc99)

**Comment by triple-Mu** [comment]
Now I have try to support tensort10 in this [pr](https://github.com/triple-Mu/YOLOv8-TensorRT/pull/221)

**Comment by TTTiankun** [comment]
Thank you so much and I will try it later
