### ISSUE TITLE
win平台编译成功后，执行exe报错：未找到插件

### ISSUE THREAD

**Issue by Gavin-Zhp** [triple-Mu/YOLOv8-TensorRT#224]
![error](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/17159354/c5076665-7fcf-4acb-bdd2-7b545c025813)

CUDA：11.8
TensorRT：TensorRT-8.6.1.6
OpenCV：4.8

**Comment by triple-Mu** [comment]
> ![error](https://github.com/triple-Mu/YOLOv8-TensorRT/assets/17159354/c5076665-7fcf-4acb-bdd2-7b545c025813)
> 
> 
> 
> 
> 
> CUDA：11.8
> 
> TensorRT：TensorRT-8.6.1.6
> 
> OpenCV：4.8

看上去是您使用tensorrtx导出的engine用本项目推理了。
你需要使用export_det.py来导出onnx模型，然后用trtexec转换后得到的engine才可以推理

**Comment by Gavin-Zhp** [comment]
@triple-Mu 可以正常工作了，感谢你的解答

**Comment by triple-Mu** [comment]
好的，issue就关闭了😁
