### ISSUE TITLE
使用 export-det.py 文件将pt转onnx失败

### ISSUE THREAD

**Issue by stephen-TT** [triple-Mu/YOLOv8-TensorRT#235]
使用命令
```
python export-det.py --weights .\yolov8s.pt --iou-thres 0.65 --conf-thres 0.25 --topk 100 --opset 11 --sim --input-shape 1 3 640 640 --device cuda:0 
```
打印的日志
![image](https://github.com/user-attachments/assets/503673f7-fadb-4aae-96f1-37a6d5fa9a57)

## 没有报错，也没有生成onnx，我使用的pt是官方的pt文件

通过打印日志定位到 export函数，如下图：
![image](https://github.com/user-attachments/assets/f331bfe9-9ac7-4a0e-9c48-bba846aeda9a)

**Comment by triple-Mu** [comment]
看上去模型没有被优化裁剪。能否提供.pt给我测试呢

**Comment by stephen-TT** [comment]
您好大佬，我换了conda虚拟环境中pytorch的包后您的代码可以正常运行，也可以正常运行自训练的v8模型，应该是一开始我的虚拟环境包的问题，谢谢大佬，我关了这个issue了。

**Comment by zju-z** [comment]
这个问题怎么解决的啊，具体pytorch哪里有问题，
