### ISSUE TITLE
What's the diff  between end2end and normal framework?

### ISSUE THREAD

**Issue by FunnyWii** [triple-Mu/YOLOv8-TensorRT#238]
Hello author!

I saw a similar issue #234 , do you mean the only differnce between that two framework is that I can modify the score_thres and iou_thres ?

**Comment by triple-Mu** [comment]
> Hello author!
> 
> I saw a similar issue #234 , do you mean the only differnce between that two framework is that I can modify the score_thres and iou_thres ?

The advantage of end2end is that it is fast and requires less code.

**Comment by FunnyWii** [comment]
> > Hello author!
> > I saw a similar issue #234 , do you mean the only differnce between that two framework is that I can modify the score_thres and iou_thres ?
> 
> The advantage of end2end is that it is fast and requires less code.

That is, the engine model will only output the results whose scores larger than the threshold ?  (0.25 as the `export-det.py`  `--conf-thres` default set). Other results whose scores smaller than the thres will not output. 

But if I want to use the NORMAL version codes, which can modify the threshold in the `main.cpp`, how should I export the onnx ->  engine format and keep the output as ` output_names=['num_dets', 'bboxes', 'scores', 'labels'])` ?
