### ISSUE TITLE
Is there a version requirement for the C++ interface?

### ISSUE THREAD

**Issue by ljl02521** [triple-Mu/YOLOv8-TensorRT#244]
I encountered this error when compiling according to the requirements.
end2end/main.cpp:74:57: error: invalid initialization of reference of type ‘std::vector<cv::String>&’ from expression of type ‘std::vector<std::__cxx11::basic_string<char> >’
YOLOv8-TensorRT/csrc/detect/end2end/main.cpp:84:34: error: no matching function for call to ‘cv::VideoCapture::VideoCapture(const ghc::filesystem::path&)’

**Comment by triple-Mu** [comment]
> I encountered this error when compiling according to the requirements. end2end/main.cpp:74:57: error: invalid initialization of reference of type ‘std::vectorcv::String&’ from expression of type ‘std::vector<std::__cxx11::basic_string >’ YOLOv8-TensorRT/csrc/detect/end2end/main.cpp:84:34: error: no matching function for call to ‘cv::VideoCapture::VideoCapture(const ghc::filesystem::path&)’

Do you have any g++ env?

**Comment by ljl02521** [comment]
> > I encountered this error when compiling according to the requirements. end2end/main.cpp:74:57: error: invalid initialization of reference of type ‘std::vectorcv::String&’ from expression of type ‘std::vector<std::__cxx11::basic_string >’ YOLOv8-TensorRT/csrc/detect/end2end/main.cpp:84:34: error: no matching function for call to ‘cv::VideoCapture::VideoCapture(const ghc::filesystem::path&)’
> 
> Do you have any g++ env?

g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
