### ISSUE TITLE
engine->getNbIOTensors() segmentation fault

### ISSUE THREAD

**Issue by RizqypratamaS** [triple-Mu/YOLOv8-TensorRT#254]
code get Segmentation Fault (core dump) in engine->getNbIOTensors(), any suggestion?
TensoRT =10.4
CUDA =12.5

**Comment by RizqypratamaS** [comment]
tested in csrc/detect/end2end and normal

**Comment by RizqypratamaS** [comment]
i re-install cuda and tensorrt, and it works

**Comment by triple-Mu** [comment]
> i re-install cuda and tensorrt, and it works

Great!
Thanks for sharing the solutions.

**Comment by RizqypratamaS** [comment]
> > i re-install cuda and tensorrt, and it works
> 
> Great! Thanks for sharing the solutions.

out of topic, do i need change something in the code if im using FP16 ?
