### ISSUE TITLE
我试着把yolov8-detect中的end2end移植到ROS中，但是运行报错

### ISSUE THREAD

**Issue by cll-git** [triple-Mu/YOLOv8-TensorRT#262]
我在posetprocess成员函数中添加如下代码：
        if (boxes == nullptr) {
            ROS_ERROR("Null pointer detected for boxes in postprocess");
        }
        if (scores == nullptr) {
            ROS_ERROR("Null pointer detected for scores in postprocess");
        }
        if (labels == nullptr) {
            ROS_ERROR("Null pointer detected for labels in postprocess");
        }
        if (boxes == nullptr || scores == nullptr || labels == nullptr) {
            ROS_ERROR("Null pointer detected in postprocess");
            return;
        }

于是报错：
[ERROR] [1730187380.381814027]: Null pointer detected for boxes in postprocess
[ERROR] [1730187380.381852953]: Null pointer detected for scores in postprocess
[ERROR] [1730187380.381863882]: Null pointer detected in postprocess

看起来像是检测不到东西，然后报错退出了？

此时是连接了深度相机的。。

**Comment by cll-git** [comment]
按照readme使用export-det.py导出end2end的onnx，再转换成engine就解决了。
外行人真的搞不懂这些，种类好多哈哈哈

**Comment by triple-Mu** [comment]
> 按照readme使用export-det.py导出end2end的onnx，再转换成engine就解决了。
> 
> 外行人真的搞不懂这些，种类好多哈哈哈

感谢您的反馈！
