### ISSUE TITLE
cudaStreamSynchronize（）函数耗时问题

### ISSUE THREAD

**Issue by Akiy071** [triple-Mu/YOLOv8-TensorRT#267]
Hello,我希望这不是一个bug或者是出自我自己疏忽大意的原因导致的情况，当我使用detect模型进行推理的时候，发现随着图片的迭代推理，推理耗时也在一直增加，最终定位到了cudaStreamSynchronize（）这个cuda函数上，由于我没有cuda编程的经验，目前通过查看了这个Stream流同步函数的作用，推测可能是为了等待所有流的工作完成导致的延时？希望得到您的答复。

- TensorRT version:10.6
- Visual studio 2022
- cuda: v12.1
下图为我定位耗时的输出语句

![B0(CT~70V)JQ1_MWMP6}QQS](https://github.com/user-attachments/assets/c213bbc0-b438-4f55-ab57-3f08e60520bb)
以及定位位置代码情况
![image](https://github.com/user-attachments/assets/74b05bf9-e470-48b9-a209-94eec25df554)

**Comment by triple-Mu** [comment]
因为使用了异步的cudamemcpy，所以需要一个流同步的操作保证数据有效性。
是否同时记录过其他地方的耗时？比如前处理和后处理？

**Comment by Akiy071** [comment]
> 因为使用了异步的cudamemcpy，所以需要一个流同步的操作保证数据有效性。 是否同时记录过其他地方的耗时？比如前处理和后处理？

感谢您的回复，我对copy_from_Mat()函数以及postprocess函数分别进行了检查确认，前者从1.5ms递增到了2.4ms左右，有一定耗时的累加，后者耗时可以忽略不记，因此我对cudaMemcpyAsync（）函数再额外进行了测试，发现其从0.3ms增加到了1.4ms。虽然有所增加，但是对于cudaStreamSynchronize（）函数从0.004ms递增到后面11ms的情况，我无法确定是什么原因。
![image](https://github.com/user-attachments/assets/a68740c4-8260-49de-b39a-950fdb529354)

**Comment by Akiy071** [comment]
> 因为使用了异步的cudamemcpy，所以需要一个流同步的操作保证数据有效性。 是否同时记录过其他地方的耗时？比如前处理和后处理？

**Comment by Akiy071** [comment]
> 因为使用了异步的cudamemcpy，所以需要一个流同步的操作保证数据有效性。 是否同时记录过其他地方的耗时？比如前处理和后处理？
感谢您的回复，由于这是我的第二次issue提问和回复，错点了close操作。
经过您的提醒，我再次分别对copy_from_Mat()函数以及postprocess函数进行了测试，前者从1.5ms耗时递增到了2.6ms左右时间，后者用时很小可以忽略不记。于是我进行了进一步测试，发现copy_from_Mat()函数的耗时递增来自于cudaMemcpyAsync（）函数
![image](https://github.com/user-attachments/assets/823d4484-4fb9-49f5-8bb3-579d20789305)

但对于cudaStreamSynchronize（）从0.004ms递增到24ms并稳定的情况我还是无法确定是什么问题。

**Comment by triple-Mu** [comment]
> > 因为使用了异步的cudamemcpy，所以需要一个流同步的操作保证数据有效性。 是否同时记录过其他地方的耗时？比如前处理和后处理？
> > 感谢您的回复，由于这是我的第二次issue提问和回复，错点了close操作。
> > 经过您的提醒，我再次分别对copy_from_Mat()函数以及postprocess函数进行了测试，前者从1.5ms耗时递增到了2.6ms左右时间，后者用时很小可以忽略不记。于是我进行了进一步测试，发现copy_from_Mat()函数的耗时递增来自于cudaMemcpyAsync（）函数
> > ![image](https://private-user-images.githubusercontent.com/116703314/385580950-823d4484-4fb9-49f5-8bb3-579d20789305.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTU5ODgsIm5iZiI6MTczMTU1NTY4OCwicGF0aCI6Ii8xMTY3MDMzMTQvMzg1NTgwOTUwLTgyM2Q0NDg0LTRmYjktNDlmNS04YmIzLTU3OWQyMDc4OTMwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQwMzQxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGMxOTRjZDcyY2YyYWY3MzdiMjkxMWQ2NDVjMGJlOTJlZjZlMzhhNzM2YWE0YTk1NTlmYmY4NmU3NmMzYTlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VLvq2xM-tmSSDX0r9rr4KkjtmXBUkOG0NdpHvzh6-i8)
> 
> 但对于cudaStreamSynchronize（）从0.004ms递增到24ms并稳定的情况我还是无法确定是什么问题。

看上去是可以优化的，可以用Pinned Memory来替代opencv管理的内存。这样可以减少一次host端的拷贝。

**Comment by Akiy071** [comment]
> > > 因为使用了异步的cudamemcpy，所以需要一个流同步的操作保证数据有效性。 是否同时记录过其他地方的耗时？比如前处理和后处理？
> > > 感谢您的回复，由于这是我的第二次issue提问和回复，错点了close操作。
> > > 经过您的提醒，我再次分别对copy_from_Mat()函数以及postprocess函数进行了测试，前者从1.5ms耗时递增到了2.6ms左右时间，后者用时很小可以忽略不记。于是我进行了进一步测试，发现copy_from_Mat()函数的耗时递增来自于cudaMemcpyAsync（）函数
> > > ![image](https://private-user-images.githubusercontent.com/116703314/385580950-823d4484-4fb9-49f5-8bb3-579d20789305.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTU5ODgsIm5iZiI6MTczMTU1NTY4OCwicGF0aCI6Ii8xMTY3MDMzMTQvMzg1NTgwOTUwLTgyM2Q0NDg0LTRmYjktNDlmNS04YmIzLTU3OWQyMDc4OTMwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQwMzQxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGMxOTRjZDcyY2YyYWY3MzdiMjkxMWQ2NDVjMGJlOTJlZjZlMzhhNzM2YWE0YTk1NTlmYmY4NmU3NmMzYTlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VLvq2xM-tmSSDX0r9rr4KkjtmXBUkOG0NdpHvzh6-i8)
> > 
> > 
> > 但对于cudaStreamSynchronize（）从0.004ms递增到24ms并稳定的情况我还是无法确定是什么问题。
> 
> 看上去是可以优化的，可以用Pinned Memory来替代opencv管理的内存。这样可以减少一次host端的拷贝。

谢谢您的建议，后续我再试试能不能解决这个问题，然后反馈到issue中。
