### ISSUE TITLE
run yolov8n on a Jetson Nano?

### ISSUE THREAD

**Issue by merhovon** [triple-Mu/YOLOv8-TensorRT#29]
Hello all,

I have the problem that the processing of my yolov8n on the Jetson nano 2GB is very slow.
I read that the FPS can be increased if you use TensorRT, but how do not quite understand what steps to perform.

My code is currently:

```
from ultralytics import YOLO
from ultralytics.yolo.v8.detect.predict import DetectionPredictor

model = YOLO("yolov8n.pt")
results = model.predict(source=frame, show=True, conf=0.55)
```

Aus der yolov8n.pt habe ich schon eine .onnx-Datei erzeugt mit diesem Befehl:

`YOLO("yolov8n.pt").export(format="onnx")`

Now I have a yolov8n.pt and a yolov8n.onnx, what steps do I still need to do and how would my python program need to be modified?

**Comment by triple-Mu** [comment]
> Hello all,
> 
> I have the problem that the processing of my yolov8n on the Jetson nano 2GB is very slow. I read that the FPS can be increased if you use TensorRT, but how do not quite understand what steps to perform.
> 
> My code is currently:
> 
> ```
> from ultralytics import YOLO
> from ultralytics.yolo.v8.detect.predict import DetectionPredictor
> 
> model = YOLO("yolov8n.pt")
> results = model.predict(source=frame, show=True, conf=0.55)
> ```
> 
> Aus der yolov8n.pt habe ich schon eine .onnx-Datei erzeugt mit diesem Befehl:
> 
> `YOLO("yolov8n.pt").export(format="onnx")`
> 
> Now I have a yolov8n.pt and a yolov8n.onnx, what steps do I still need to do and how would my python program need to be modified?

You must generate `yolov8n.onnx` by this repo, and you can also use personal pc to generate it, and move to jetson to save time.
Besides, in order to generate `yolov8n.engine`, you must run `build.py` in jetson nano.
If you have some touble, I hope you can provide detailed logs.
Thanks

**Comment by merhovon** [comment]
python3 export-det.py --weights yolov8n.pt --sim

Nach dem Befehl erhalte ich folgende Fehlermeldung:

![image](https://user-images.githubusercontent.com/26201870/217813635-4c98d490-6f54-4fd3-9918-649682d8f375.png)

**Comment by triple-Mu** [comment]
```shell
pip install onnx onnxsim
```

**Comment by triple-Mu** [comment]
> python3 export-det.py --weights yolov8n.pt --sim
> 
> Nach dem Befehl erhalte ich folgende Fehlermeldung:
> 
> ![image](https://user-images.githubusercontent.com/26201870/217813635-4c98d490-6f54-4fd3-9918-649682d8f375.png)

``` shell
pip install onnx onnxsim
```

**Comment by merhovon** [comment]
Now I get the following error message:

![image](https://user-images.githubusercontent.com/26201870/217822909-f73a1c28-a88c-4980-9a64-74e6ba0aed71.png)

But tensorrt is installed.

![image](https://user-images.githubusercontent.com/26201870/217823070-e5da0bbd-39fb-468b-b125-56b2ad40c3c2.png)

**Comment by triple-Mu** [comment]
> Now I get the following error message:
> 
> ![image](https://user-images.githubusercontent.com/26201870/217822909-f73a1c28-a88c-4980-9a64-74e6ba0aed71.png)
> 
> But tensorrt is installed.
> 
> ![image](https://user-images.githubusercontent.com/26201870/217823070-e5da0bbd-39fb-468b-b125-56b2ad40c3c2.png)
> 
> The problem is that tensorrt does not exist for Python version 3.8 for the Jetson nano. Is there a way to be able to run YOLOv8 and YOLOv8-TensorRT under Python 3.6?

Could you please export onnx by your personal pc, and move it to you jetson?

**Comment by merhovon** [comment]
I get the same error message on my PC. Here is my py file.
[yolov8n.zip](https://github.com/triple-Mu/YOLOv8-TensorRT/files/10698377/yolov8n.zip)

**Comment by triple-Mu** [comment]
> 

Have you exported onnx success?

**Comment by merhovon** [comment]
No I get the same error message on my Windows computer:

ModuleNotFoundError: No module named 'tensorrt'

**Comment by triple-Mu** [comment]
> No I get the same error message on my Windows computer:
> 
> ModuleNotFoundError: No module named 'tensorrt'

It seems that you haven't install tensorrt.
``` shell
which python3.6
```
Please use python3.6 default in jetson

**Comment by merhovon** [comment]
Es funktioniert leider nicht, ich erhalte die Meldung, dass keine richtige version von  protobuf installiert ist, was aber nicht stimmt.

![image](https://user-images.githubusercontent.com/26201870/217921523-8a6dedbf-f216-48cc-9c3b-78ce059be005.png)

**Comment by triple-Mu** [comment]
> Unfortunately it does not work, I get a message that there is no correct version of protobuf installed, which is not true.
> 
> ![image](https://user-images.githubusercontent.com/26201870/217921523-8a6dedbf-f216-48cc-9c3b-78ce059be005.png)
> 
> ![image](https://user-images.githubusercontent.com/26201870/217922371-13faaaf9-7f93-4537-b77a-a6b846d8e050.png)

Your protobuf version is mismatch.
Please install protobuf==3.20.3.
If you have exported onnx in you pc.
You can move it to jetson and use 
``` shell
/usr/src/tensorrt/bin/trtexec --onnx yolov8n.onnx --saveEngine=yolov8n.engine --fp16
```
Then you will get an engine, and use
``` shell
python3 infer-det-without-torch.py --engine yolov8n.engine --imgs data/bus.jpg --show --method pycuda
```

**Comment by merhovon** [comment]
> 1. First, you need to clone this repo and move your weights to this repository path.
> 
> ```shell
> git clone https://github.com/triple-Mu/YOLOv8-TensorRT.git
> cd YOLOv8-TensorRT
> # make sure you have move the yolov8n.pt to this path
> python3 export-det.py --weights yolov8n.pt --sim
> ```
> 
> 2. The above operation will generate `yolov8n.onnx` in the current directory, then run:
> 
> ```shell
> python3 build.py --weights yolov8n.onnx --fp16  --device cuda:0
> ```
> 
> You will get `yolov8n.engine` in the current directory. 3. Use `yolov8n.engine` to detect images!
> 
> ```shell
> pip install pycuda
> python3 infer-det-without-torch.py --engine yolov8n.engine --imgs data/bus.jpg --show --method pycuda
> ```

I have now been able to create the yolov8n.engine, how can I incorporate this into my Python application?
Currently I use YOLOv8 as follows, what should my source code look like at this point?

```
from ultralytics import YOLO
from ultralytics.yolo.v8.detect.predict import DetectionPredictor

model = YOLO("yolov8n.pt")
results = model.predict(source=frame, show=True, conf=0.55)
```

**Comment by triple-Mu** [comment]
> 

The code of YOLOv8 is relatively complicated, so this repo simplifies it. 
Compared with its version, we have implemented the end-to-end detection of the model on the GPU, 
so our speed is faster.
I suggest you try:

``` shell
python3 export-det.py --weights yolov8n.pt --sim
python3 build.py --weights yolov8n.onnx --fp16  --device cuda:0
python3 infer-det-without-torch.py --engine yolov8n.engine --imgs data/bus.jpg --show --method pycuda
``` 
to show you detection result.

**Comment by merhovon** [comment]
I am currently using yolov8 with cv2.VideoCapture and other pip packages in my python source code. Can I also include yolov8tenosrt as a pip package and use it accordingly or can yolov8tenosrt only be included via the command line interface?

How would I be able to include yolov8tenosrt in my python source code?
Übersetzt mit DeepL https://www.deepl.com/app/?utm_source=android&utm_medium=app&utm_campaign=share-translation

**Comment by triple-Mu** [comment]
``` python
import os
import random
import warnings
from collections import namedtuple
from pathlib import Path
from typing import List, Optional, Tuple, Union

import cv2
import numpy as np
import pycuda.autoinit  # noqa F401
import pycuda.driver as cuda
import tensorrt as trt
from numpy import ndarray

os.environ['CUDA_MODULE_LOADING'] = 'LAZY'
warnings.filterwarnings(action='ignore', category=DeprecationWarning)

random.seed(0)

# detection model classes
CLASSES = ('person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus',
           'train', 'truck', 'boat', 'traffic light', 'fire hydrant',
           'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog',
           'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe',
           'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee',
           'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat',
           'baseball glove', 'skateboard', 'surfboard', 'tennis racket',
           'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl',
           'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot',
           'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
           'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop',
           'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven',
           'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase',
           'scissors', 'teddy bear', 'hair drier', 'toothbrush')

# colors for per classes
COLORS = {
    cls: [random.randint(0, 255) for _ in range(3)]
    for i, cls in enumerate(CLASSES)
}


class TRTEngine:

    def __init__(self, weight: Union[str, Path]) -> None:
        self.weight = Path(weight) if isinstance(weight, str) else weight
        self.stream = cuda.Stream(0)
        self.__init_engine()
        self.__init_bindings()
        self.__warm_up()

    def __init_engine(self) -> None:
        logger = trt.Logger(trt.Logger.WARNING)
        trt.init_libnvinfer_plugins(logger, namespace='')
        with trt.Runtime(logger) as runtime:
            model = runtime.deserialize_cuda_engine(self.weight.read_bytes())

        context = model.create_execution_context()

        names = [model.get_binding_name(i) for i in range(model.num_bindings)]
        self.num_bindings = model.num_bindings
        self.bindings: List[int] = [0] * self.num_bindings
        num_inputs, num_outputs = 0, 0

        for i in range(model.num_bindings):
            if model.binding_is_input(i):
                num_inputs += 1
            else:
                num_outputs += 1

        self.num_inputs = num_inputs
        self.num_outputs = num_outputs
        self.model = model
        self.context = context
        self.input_names = names[:num_inputs]
        self.output_names = names[num_inputs:]

    def __init_bindings(self) -> None:
        dynamic = False
        Tensor = namedtuple('Tensor', ('name', 'dtype', 'shape', 'cpu', 'gpu'))
        inp_info = []
        out_info = []
        out_ptrs = []
        for i, name in enumerate(self.input_names):
            assert self.model.get_binding_name(i) == name
            dtype = trt.nptype(self.model.get_binding_dtype(i))
            shape = tuple(self.model.get_binding_shape(i))
            if -1 in shape:
                dynamic |= True
            if not dynamic:
                cpu = np.empty(shape, dtype)
                gpu = cuda.mem_alloc(cpu.nbytes)
                cuda.memcpy_htod_async(gpu, cpu, self.stream)
            else:
                cpu, gpu = np.empty(0), 0
            inp_info.append(Tensor(name, dtype, shape, cpu, gpu))
        for i, name in enumerate(self.output_names):
            i += self.num_inputs
            assert self.model.get_binding_name(i) == name
            dtype = trt.nptype(self.model.get_binding_dtype(i))
            shape = tuple(self.model.get_binding_shape(i))
            if not dynamic:
                cpu = np.empty(shape, dtype=dtype)
                gpu = cuda.mem_alloc(cpu.nbytes)
                cuda.memcpy_htod_async(gpu, cpu, self.stream)
                out_ptrs.append(gpu)
            else:
                cpu, gpu = np.empty(0), 0
            out_info.append(Tensor(name, dtype, shape, cpu, gpu))

        self.is_dynamic = dynamic
        self.inp_info = inp_info
        self.out_info = out_info
        self.out_ptrs = out_ptrs

    def __warm_up(self) -> None:
        if self.is_dynamic:
            print('You engine has dynamic axes, please warm up by yourself !')
            return
        for _ in range(10):
            inputs = []
            for i in self.inp_info:
                inputs.append(i.cpu)
            self.__call__(inputs)

    def set_profiler(self, profiler: Optional[trt.IProfiler]) -> None:
        self.context.profiler = profiler \
            if profiler is not None else trt.Profiler()

    def __call__(self, *inputs) -> Union[Tuple, ndarray]:

        assert len(inputs) == self.num_inputs
        contiguous_inputs: List[ndarray] = [
            np.ascontiguousarray(i) for i in inputs
        ]

        for i in range(self.num_inputs):

            if self.is_dynamic:
                self.context.set_binding_shape(
                    i, tuple(contiguous_inputs[i].shape))
                self.inp_info[i].gpu = cuda.mem_alloc(
                    contiguous_inputs[i].nbytes)

            cuda.memcpy_htod_async(self.inp_info[i].gpu, contiguous_inputs[i],
                                   self.stream)
            self.bindings[i] = int(self.inp_info[i].gpu)

        output_gpu_ptrs: List[int] = []
        outputs: List[ndarray] = []

        for i in range(self.num_outputs):
            j = i + self.num_inputs
            if self.is_dynamic:
                shape = tuple(self.context.get_binding_shape(j))
                dtype = self.out_info[i].dtype
                cpu = np.empty(shape, dtype=dtype)
                gpu = cuda.mem_alloc(contiguous_inputs[i].nbytes)
                cuda.memcpy_htod_async(gpu, cpu, self.stream)
            else:
                cpu = self.out_info[i].cpu
                gpu = self.out_info[i].gpu
            outputs.append(cpu)
            output_gpu_ptrs.append(gpu)
            self.bindings[j] = int(gpu)

        self.context.execute_async_v2(self.bindings, self.stream.handle)
        self.stream.synchronize()

        for i, o in enumerate(output_gpu_ptrs):
            cuda.memcpy_dtoh_async(outputs[i], o, self.stream)

        return tuple(outputs) if len(outputs) > 1 else outputs[0]


def det_postprocess(data: Tuple[ndarray, ndarray, ndarray, ndarray]):
    assert len(data) == 4
    num_dets, bboxes, scores, labels = (i[0] for i in data)
    nums = num_dets.item()
    bboxes = bboxes[:nums]
    scores = scores[:nums]
    labels = labels[:nums]
    return bboxes, scores, labels


def letterbox(im: ndarray,
              new_shape: Union[Tuple, List] = (640, 640),
              color: Union[Tuple, List] = (114, 114, 114)) \
        -> Tuple[ndarray, float, Tuple[float, float]]:
    # Resize and pad image while meeting stride-multiple constraints
    shape = im.shape[:2]  # current shape [height, width]
    if isinstance(new_shape, int):
        new_shape = (new_shape, new_shape)

    # Scale ratio (new / old)
    r = min(new_shape[0] / shape[0], new_shape[1] / shape[1])

    # Compute padding
    new_unpad = int(round(shape[1] * r)), int(round(shape[0] * r))
    dw, dh = new_shape[1] - new_unpad[0], new_shape[0] - new_unpad[
        1]  # wh padding

    dw /= 2  # divide padding into 2 sides
    dh /= 2

    if shape[::-1] != new_unpad:  # resize
        im = cv2.resize(im, new_unpad, interpolation=cv2.INTER_LINEAR)
    top, bottom = int(round(dh - 0.1)), int(round(dh + 0.1))
    left, right = int(round(dw - 0.1)), int(round(dw + 0.1))
    im = cv2.copyMakeBorder(im,
                            top,
                            bottom,
                            left,
                            right,
                            cv2.BORDER_CONSTANT,
                            value=color)  # add border
    return im, r, (dw, dh)


def blob(im: ndarray, return_seg: bool = False) -> Union[ndarray, Tuple]:
    if return_seg:
        seg = im.astype(np.float32) / 255
    im = im.transpose([2, 0, 1])
    im = im[np.newaxis, ...]
    im = np.ascontiguousarray(im).astype(np.float32) / 255
    if return_seg:
        return im, seg
    else:
        return im


if __name__ == '__main__':
    bgr = cv2.imread('data/bus.jpg')
    Engine = TRTEngine('yolov8n.engine')
    H, W = Engine.inp_info[0].shape[-2:]

    draw = bgr.copy()
    bgr, ratio, dwdh = letterbox(bgr, (W, H))
    rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
    tensor = blob(rgb, return_seg=False)
    dwdh = np.array(dwdh * 2, dtype=np.float32)
    tensor = np.ascontiguousarray(tensor)
    # inference
    data = Engine(tensor)

    bboxes, scores, labels = det_postprocess(data)
    bboxes -= dwdh
    bboxes /= ratio

    for (bbox, score, label) in zip(bboxes, scores, labels):
        bbox = bbox.round().astype(np.int32).tolist()
        cls_id = int(label)
        cls = CLASSES[cls_id]
        color = COLORS[cls]
        cv2.rectangle(draw, bbox[:2], bbox[2:], color, 2)
        cv2.putText(draw,
                    f'{cls}:{score:.3f}', (bbox[0], bbox[1] - 2),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.75, [225, 255, 255],
                    thickness=2)

        cv2.imshow('result', draw)
        cv2.waitKey(0)

```
Here is a simple demo.
Notice! You should generate yolov8n.engine by this repo.
If you generate engine by ultralytics, it will not work.
``` shell
python3 export-det.py --weights yolov8n.pt --sim
python3 build.py --weights yolov8n.onnx --fp16  --device cuda:0
```

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!

**Comment by programmeddeath1** [comment]
Hi,
the jetson nano comes with cuda 10.2
The tensorrt installed is 8.3 by default in jetpack 4.6.3.
It has ubuntu 18 with python 3.6.9

Ultralytics packages cannot be installed because it requires python 3.7 as minimum. 

I installed python 3.10 from source and was able to run the ultralytics yolov8 models. I want to run tensorrt inference.
But the tensorrt python package claims to have wheels only for cuda 11.x (https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html)
```The tensorrt Python wheel files only support Python versions 3.6 to 3.10 and CUDA 11.x at this time and will not work with other Python or CUDA versions. Only the Linux operating system and x86_64 CPU architecture is currently supported. These Python wheel files are expected to work on CentOS 7 or newer and Ubuntu 18.04 or newer.
```

I tried to export the onnx model and yolov8n/s.engine from the pc to the jetson nano, but both the infer and infer without torch still give me the same error` no module named tensorrt.`

How to run this in the jetson nano?

**Comment by triple-Mu** [comment]
> 

Could you please update your jetpack?
Here: https://developer.nvidia.com/embedded/jetpack
You'd best install cuda-11.x and tensorrt-8.4x.

**Comment by programmeddeath1** [comment]
But jetpack 5 does not support Jetson Nano. Mine is an emmc module so the only way for me to boot is through the nvidia sdkmanager.

Are you saying i have to manually install cuda 11 and tensorrt 8.4 on my nano by deleting the older one and building within the nano?

**Comment by triple-Mu** [comment]
> But jetpack 5 does not support Jetson Nano. Mine is an emmc module so the only way for me to boot is through the nvidia sdkmanager.
> 
> Are you saying i have to manually install cuda 11 and tensorrt 8.4 on my nano by deleting the older one and building within the nano?

Got it.
I will make a new dir for Jetson. But I have no Jetson, could you please help me to verify it?

**Comment by programmeddeath1** [comment]
Sure I can help you verify it. By new dir, do you mean you are planning to customize the code for cuda 10.2 and tensorrt 8.3 or do you want me to test manual upgrade of jetson nano to latest CUDA version.

**Comment by pastukhov-aleksandr** [comment]
> Sure I can help you verify it. By new dir, do you mean you are planning to customize the code for cuda 10.2 and tensorrt 8.3 or do you want me to test manual upgrade of jetson nano to latest CUDA version.
customize the code for cuda 10.2 and tensorrt 8.3 ! it would help me too. Thank you!

**Comment by triple-Mu** [comment]
I release a new version for jetson.
https://github.com/triple-Mu/YOLOv8-TensorRT/blob/main/docs/Jetson.md
