### ISSUE TITLE
c++ tensorrt infer with error!

### ISSUE THREAD

**Issue by jcyhcs** [triple-Mu/YOLOv8-TensorRT#3]
hi, @triple-Mu 
i use ultralytics offical export cli command like: yolo task=detect mode=export model=yolov8s.pt format=onnx opset=11, i got onnx and then use trtexec convert to engine, i success compile your c++ demo， when i use this demo to load tensorrt engine, i got error:
ERROR: 3: Cannot find binding of given name: num_dets
ERROR: 3: Cannot find binding of given name: scores....
so, how can i resolve this ? please help me!

**Comment by triple-Mu** [comment]
Please use export.py and build.py to build your tensorrt engine.
I have optimized the onnx model when export.

**Comment by triple-Mu** [comment]
> hi, @triple-Mu i use ultralytics offical export cli command like: yolo task=detect mode=export model=yolov8s.pt format=onnx opset=11, i got onnx and then use trtexec convert to engine, i success compile your c++ demo， when i use this demo to load tensorrt engine, i got error: ERROR: 3: Cannot find binding of given name: num_dets ERROR: 3: Cannot find binding of given name: scores.... so, how can i resolve this ? please help me!

How about now？

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
