### ISSUE TITLE
为啥yolov8 的n模型比v5的s模型慢呢

### ISSUE THREAD

**Issue by liuxiaoxiao666** [triple-Mu/YOLOv8-TensorRT#30]
为啥yolov8 的n模型比v5的s模型慢呢

**Comment by triple-Mu** [comment]
> 为啥yolov8 的n模型比v5的s模型慢呢

你比较的是端到端吗？这个仓库把后处理和NMS也放到模型里面了

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
