### ISSUE TITLE
Inference fails with YOLOv8 exported engine file.

### ISSUE THREAD

**Issue by titq2022** [triple-Mu/YOLOv8-TensorRT#33]
Inference fails, does it not support segmentation?

**export**
```
from ultralytics import YOLO

model = YOLO("yolov8m-seg.pt")
success = model.export(format="engine", half=True, device=0)
```
inference
```
!python3 ./YOLOv8-TensorRT/infer-seg.py \
--engine yolov8m-seg.engine \
--imgs "bus.jpg" \
--out-dir ./tmp \
--device cuda:0
```
trace
```
[02/19/2023-21:35:40] [TRT] [W] TensorRT was linked against cuDNN 8.6.0 but loaded cuDNN 8.5.0
[02/19/2023-21:35:40] [TRT] [W] TensorRT was linked against cuDNN 8.6.0 but loaded cuDNN 8.5.0
Traceback (most recent call last):
  File "/workdir/./YOLOv8-TensorRT/infer-seg.py", line 106, in <module>
    main(args)
  File "/workdir/./YOLOv8-TensorRT/infer-seg.py", line 20, in main
    Engine.set_desired(['outputs', 'proto'])
  File "/workdir/YOLOv8-TensorRT/models/engine.py", line 287, in set_desired
    self.idx = [self.output_names.index(i) for i in desired]
  File "/workdir/YOLOv8-TensorRT/models/engine.py", line 287, in <listcomp>
    self.idx = [self.output_names.index(i) for i in desired]
ValueError: 'outputs' is not in list
```

**Comment by triple-Mu** [comment]
> Inference fails, does it not support segmentation?
> 
> **export**
> 
> ```
> from ultralytics import YOLO
> 
> model = YOLO("yolov8m-seg.pt")
> success = model.export(format="engine", half=True, device=0)
> ```
> 
> inference
> 
> ```
> !python3 ./YOLOv8-TensorRT/infer-seg.py \
> --engine yolov8m-seg.engine \
> --imgs "bus.jpg" \
> --out-dir ./tmp \
> --device cuda:0
> ```
> 
> trace
> 
> ```
> [02/19/2023-21:35:40] [TRT] [W] TensorRT was linked against cuDNN 8.6.0 but loaded cuDNN 8.5.0
> [02/19/2023-21:35:40] [TRT] [W] TensorRT was linked against cuDNN 8.6.0 but loaded cuDNN 8.5.0
> Traceback (most recent call last):
>   File "/workdir/./YOLOv8-TensorRT/infer-seg.py", line 106, in <module>
>     main(args)
>   File "/workdir/./YOLOv8-TensorRT/infer-seg.py", line 20, in main
>     Engine.set_desired(['outputs', 'proto'])
>   File "/workdir/YOLOv8-TensorRT/models/engine.py", line 287, in set_desired
>     self.idx = [self.output_names.index(i) for i in desired]
>   File "/workdir/YOLOv8-TensorRT/models/engine.py", line 287, in <listcomp>
>     self.idx = [self.output_names.index(i) for i in desired]
> ValueError: 'outputs' is not in list
> ```

The python script in this repo cannot directly read the engine file exported from the ultralytics repo, 
because I have adjusted the model. 
If you want to use the engine file exported by ultralytics, you can check the c++ code in `csrc/segment/normal`

**Comment by triple-Mu** [comment]
The reason is that the ultralytics repo itself can read the model and inference, 
and this repo is mainly for deeper acceleration, so the exported model will be different.

**Comment by titq2022** [comment]
Thank you Triple-Mu!
I don't have nvidia-cuda-toolkit installed.
So I will try export-seg.py.
