### ISSUE TITLE
Question about given models

### ISSUE THREAD

**Issue by CasparTheGhost** [triple-Mu/YOLOv8-TensorRT#34]
Hey,
it would be very cool if you could provide further information on how you exported the onnx models which you provided in the repo to export them to the .engine files. My exported ONNX files always dont work but yours do. The difference i see is the opset version which is 12 or 11 for me and your files have 17. Are there any special steps you could tell me that i can export the trained .onnx files the same way you do?

Thanks in advance
Caspar

**Comment by triple-Mu** [comment]
You can follow the readme for onnx export.
For example:
``` shell
python3 export-det.py \
--weights yolov8s.pt \
--iou-thres 0.65 \
--conf-thres 0.25 \
--topk 100 \
--opset 17 \
--sim \
--input-shape 1 3 640 640 \
--device cuda:0
```
Notice that the opset we set is 17.
The onnx I provide is modified by onnx api, it is the same as which is exported by the command.
