### ISSUE TITLE
Scores of all classes instead of only highest

### ISSUE THREAD

**Issue by sezer-muhammed** [triple-Mu/YOLOv8-TensorRT#35]
Hi,

How Can I get all scores for all detections?

Scores shape is batch×num_detection
I want it to be batch×num_detection×class_num

**Comment by triple-Mu** [comment]
You can modify the cpp demo of normal yolov8 model.
End2end model needs to feed all scores and gets the highest one for every object.

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
