### ISSUE TITLE
RGB image blob function

### ISSUE THREAD

**Issue by sezer-muhammed** [triple-Mu/YOLOv8-TensorRT#36]
There is a transpose line in blob I think this converts BGR to RGB or RGB to BGR. But input image is already RGB so why there is transpose line in blob function?

**Comment by triple-Mu** [comment]
> There is a transpose line in blob I think this converts BGR to RGB or RGB to BGR. But input image is already RGB so why there is transpose line in blob function?

If you use opencv to read image, the image is default bgr, so the blob function is to convert bgr to rgb.
If your image is rgb, you could common this line:
``` python
# image = image[:,:,::-1]
```

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!

**Comment by willwang-ai** [comment]
> There is a transpose line in blob I think this converts BGR to RGB or RGB to BGR. But input image is already RGB so why there is transpose line in blob function?

![image](https://user-images.githubusercontent.com/29682883/233817791-efd92919-e2b8-4b0b-93da-1efffba29bc4.png)

The annotations in the picture may help you.
