### ISSUE TITLE
Passing the Win32 BitBlt captured frame to YOLOv8 TensorRT

### ISSUE THREAD

**Issue by anzenchitai** [triple-Mu/YOLOv8-TensorRT#37]
I am capturing frames using BitBlt without any problems but how can I pass the frames to YOLOv8 TensorRT? Can someone provide me with a C++ example please? I tried using Ultralytics YOLOv8n with ONNX but it obviously has performance issues.

**Comment by triple-Mu** [comment]
> BitBlt

I have no idea with BitBlt.
I am not sure whether opencv support it?
``` c++
auto cap = cv::VideoCapture("***bitblt***");
```

**Comment by anzenchitai** [comment]
> > BitBlt
> 
> I have no idea with BitBlt. I am not sure whether opencv support it?
> 
> ```c++
> auto cap = cv::VideoCapture("***bitblt***");
> ```

Please disregard my first question. I can't even get the inference to work with C++.

`ERROR: 1: [stdArchiveReader.cpp::nvinfer1::rt::StdArchiveReader::StdArchiveReader::32] Error Code 1: Serialization (Serialization assertion magicTagRead == kMAGIC_TAG failed.Magic tag does not match)
ERROR: 4: [runtime.cpp::nvinfer1::Runtime::deserializeCudaEngine::66] Error Code 4: Internal Error (Engine deserialization failed.)`

**Comment by triple-Mu** [comment]
> 

Could you please provide more detail log?
Or could you please upload the pt and onnx model?

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
