### ISSUE TITLE
These py scripts don't work if you try them on an onnx file exported by the ultralytics repo. Must use this repo to convert pt to onnx

### ISSUE THREAD

**Issue by AdamRoden** [triple-Mu/YOLOv8-TensorRT#38]
Did some earlier version of these scripts work? Do the current versions work for anyone else? I'm trying to figure out my problems, but it always leads back to missing/incomplete code/files

**Comment by triple-Mu** [comment]
> Did some earlier version of these scripts work? Do the current versions work for anyone else? I'm trying to figure out my problems, but it always leads back to missing/incomplete code/files

Could you please provide detail log?
Or could you please provide the pt model?

**Comment by AdamRoden** [comment]
Here's build.py:
```
(aim) C:\Users\adamr\YOLOv8-TensorRT-main>python build.py --weights yolov8l.onnx --iou-thres 0.25 --conf-thres 0.05 --topk 9 --fp16  --device cuda:0
Traceback (most recent call last):
  File "C:\Users\adamr\YOLOv8-TensorRT-main\build.py", line 56, in <module>
    main(args)
  File "C:\Users\adamr\YOLOv8-TensorRT-main\build.py", line 47, in main
    builder.build(fp16=args.fp16,
  File "C:\Users\adamr\YOLOv8-TensorRT-main\models\engine.py", line 75, in build
    self.__build_engine(fp16, input_shape, iou_thres, conf_thres, topk,
  File "C:\Users\adamr\YOLOv8-TensorRT-main\models\engine.py", line 55, in __build_engine
    self.build_from_onnx(iou_thres, conf_thres, topk)
  File "C:\Users\adamr\YOLOv8-TensorRT-main\models\engine.py", line 85, in build_from_onnx
    onnx_model.graph.node[-1].attribute[2].i = topk
IndexError: list index (2) out of range

**Comment by AdamRoden** [comment]
Here's infer-det.py:
```
(aim) C:\Users\adamr\YOLOv8-TensorRT-main>python infer-det.py --engine yolov8l.engine --imgs data --show --out-dir outputs --device cuda:0
Traceback (most recent call last):
  File "C:\Users\adamr\YOLOv8-TensorRT-main\infer-det.py", line 82, in <module>
    main(args)
  File "C:\Users\adamr\YOLOv8-TensorRT-main\infer-det.py", line 39, in main
    bboxes, scores, labels = det_postprocess(data)
  File "C:\Users\adamr\YOLOv8-TensorRT-main\models\torch_utils.py", line 37, in det_postprocess
    assert len(data) == 4
AssertionError

**Comment by triple-Mu** [comment]
The onnx you build engine is exported by this repo, not by ultralytics repo.
Why?
Beacuse I have merged postprocess such as nms into onnx when export onnx.
If you use ultralytics repo, you could not get onnx with nms.

**Comment by AdamRoden** [comment]
Here's me trying to replicate your work in my code... No trtmodule. Where does that come from?
```
Traceback (most recent call last):
  File "C:\Users\adamr\YOLOv8-TensorRT-main\trt.py", line 180, in <module>
    Engine = TRTModule('yolov8l.engine', device)
NameError: name 'TRTModule' is not defined

**Comment by triple-Mu** [comment]
> Here's me trying to replicate your work in my code... No trtmodule. Where does that come from?
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\adamr\YOLOv8-TensorRT-main\trt.py", line 180, in <module>
>     Engine = TRTModule('yolov8l.engine', device)
> NameError: name 'TRTModule' is not defined
> ```

Where do you get trt.py?

**Comment by AdamRoden** [comment]
trt.py is my file running some of your code.

**Comment by triple-Mu** [comment]
`TRTModule` is in `models/engine.py`

**Comment by AdamRoden** [comment]
Okay, I'm going to back up and try the end2end like you said and will let you know if that works for me . Thanks so far.

**Comment by triple-Mu** [comment]
> Okay, I'm going to back up and try the end2end like you said and will let you know if that works for me . Thanks so far.

You are welcome~

**Comment by triple-Mu** [comment]
> Starting the whole process using end2end worked! The export appeared to be stuck, but finished after a wait. So, what I don't yet understand is why it only works with your version of an exported onnx file. Is your onnx a custom file type? Could you not alter your code to infer the missing fields and use other onnx files? Whatever the case, I think it is critical to point out. I used ultralytics to export my onnx model and that was what got me stuck.
> 
> 
> 
> > The onnx you build engine is exported by this repo, not by ultralytics repo. Why? Beacuse I have merged postprocess such as nms into onnx when export onnx. If you use ultralytics repo, you could not get onnx with nms.

In order to make the model export post-processing from the pytorch and simplify some operations, remove such as transpose and complex anchor processing operations, so I choose to modify from the pytorch model. This is possible if you have a requirement to use the ult repository exported onnx and convert it.

**Comment by triple-Mu** [comment]
> > Starting the whole process using end2end worked! The export appeared to be stuck, but finished after a wait. So, what I don't yet understand is why it only works with your version of an exported onnx file. Is your onnx a custom file type? Could you not alter your code to infer the missing fields and use other onnx files? Whatever the case, I think it is critical to point out. I used ultralytics to export my onnx model and that was what got me stuck.
> > 
> > 
> > 
> > > The onnx you build engine is exported by this repo, not by ultralytics repo. Why? Beacuse I have merged postprocess such as nms into onnx when export onnx. If you use ultralytics repo, you could not get onnx with nms.
> 
> In order to make the model export post-processing from the pytorch and simplify some operations, remove such as transpose and complex anchor processing operations, so I choose to modify from the pytorch model. This is possible if you have a requirement to use the ult repository exported onnx and convert it.
> 

BTW. Do you get right results using this repo？
How about the speed？

**Comment by AdamRoden** [comment]
I just finished building my yolov8l.engine with your repo. Now, I'll try coding it into my process and see if I can get it working with improved speed. It may take me a while, but I will let you know how it goes.

**Comment by triple-Mu** [comment]
> I just finished building my yolov8l.engine with your repo. Now, I'll try coding it into my process and see if I can get it working with improved speed. It may take me a while, but I will let you know how it goes.

Great.
Congratulations in advance

**Comment by AdamRoden** [comment]
Well, I got the code up and running and to my surprise the version using yolov8l.engine is NOT faster than yolov8l.pt.

My speed is about 30 fps either way I do it. In my original code, 70% of the time was spent running the model. With TensorRT I only spend about 50% of the time running the model, but there is 20% new overhead.

Performance tuning has revealed that any gains in using .engine are offset by the additional overhead of this code:
```
        bgr, ratio, dwdh = letterbox(bgr, (W, H))
        tensor = blob(bgr, return_seg=False)
        dwdh = torch.asarray(dwdh * 2, dtype=torch.float32, device=device)
        tensor = torch.asarray(tensor, device=device)
```
Is there a faster way from go from image array to engine?

**Comment by triple-Mu** [comment]
> 

First:
If the model inference is very slow, it may be due to no warm-up loading. 
I will add warm-up 10 times in the next minor version.

Second:
I do not find a good python solution about pre-processing part for the image, you can try the c++ code in `src/detect/end2end`

**Comment by AdamRoden** [comment]
FYI, I just found out Ultralytics is now capable of exporting from .pt to .engine and of running prediction using TensorRT. I tested myself. 
https://github.com/ultralytics/ultralytics/issues/866#issuecomment-1442672573

Thanks for your help. If you make further improvements I'll give them a try, but for now, I'm satisfied.

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
