### ISSUE TITLE
Bug in models/utils.py

### ISSUE THREAD

**Issue by geniusfoever** [triple-Mu/YOLOv8-TensorRT#39]
Thanks for your work!
In file models/utils.py you misused width and height.
The code should be `dw, dh = new_shape[0] - new_unpad[0], new_shape[1] - new_unpad[
        1]  # wh padding`

**Comment by triple-Mu** [comment]
> Thanks for your work! In file models/utils.py you misused width and height. The code should be `dw, dh = new_shape[0] - new_unpad[0], new_shape[1] - new_unpad[ 1] # wh padding`

Could you please pr for it?

**Comment by geniusfoever** [comment]
sure, I also  changed `masks = cv2.resize(masks,
                       (shape[1],shape[0]),
                       interpolation=cv2.INTER_LINEAR)` in function seg_postprocess and `
    r = min(new_shape[0] / shape[1], new_shape[1] / shape[0])` in function letterbox

**Comment by geniusfoever** [comment]
I cannot make a pull request, but the code is already in my repo
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/58506698/220845190-00fa0345-b671-46bf-a0a4-ba90bc503b14.png">

**Comment by triple-Mu** [comment]
> I cannot make a pull request, but the code is already in my repo <img alt="image" width="1222" src="https://user-images.githubusercontent.com/58506698/220845190-00fa0345-b671-46bf-a0a4-ba90bc503b14.png">

It seems that you do not push you code to master?

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
