### ISSUE TITLE
instance segmentation

### ISSUE THREAD

**Issue by chyphen777** [triple-Mu/YOLOv8-TensorRT#4]
Is it also working for instance segmentation?  How do I do it?  Any help will be appreciated.  Thanks.
CC

**Comment by triple-Mu** [comment]
> Is it also working for instance segmentation?  How do I do it?  Any help will be appreciated.  Thanks.
> 
> CC

Now it only support detection.
I will work on seg soon.
Thanks for your keeping a watchful eye on.

**Comment by triple-Mu** [comment]
@chyphen777 
Here is a sample example for seg model.
https://github.com/triple-Mu/YOLOv8-TensorRT/blob/main/docs/Segment.md

**Comment by aurelm95** [comment]
I am also interested in deploying a instance segmentacion yolov8 model with deepstream. Will this feature be available ? Or any idea how I can proceed?

Thanks!

**Comment by triple-Mu** [comment]
> I am also interested in deploying a instance segmentacion yolov8 model with deepstream. Will this feature be available ? Or any idea how I can proceed?
> 
> 
> 
> Thanks!

This is also a feature I want to support. At present, because the plugin used for detection cannot be used for segmentation, the post-processing of segmentation needs to be completed again. I think as long as the post-processing part of the code is implemented, it can be deployed in deepstream.

**Comment by triple-Mu** [comment]
> I am also interested in deploying a instance segmentacion yolov8 model with deepstream. Will this feature be available ? Or any idea how I can proceed?
> 
> 
> 
> Thanks!

https://github.com/triple-Mu/YOLOv8-TensorRT/tree/main/csrc/segment
Here is a c++ postprocess for seg.
Maybe we can use it in deepstream.

**Comment by aurelm95** [comment]
I have seen that here author of this repo https://github.com/hiennguyen9874/deepstream-realtime-instance-segmentation has shared  a custom NMS tensorrt plugin for instance segmentation and the corresponding parsers for deepstream. I  don't if that's the best way to proceed

**Comment by triple-Mu** [comment]
> I have seen that here author of this repo https://github.com/hiennguyen9874/deepstream-realtime-instance-segmentation has shared  a custom NMS tensorrt plugin for instance segmentation and the corresponding parsers for deepstream. I  don't if that's the best way to proceed

I haven seen the nms plugin for seg in this repo.
It seems that it use the same plugin as my repo.

**Comment by aurelm95** [comment]
> > I have seen that here author of this repo https://github.com/hiennguyen9874/deepstream-realtime-instance-segmentation has shared  a custom NMS tensorrt plugin for instance segmentation and the corresponding parsers for deepstream. I  don't if that's the best way to proceed
> 
> I haven't seen the nms plugin for seg in this repo. It seems that it use the same plugin as my repo.

As far as I understand, in this file: https://github.com/hiennguyen9874/TensorRT/blob/release/8.4/plugin/efficientNMSCustomPlugin/efficientNMSCustomPlugin.cpp, he modifies the TensoRT nms plugin in order to be compatible with the 5 oupts of the yolov7-seg (beacuse it also has the mask)

**Comment by triple-Mu** [comment]
Recently, I tried to use another function of the official EfficientNMS to post-process the segmentation model, which avoids the use of additional APIs for NMS. But the output Tensor is very large. You can view this link: https://github.com/triple-Mu/YOLOv8-TensorRT/tree/triplemu/nms-plugin-seg

**Comment by aurelm95** [comment]
> Recently, I tried to use another function of the official EfficientNMS to post-process the segmentation model, which avoids the use of additional APIs for NMS. But the output Tensor is very large. You can view this link: https://github.com/triple-Mu/YOLOv8-TensorRT/tree/triplemu/nms-plugin-seg

I need to learn more to really understand what you have done. I will keep an eye on this great repo!

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
