### ISSUE TITLE
run in windows ?

### ISSUE THREAD

**Issue by dany137718** [triple-Mu/YOLOv8-TensorRT#41]
how can I run this cpp code in windows?
I get some library errors.

**Comment by triple-Mu** [comment]
> how can I run this cpp code in windows? I get some library errors.

You should prepare cuda cudnn tensorrt opencv. If some api does not support in windows, you should modify it.

**Comment by triple-Mu** [comment]
> Code can work fine in Windows,I tried

Thanks for your reply！

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!

**Comment by kimtaehyeong** [comment]
hello.
Can you tell me the cmake file and cuda cudnn version to run on windows?
Thanks..:)
