### ISSUE TITLE
分割模型转TRT

### ISSUE THREAD

**Issue by milely** [triple-Mu/YOLOv8-TensorRT#42]
感谢分享优秀的工作，请问分割模型转TensorRT模型时是否可以带着NMS plugin呢？

**Comment by triple-Mu** [comment]
> 感谢分享优秀的工作，请问分割模型转TensorRT模型时是否可以带着NMS plugin呢？

有尝试是用 onnx 版本的 NMS，不过在 batch 推理上有点问题，batch=1可用。
如果需要能够 batch 推理的版本，需要自己写 plugin

**Comment by milely** [comment]
好的，我会尝试下。感谢答复
