### ISSUE TITLE
Predict more than one frame at the sametime

### ISSUE THREAD

**Issue by KevsernurE** [triple-Mu/YOLOv8-TensorRT#43]
Hello,

In ultralytics repo we can use batch prediction like these:
```
frames = [frame1, frame2, ..]
results = model(frames)
``` 

how can we use batch prediction in this repo?

**Comment by triple-Mu** [comment]
> 

Maybe you should export dynamic batch onnx for engine building.
And add a function for preparing batched images,
and parser outputs for every image in batch.

**Comment by triple-Mu** [comment]
Here is a onnx export demo.
https://github.com/triple-Mu/YOLOv8-TensorRT/pull/44

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
