### ISSUE TITLE
实例分割代码

### ISSUE THREAD

**Issue by milely** [triple-Mu/YOLOv8-TensorRT#45]
作者你好，在实例分割的后处理过程中。最后得到每个实例的mask的那一步，是否忘记加sigmoid函数了呢?这一步是有其他的什么考虑吗，但似乎不影响性能。
![image](https://user-images.githubusercontent.com/19663249/222105430-972fe142-18ac-4698-9dbc-d6673fb5f8fa.png)
![image](https://user-images.githubusercontent.com/19663249/222105514-8cdb08b5-243a-4570-8127-06cce108f8b5.png)

**Comment by triple-Mu** [comment]
> 作者你好，在实例分割的后处理过程中。最后得到每个实例的mask的那一步，是否忘记加sigmoid函数了呢?这一步是有其他的什么考虑吗，但似乎不影响性能。
> 
> ![image](https://user-images.githubusercontent.com/19663249/222105430-972fe142-18ac-4698-9dbc-d6673fb5f8fa.png)
> 
> ![image](https://user-images.githubusercontent.com/19663249/222105514-8cdb08b5-243a-4570-8127-06cce108f8b5.png)
> 
> 

后处理代码摘抄自yolov8 没什么变化。

**Comment by milely** [comment]
YOLOV8的后处理代码中好像是带着的，不知道是不是我理解错了呢
![image](https://user-images.githubusercontent.com/19663249/222125083-ce234f82-14cd-4948-a16e-a409e74480ca.png)

**Comment by triple-Mu** [comment]
> YOLOV8的后处理代码中好像是带着的，不知道是不是我理解错了呢
> 
> ![image](https://user-images.githubusercontent.com/19663249/222125083-ce234f82-14cd-4948-a16e-a409e74480ca.png)
> 
> 
> 
> 

嗷嗷，那可能我确实没加，疏忽啦。

**Comment by triple-Mu** [comment]
> 作者你好，在实例分割的后处理过程中。最后得到每个实例的mask的那一步，是否忘记加sigmoid函数了呢?这一步是有其他的什么考虑吗，但似乎不影响性能。
> 
> ![image](https://user-images.githubusercontent.com/19663249/222105430-972fe142-18ac-4698-9dbc-d6673fb5f8fa.png)
> 
> ![image](https://user-images.githubusercontent.com/19663249/222105514-8cdb08b5-243a-4570-8127-06cce108f8b5.png)
> 
> 

您愿意提个pr把numpy和pytorch版本的分割后处理修复吗？

**Comment by milely** [comment]
十分抱歉，现在我把YOLOV8的分割部分改成了其他的分割方法，现在没有办法验证我修改的是否正确。等我弄完了，我提个pr吧。

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
