### ISSUE TITLE
How to perform end2end detection

### ISSUE THREAD

**Issue by Ghustwb** [triple-Mu/YOLOv8-TensorRT#46]
Hi, triple-Mu
Thanks for you good jjob, normal detection code can work fine in my device, just I want to know how to perform the end2end (onnx-nms) detection.
As I found that postprocess is slow in CPU

**Comment by triple-Mu** [comment]
> Hi, triple-Mu
> 
> Thanks for you good jjob, normal detection code can work fine in my device, just I want to know how to perform the end2end (onnx-nms) detection.
> 
> As I found that postprocess is slow in CPU

Please follow readme and use csrc/detect/end2end to infer with end2end.

**Comment by Ghustwb** [comment]
I had exported onnx file by Ultralytics, but it is different with onnx-nms from you. Is there way to export onnx-nms model?

**Comment by triple-Mu** [comment]
> I had exported onnx file by Ultralytics, but it is different with onnx-nms from you. Is there way to export onnx-nms model?

All right.
The export-det.py is for export end2end onnx.

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
