### ISSUE TITLE
Yolo v8 conversion model, no output during inference

### ISSUE THREAD

**Issue by andreazuna89** [triple-Mu/YOLOv8-TensorRT#47]
Hi! I am currently trying your repo for converting a yolo v8 model (yolov8s.pt) using a Jetson Orin. I have been trying the export-det.py and then the build.py script. The model is converted but when I do inference with the produced engine I get an output always containing zeros and no detection is produced. Can you help me to understand where is the issue?

Thanks a lot
Andrea

**Comment by triple-Mu** [comment]
> Hi! I am currently trying your repo for converting a yolo v8 model (yolov8s.pt) using a Jetson Orin. I have been trying the export-det.py and then the build.py script. The model is converted but when I do inference with the produced engine I get an output always containing zeros and no detection is produced. Can you help me to understand where is the issue?
> 
> 
> 
> Thanks a lot
> 
> Andrea

Could you please show me your infer script or your onnx model?
or how could I reproduce your issue？

**Comment by andreazuna89** [comment]
```
root@ubuntu:/YOLOv8-TensorRT# python3 export-det.py --weights yolov8s.pt --iou-thres 0.65 --conf-thres 0.25 --topk 100 --opset 11 --sim --input-shape 1 3 640 640 --device cuda:0
Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8s.pt to yolov8s.pt...
100%|██████████████████████████████████████| 21.5M/21.5M [00:04<00:00, 5.01MB/s]
YOLOv8s summary (fused): 168 layers, 11156544 parameters, 0 gradients, 28.6 GFLOPs
[W shape_type_inference.cpp:1913] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
[W shape_type_inference.cpp:1913] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
[W shape_type_inference.cpp:1913] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
[W shape_type_inference.cpp:1913] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
====== Diagnostic Run torch.onnx.export version 2.0.0a0+ec3941ad.nv23.02 =======
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 4 WARNING 0 ERROR ========================
4 WARNING were not printed due to the log level.

Simplifier failure: 'NoneType' object has no attribute 'simplify'
ONNX export success, saved as yolov8s.onnx
root@ubuntu:/YOLOv8-TensorRT# ^C
root@ubuntu:/YOLOv8-TensorRT# python3 build.py --weights yolov8s.onnx --iou-thres 0.65 --conf-thres 0.25 --topk 100 --fp16  --device cuda:0
[03/01/2023-14:28:21] [TRT] [W] onnx2trt_utils.cpp:375: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[03/01/2023-14:28:21] [TRT] [W] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
[03/01/2023-14:28:21] [TRT] [W] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
[03/01/2023-14:28:21] [TRT] [W] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
[03/01/2023-14:28:21] [TRT] [W] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
[03/01/2023-14:28:21] [TRT] [W] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
[03/01/2023-14:28:21] [TRT] [W] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
[03/01/2023-14:28:21] [TRT] [W] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
[03/01/2023-14:28:21] [TRT] [W] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
[03/01/2023-14:28:21] [TRT] [W] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
[03/01/2023-14:28:21] [TRT] [W] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
[03/01/2023-14:28:21] [TRT] [W] input "images" with shape: (1, 3, 640, 640) dtype: DataType.FLOAT
[03/01/2023-14:28:21] [TRT] [W] output "num_dets" with shape: (1, 1) dtype: DataType.INT32
[03/01/2023-14:28:21] [TRT] [W] output "bboxes" with shape: (1, 100, 4) dtype: DataType.FLOAT
[03/01/2023-14:28:21] [TRT] [W] output "scores" with shape: (1, 100) dtype: DataType.FLOAT
[03/01/2023-14:28:21] [TRT] [W] output "labels" with shape: (1, 100) dtype: DataType.INT32
[03/01/2023-14:46:25] [TRT] [W] TensorRT encountered issues when converting weights between types and that could affect accuracy.
[03/01/2023-14:46:25] [TRT] [W] If this is not the desired behavior, please modify the weights or retrain with regularization to adjust the magnitude of the weights.
[03/01/2023-14:46:25] [TRT] [W] Check verbose logs for the list of affected weights.
[03/01/2023-14:46:25] [TRT] [W] - 1 weights are affected by this issue: Detected NaN values and converted them to corresponding FP16 NaN.
[03/01/2023-14:46:25] [TRT] [W] - 59 weights are affected by this issue: Detected subnormal FP16 values.
[03/01/2023-14:46:25] [TRT] [W] Build tensorrt engine finish.
Save in /YOLOv8-TensorRT/yolov8s.engine
root@ubuntu:/YOLOv8-TensorRT# python3 infer-det.py --engine yolov8s.engine --imgs data --show --out-dir outputs --device cuda:0
   ```
The final script infer-det.py does not produce any detection results. I noticed that warning in the engine conversion: 
   ```
[03/01/2023-14:46:25] [TRT] [W] - 1 weights are affected by this issue: Detected NaN values and converted them to corresponding FP16 NaN.
[03/01/2023-14:46:25] [TRT] [W] - 59 weights are affected by this issue: Detected subnormal FP16 values.
   ```
Is that an issue? I have also tried using fp32 precision, I did not get that warning but same results without detections produced. Can you help me?

**Comment by triple-Mu** [comment]
>    ```
> 
> root@ubuntu:/YOLOv8-TensorRT# python3 export-det.py --weights yolov8s.pt --iou-thres 0.65 --conf-thres 0.25 --topk 100 --opset 11 --sim --input-shape 1 3 640 640 --device cuda:0
> 
> Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8s.pt to yolov8s.pt...
> 
> 100%|██████████████████████████████████████| 21.5M/21.5M [00:04<00:00, 5.01MB/s]
> 
> YOLOv8s summary (fused): 168 layers, 11156544 parameters, 0 gradients, 28.6 GFLOPs
> 
> [W shape_type_inference.cpp:1913] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
> 
> [W shape_type_inference.cpp:1913] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
> 
> [W shape_type_inference.cpp:1913] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
> 
> [W shape_type_inference.cpp:1913] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
> 
> ====== Diagnostic Run torch.onnx.export version 2.0.0a0+ec3941ad.nv23.02 =======
> 
> verbose: False, log level: Level.ERROR
> 
> ======================= 0 NONE 0 NOTE 4 WARNING 0 ERROR ========================
> 
> 4 WARNING were not printed due to the log level.
> 
> 
> 
> Simplifier failure: 'NoneType' object has no attribute 'simplify'
> 
> ONNX export success, saved as yolov8s.onnx
> 
> root@ubuntu:/YOLOv8-TensorRT# ^C
> 
> root@ubuntu:/YOLOv8-TensorRT# python3 build.py --weights yolov8s.onnx --iou-thres 0.65 --conf-thres 0.25 --topk 100 --fp16  --device cuda:0
> 
> [03/01/2023-14:28:21] [TRT] [W] onnx2trt_utils.cpp:375: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
> 
> [03/01/2023-14:28:21] [TRT] [W] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
> 
> [03/01/2023-14:28:21] [TRT] [W] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
> 
> [03/01/2023-14:28:21] [TRT] [W] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
> 
> [03/01/2023-14:28:21] [TRT] [W] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
> 
> [03/01/2023-14:28:21] [TRT] [W] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
> 
> [03/01/2023-14:28:21] [TRT] [W] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
> 
> [03/01/2023-14:28:21] [TRT] [W] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
> 
> [03/01/2023-14:28:21] [TRT] [W] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
> 
> [03/01/2023-14:28:21] [TRT] [W] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
> 
> [03/01/2023-14:28:21] [TRT] [W] onnx2trt_utils.cpp:403: One or more weights outside the range of INT32 was clamped
> 
> [03/01/2023-14:28:21] [TRT] [W] input "images" with shape: (1, 3, 640, 640) dtype: DataType.FLOAT
> 
> [03/01/2023-14:28:21] [TRT] [W] output "num_dets" with shape: (1, 1) dtype: DataType.INT32
> 
> [03/01/2023-14:28:21] [TRT] [W] output "bboxes" with shape: (1, 100, 4) dtype: DataType.FLOAT
> 
> [03/01/2023-14:28:21] [TRT] [W] output "scores" with shape: (1, 100) dtype: DataType.FLOAT
> 
> [03/01/2023-14:28:21] [TRT] [W] output "labels" with shape: (1, 100) dtype: DataType.INT32
> 
> [03/01/2023-14:46:25] [TRT] [W] TensorRT encountered issues when converting weights between types and that could affect accuracy.
> 
> [03/01/2023-14:46:25] [TRT] [W] If this is not the desired behavior, please modify the weights or retrain with regularization to adjust the magnitude of the weights.
> 
> [03/01/2023-14:46:25] [TRT] [W] Check verbose logs for the list of affected weights.
> 
> [03/01/2023-14:46:25] [TRT] [W] - 1 weights are affected by this issue: Detected NaN values and converted them to corresponding FP16 NaN.
> 
> [03/01/2023-14:46:25] [TRT] [W] - 59 weights are affected by this issue: Detected subnormal FP16 values.
> 
> [03/01/2023-14:46:25] [TRT] [W] Build tensorrt engine finish.
> 
> Save in /YOLOv8-TensorRT/yolov8s.engine
> 
> root@ubuntu:/YOLOv8-TensorRT# python3 infer-det.py --engine yolov8s.engine --imgs data --show --out-dir outputs --device cuda:0
> 
>    ```
> 
> The final script infer-det.py does not produce any detection results. I noticed that warning in the engine conversion: 
> 
>    ```
> 
> [03/01/2023-14:46:25] [TRT] [W] - 1 weights are affected by this issue: Detected NaN values and converted them to corresponding FP16 NaN.
> 
> [03/01/2023-14:46:25] [TRT] [W] - 59 weights are affected by this issue: Detected subnormal FP16 values.
> 
>    ```
> 
> Is that an issue? I have also tried using fp32 precision, I did not get that warning but same results without detections produced. Can you help me?

Sure. May you upload your onnx?

**Comment by andreazuna89** [comment]
How can I open it and paste properly here?

**Comment by triple-Mu** [comment]
> How can I open it and paste properly here?

You can upload to googledrive or any web drive.

**Comment by andreazuna89** [comment]
I have solved it by installing onnxsim. Now the output is correct! Thanks a lot for your help!

**Comment by andreazuna89** [comment]
Sorry, last issue. I was now trying to use a yolov8 model converted using tensorrt. When I do the following command:
   ```
from ultralytics import YOLO
results= YOLO('./yolov8s.engine').predict(device=0)
   ```

I get the following error:
   ```
Ultralytics YOLOv8.0.44 🚀 Python-3.8.10 torch-2.0.0a0+ec3941ad.nv23.02 CUDA:0 (Orin, 30589MiB)
Loading yolov8s.engine for TensorRT inference...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/ultralytics/ultralytics/yolo/engine/model.py", line 201, in predict
    self.predictor.setup_model(model=self.model)
  File "/root/ultralytics/ultralytics/yolo/engine/predictor.py", line 221, in setup_model
    self.model = AutoBackend(model, device=device, dnn=self.args.dnn, data=self.args.data, fp16=self.args.half)
  File "/root/ultralytics/ultralytics/nn/autobackend.py", line 151, in __init__
    meta = json.loads(f.read(meta_len).decode('utf-8'))  # read metadata
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 4: invalid continuation byte
   ```
Do you have any idea here?

Thanks a lot

**Comment by triple-Mu** [comment]
> self.model = AutoBackend(model, device=device, dnn=self.args.dnn, data=self.args.data, fp16=self.args.half)
> File "/root/ultralytics/ultralytics/nn/autobackend.py", line 151, in __init__
>  meta = json.loads(f.read(meta_len).decode('utf-8'))  # read metadata

The engine this repo export can not be used in `YOLO('./yolov8s.engine').predict(device=0)`
It is different from which is exported by  `ultralytics`.
You can see `infer-det.py` for more information about the engine postprocess.
It is more easier than `ultralytics`.

**Comment by andreazuna89** [comment]
Thanks a lot
