### ISSUE TITLE
Getting error related to opencv for segmentation model with out torch 

### ISSUE THREAD

**Issue by anil-debug** [triple-Mu/YOLOv8-TensorRT#48]
I am trying the run the tensorrt models on jetson agx xavier with jetpack 5.0.2.
Firstly i tried with torch and able to run only yolov8s-seg.engine successfully remaining 2 models are also getting opencv related errors.
 later i tried to load the model with out torch and getting some errors that are related to opencv. I am not understanding whether its related to version mismatching or any another, I am attaching the error log in the following for your reference . Please help me to find the problem and give your suggestions.
Thanks in advance.

/usr/src/YOLOv8-TensorRT# python3 infer-seg-without-torch.py --engine yolov8s-seg.engine --imgs data --show --out-dir outputs 
[03/03/2023-09:19:55] [TRT] [W] Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.0) /opt/opencv/modules/core/src/copy.cpp:254: error: (-215:Assertion failed) channels() == CV_MAT_CN(dtype) in function 'copyTo'

Aborted (core dumped)

**Comment by triple-Mu** [comment]
Please use jetson agx xavier to build engine.
This will avoid the warning
``` text
Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
```
And please also checkout `data` has images.

**Comment by anil-debug** [comment]
I built the engine on jetson only and data folder also contains images

**Comment by triple-Mu** [comment]
> I built the engine on jetson only and data folder also contains images

Could you please run such script:

``` python
import cv2
import numpy as np
from numpy import ndarray
from typing import Union, Tuple, List


def letterbox(im: ndarray,
              new_shape: Union[Tuple, List] = (640, 640),
              color: Union[Tuple, List] = (114, 114, 114)) \
        -> Tuple[ndarray, float, Tuple[float, float]]:
    # Resize and pad image while meeting stride-multiple constraints
    shape = im.shape[:2]  # current shape [height, width]
    if isinstance(new_shape, int):
        new_shape = (new_shape, new_shape)
    # new_shape: [width, height]

    # Scale ratio (new / old)
    r = min(new_shape[0] / shape[1], new_shape[1] / shape[0])
    # Compute padding [width, height]
    new_unpad = int(round(shape[1] * r)), int(round(shape[0] * r))
    dw, dh = new_shape[0] - new_unpad[0], new_shape[1] - new_unpad[
        1]  # wh padding

    dw /= 2  # divide padding into 2 sides
    dh /= 2

    if shape[::-1] != new_unpad:  # resize
        im = cv2.resize(im, new_unpad, interpolation=cv2.INTER_LINEAR)
    top, bottom = int(round(dh - 0.1)), int(round(dh + 0.1))
    left, right = int(round(dw - 0.1)), int(round(dw + 0.1))
    im = cv2.copyMakeBorder(im,
                            top,
                            bottom,
                            left,
                            right,
                            cv2.BORDER_CONSTANT,
                            value=color)  # add border
    return im, r, (dw, dh)


def blob(im: ndarray, return_seg: bool = False) -> Union[ndarray, Tuple]:
    if return_seg:
        seg = im.astype(np.float32) / 255
    im = im.transpose([2, 0, 1])
    im = im[np.newaxis, ...]
    im = np.ascontiguousarray(im).astype(np.float32) / 255
    if return_seg:
        return im, seg
    else:
        return im


if __name__ == '__main__':
    image = cv2.imread('data/bus.jpg')
    image = letterbox(image, (640, 640))[0]
    image = image[:, :, ::-1]
    image = blob(image)
    print(image.shape)

```

**Comment by anil-debug** [comment]
Hi triple-Mu I ran the above script and the output is image shape as below
(1, 3, 640, 640)

**Comment by triple-Mu** [comment]
> Hi triple-Mu I ran the above script and the output is image shape as below (1, 3, 640, 640)

Can you locate the offending line of code?

**Comment by anil-debug** [comment]
while running the model with torch also i was unable to run the inference i added tuple at line 64 in infer-seg.py as below and able to run the inference only yolov8s-seg.engine but in infer-seg-without-torch.py i am unable to debug and find which line is exactly causing problem.
In infer-seg.py line 64 changes as below:
cv2.rectangle(draw, tuple(bbox[:2]), tuple(bbox[2:]), color, 2)

**Comment by triple-Mu** [comment]
> 在使用 torch 运行模型时，我也无法运行推理，我在 infer-seg.py 的第 64 行添加了元组，如下所示，并且只能在 yolov8s-seg.engine 中运行推理，但在 infer-seg-without-torch 中。 py 我无法调试并找到到底是哪一行导致了问题。 在 infer-seg.py 中，第 64 行更改如下： cv2.rectangle(draw, tuple(bbox[:2]), tuple(bbox[2:]), color, 2)
> 
> 今天我再次构建引擎并尝试运行但发生了同样的错误但是这次没有任何警告。
> 
> 在抛出“cv::Exception”实例后调用终止 what(): OpenCV(4.5.0) /opt/opencv/modules/core/src/copy.cpp:254: error: (-215:Assertion failed) channels () == CV_MAT_CN(dtype) 在函数 'copyTo' 中
> 
> 中止（核心转储）


Can you provide a remote connection method so that I can debug the code?
The code runs well in my laptop.
BTW, do you update the code?

**Comment by triple-Mu** [comment]
> while running the model with torch also i was unable to run the inference i added tuple at line 64 in infer-seg.py as below and able to run the inference only yolov8s-seg.engine but in infer-seg-without-torch.py i am unable to debug and find which line is exactly causing problem. In infer-seg.py line 64 changes as below: cv2.rectangle(draw, tuple(bbox[:2]), tuple(bbox[2:]), color, 2)
> 
> today i build the engine again and tried to run but same error occurred but there is no any warning this time.
> 
> terminate called after throwing an instance of 'cv::Exception' what(): OpenCV(4.5.0) /opt/opencv/modules/core/src/copy.cpp:254: error: (-215:Assertion failed) channels() == CV_MAT_CN(dtype) in function 'copyTo'
> 
> Aborted (core dumped)

Can you provide a remote connection method so that I can debug the code?
The code runs well in my laptop.
BTW, do you update the code?

**Comment by anil-debug** [comment]
Hi triple-Mu on my PC i am also able to run with out any errors but on jetson i am getting the problems and on jetson device I am unable to install any remote controlling software due to insufficient memory but i think the problem is with opencv version. I will try to install the ultraviewer for debugging and get back to you, thank you so much for your response

**Comment by triple-Mu** [comment]
I release a new version for jetson.
https://github.com/triple-Mu/YOLOv8-TensorRT/blob/main/docs/Jetson.md

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
