### ISSUE TITLE
convert onnx to engine failed

### ISSUE THREAD

**Issue by fire717** [triple-Mu/YOLOv8-TensorRT#5]
First, I run export.py get yolov8s.onnx, then I run build.py, got error:

> [TensorRT] ERROR: MatMul_276: last dimension of input0 = 16 and second to last dimension of input1 = 1 but must match.

Then I try to use your yolov8s_nms.onnx, got other error:

> ERROR: 3: getPluginCreator could not find plugin: EfficientNMS_TRT version: 1

**Comment by triple-Mu** [comment]
> First, I run export.py get yolov8s.onnx, then I run build.py, got error:
> 
> 
> 
> > [TensorRT] ERROR: MatMul_276: last dimension of input0 = 16 and second to last dimension of input1 = 1 but must match.
> 
> 
> 
> Then I try to use your yolov8s_nms.onnx, got other error:
> 
> 
> 
> > ERROR: 3: getPluginCreator could not find plugin: EfficientNMS_TRT version: 1
What is your tensorrt version？
This repo only support tensorrt8+

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
