### ISSUE TITLE
Exporting with cuda doesn't work on nvidia jetson 

### ISSUE THREAD

**Issue by AlexKanakis5** [triple-Mu/YOLOv8-TensorRT#50]
First of all I should mention that I am using the NVIDIA Jetson Xavier

I am trying to export a the yollov8n.pt to onnx using the following command 

`python3 YOLOv8-TensorRT/export-det.py --weights yolov8n.pt --opset 11 --sim --device cuda:0`

but when using **--device cuda:0** I get the following error: 

>
> YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
> WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> Traceback (most recent call last):
>   File "YOLOv8-TensorRT/export-det.py", line 97, in <module>
>     main(parse_args())
>   File "YOLOv8-TensorRT/export-det.py", line 72, in main
>     torch.onnx.export(
>   File "/home/user/.local/lib/python3.8/site-packages/torch/onnx/__init__.py", line 319, in export
>     return utils.export(model, args, f, export_params, verbose, training,
>   File "/home/user/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 113, in export
>     _export(model, args, f, export_params, verbose, training, input_names, output_names,
>   File "/home/user/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 734, in _export
>     params_dict = torch._C._jit_pass_onnx_deduplicate_initializers(graph, params_dict,
> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument other in method wrapper__equal)

When I remove it, it exports normally. 

After that I build it to tensorrt with the command

` python3 YOLOv8-TensorRT/build.py --weights yolov8n.onnx --device cuda:0`

And I get the exported .engine file.

When I try to use it however:

```
model = YOLO("yolov8n.engine", task='detect')
detection_results = model(frame) #<--- got 'frame' from opencv video capture
```
I now get this error:

> Traceback (most recent call last):
>   File "test_detect.py", line 45, in <module>
>     detection_results = model(frame)
>   File "/home/user/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 99, in __call__
>     return self.predict(source, stream, **kwargs)
>   File "/home/user/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/user/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 218, in predict
>     self.predictor.setup_model(model=self.model, verbose=is_cli)
>   File "/home/user/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 227, in setup_model
>     self.model = AutoBackend(model,
>   File "/home/user/.local/lib/python3.8/site-packages/ultralytics/nn/autobackend.py", line 160, in __init__
>     metadata = json.loads(f.read(meta_len).decode('utf-8'))  # read metadata
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 4: invalid continuation byte

I don't know if the second part is related to this repo but I thought I should mention both. Any insights would be much appreciated.

**Comment by triple-Mu** [comment]
First question:
You'd better export onnx in your pc or laptop or using cpu.
Because jetson's pytorch may behave differently.

Second question:
The onnx and engine you export by my repo is an end2end model.
It contains nms plugin. So I won't work by yolov8 api such as :
``` python
model = YOLO("yolov8n.engine", task='detect')
detection_results = model(frame) #<--- got 'frame' from opencv video capture
````
You'd better try to use `infer-det.py` or `infer-det-without-torch.py`.
I am looking forward for your reply.

**Comment by triple-Mu** [comment]
> First of all I should mention that I am using the NVIDIA Jetson Xavier
> 
> I am trying to export a the yollov8n.pt to onnx using the following command
> 
> `python3 YOLOv8-TensorRT/export-det.py --weights yolov8n.pt --opset 11 --sim --device cuda:0`
> 
> but when using **--device cuda:0** I get the following error:
> 
> > YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > Traceback (most recent call last):
> > File "YOLOv8-TensorRT/export-det.py", line 97, in 
> > main(parse_args())
> > File "YOLOv8-TensorRT/export-det.py", line 72, in main
> > torch.onnx.export(
> > File "/home/user/.local/lib/python3.8/site-packages/torch/onnx/**init**.py", line 319, in export
> > return utils.export(model, args, f, export_params, verbose, training,
> > File "/home/user/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 113, in export
> > _export(model, args, f, export_params, verbose, training, input_names, output_names,
> > File "/home/user/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 734, in _export
> > params_dict = torch._C._jit_pass_onnx_deduplicate_initializers(graph, params_dict,
> > RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument other in method wrapper__equal)
> 
> When I remove it, it exports normally.
> 
> After that I build it to tensorrt with the command
> 
> ` python3 YOLOv8-TensorRT/build.py --weights yolov8n.onnx --device cuda:0`
> 
> And I get the exported .engine file.
> 
> When I try to use it however:
> 
> ```
> model = YOLO("yolov8n.engine", task='detect')
> detection_results = model(frame) #<--- got 'frame' from opencv video capture
> ```
> 
> I now get this error:
> 
> > Traceback (most recent call last):
> > File "test_detect.py", line 45, in 
> > detection_results = model(frame)
> > File "/home/user/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 99, in **call**
> > return self.predict(source, stream, **kwargs)
> > File "/home/user/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
> > return func(*args, **kwargs)
> > File "/home/user/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 218, in predict
> > self.predictor.setup_model(model=self.model, verbose=is_cli)
> > File "/home/user/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 227, in setup_model
> > self.model = AutoBackend(model,
> > File "/home/user/.local/lib/python3.8/site-packages/ultralytics/nn/autobackend.py", line 160, in **init**
> > metadata = json.loads(f.read(meta_len).decode('utf-8'))  # read metadata
> > UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 4: invalid continuation byte
> 
> I don't know if the second part is related to this repo but I thought I should mention both. Any insights would be much appreciated.

First question:
You'd better export onnx in your pc or laptop or using cpu.
Because jetson's pytorch may behave differently.

Second question:
The onnx and engine you export by my repo is an end2end model.
It contains nms plugin. So It won't work by yolov8 api such as :
``` python
model = YOLO("yolov8n.engine", task='detect')
detection_results = model(frame) #<--- got 'frame' from opencv video capture
````
You'd better try to use `infer-det.py` or `infer-det-without-torch.py`.
I am looking forward for your reply.

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!

**Comment by XhHello** [comment]
> First of all I should mention that I am using the NVIDIA Jetson Xavier
> 
> I am trying to export a the yollov8n.pt to onnx using the following command
> 
> `python3 YOLOv8-TensorRT/export-det.py --weights yolov8n.pt --opset 11 --sim --device cuda:0`
> 
> but when using **--device cuda:0** I get the following error:
> 
> > YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > Traceback (most recent call last):
> > File "YOLOv8-TensorRT/export-det.py", line 97, in 
> > main(parse_args())
> > File "YOLOv8-TensorRT/export-det.py", line 72, in main
> > torch.onnx.export(
> > File "/home/user/.local/lib/python3.8/site-packages/torch/onnx/**init**.py", line 319, in export
> > return utils.export(model, args, f, export_params, verbose, training,
> > File "/home/user/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 113, in export
> > _export(model, args, f, export_params, verbose, training, input_names, output_names,
> > File "/home/user/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 734, in _export
> > params_dict = torch._C._jit_pass_onnx_deduplicate_initializers(graph, params_dict,
> > RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument other in method wrapper__equal)
> 
> When I remove it, it exports normally.
> 
> After that I build it to tensorrt with the command
> 
> ` python3 YOLOv8-TensorRT/build.py --weights yolov8n.onnx --device cuda:0`
> 
> And I get the exported .engine file.
> 
> When I try to use it however:
> 
> ```
> model = YOLO("yolov8n.engine", task='detect')
> detection_results = model(frame) #<--- got 'frame' from opencv video capture
> ```
> 
> I now get this error:
> 
> > Traceback (most recent call last):
> > File "test_detect.py", line 45, in 
> > detection_results = model(frame)
> > File "/home/user/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 99, in **call**
> > return self.predict(source, stream, **kwargs)
> > File "/home/user/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
> > return func(*args, **kwargs)
> > File "/home/user/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 218, in predict
> > self.predictor.setup_model(model=self.model, verbose=is_cli)
> > File "/home/user/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 227, in setup_model
> > self.model = AutoBackend(model,
> > File "/home/user/.local/lib/python3.8/site-packages/ultralytics/nn/autobackend.py", line 160, in **init**
> > metadata = json.loads(f.read(meta_len).decode('utf-8'))  # read metadata
> > UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 4: invalid continuation byte
> 
> I don't know if the second part is related to this repo but I thought I should mention both. Any insights would be much appreciated.

I also deployed on Jetson and encountered the same problem as you. How did you solve it? Thank you

**Comment by XhHello** [comment]
> First of all I should mention that I am using the NVIDIA Jetson Xavier
> 
> I am trying to export a the yollov8n.pt to onnx using the following command
> 
> `python3 YOLOv8-TensorRT/export-det.py --weights yolov8n.pt --opset 11 --sim --device cuda:0`
> 
> but when using **--device cuda:0** I get the following error:
> 
> > YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > WARNING: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
> > Traceback (most recent call last):
> > File "YOLOv8-TensorRT/export-det.py", line 97, in 
> > main(parse_args())
> > File "YOLOv8-TensorRT/export-det.py", line 72, in main
> > torch.onnx.export(
> > File "/home/user/.local/lib/python3.8/site-packages/torch/onnx/**init**.py", line 319, in export
> > return utils.export(model, args, f, export_params, verbose, training,
> > File "/home/user/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 113, in export
> > _export(model, args, f, export_params, verbose, training, input_names, output_names,
> > File "/home/user/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 734, in _export
> > params_dict = torch._C._jit_pass_onnx_deduplicate_initializers(graph, params_dict,
> > RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument other in method wrapper__equal)
> 
> When I remove it, it exports normally.
> 
> After that I build it to tensorrt with the command
> 
> ` python3 YOLOv8-TensorRT/build.py --weights yolov8n.onnx --device cuda:0`
> 
> And I get the exported .engine file.
> 
> When I try to use it however:
> 
> ```
> model = YOLO("yolov8n.engine", task='detect')
> detection_results = model(frame) #<--- got 'frame' from opencv video capture
> ```
> 
> I now get this error:
> 
> > Traceback (most recent call last):
> > File "test_detect.py", line 45, in 
> > detection_results = model(frame)
> > File "/home/user/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 99, in **call**
> > return self.predict(source, stream, **kwargs)
> > File "/home/user/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
> > return func(*args, **kwargs)
> > File "/home/user/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 218, in predict
> > self.predictor.setup_model(model=self.model, verbose=is_cli)
> > File "/home/user/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 227, in setup_model
> > self.model = AutoBackend(model,
> > File "/home/user/.local/lib/python3.8/site-packages/ultralytics/nn/autobackend.py", line 160, in **init**
> > metadata = json.loads(f.read(meta_len).decode('utf-8'))  # read metadata
> > UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 4: invalid continuation byte
> 
> I don't know if the second part is related to this repo but I thought I should mention both. Any insights would be much appreciated.

First question:
You can change the versions of Torch and Torchvision.
My environment is installed on Jetson:
When reporting an error, in the Conda environment, torch=1.12.1 and torch vision=0.13.0 were changed to torch=2.0.0 and torch vision=0.15.1, which resolved this error.

Second question:
The onnx and engine you should export by yolov8 api such as :
model = YOLO("yolov8n.engine", task='detect') detection_results = model(frame) #<--- got 'frame' from opencv video capture

If using trtexec to export the engine, this error message will appear
