### ISSUE TITLE
a Warrning

### ISSUE THREAD

**Issue by AndyHUI711** [triple-Mu/YOLOv8-TensorRT#54]
The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.

**Comment by triple-Mu** [comment]
If you do not use dynamic shape, there will not be affected in any way.

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
