### ISSUE TITLE
error label

### ISSUE THREAD

**Issue by dadada-123** [triple-Mu/YOLOv8-TensorRT#57]
Hello, when i use yolov8.exe to detect object, the object have two objs with same rect but different label and scores, what is the reason? I use pytorch .pt file to detect only have one obj.
![image](https://user-images.githubusercontent.com/93700580/228863974-4055d98e-ec5e-4ea5-8c4d-cdd7eb35aec8.png)

**Comment by dadada-123** [comment]
> 

End2end

**Comment by triple-Mu** [comment]
> > 
> 
> End2end

Could you please show the detection result picture?

**Comment by dadada-123** [comment]
please ignore picture label
![image](https://user-images.githubusercontent.com/93700580/228871397-9147081a-0d5c-434f-9028-d180a84e0ad8.png)
![image](https://user-images.githubusercontent.com/93700580/228871498-f68f2d86-58c6-461c-9a3d-e83fb02a3a76.png)

**Comment by triple-Mu** [comment]
How about pytorch result?

**Comment by dadada-123** [comment]
same with label 0
![image](https://user-images.githubusercontent.com/93700580/228873763-f73cdeaa-48b6-4702-a0f1-4a3fad819801.png)
![image](https://user-images.githubusercontent.com/93700580/228873833-e74ffa18-c6a4-4273-8316-c1deba024804.png)

**Comment by triple-Mu** [comment]
> same with label 0 ![image](https://user-images.githubusercontent.com/93700580/228873763-f73cdeaa-48b6-4702-a0f1-4a3fad819801.png) ![image](https://user-images.githubusercontent.com/93700580/228873833-e74ffa18-c6a4-4273-8316-c1deba024804.png)

How about conf threshold?

**Comment by dadada-123** [comment]
both 0.1

**Comment by triple-Mu** [comment]
> 

What's your envs? Could you list all?  How could I reproduce your result?

**Comment by dadada-123** [comment]
When I capture a small portion of the image，the result change
![image](https://user-images.githubusercontent.com/93700580/228880666-883d6572-4d00-4195-96de-b996e9585ed3.png)

**Comment by dadada-123** [comment]
你好，关于出现错误标签这个问题能帮我看下如何处理吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "triple-Mu/YOLOv8-TensorRT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月30日(星期四) 晚上10:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [triple-Mu/YOLOv8-TensorRT] error label (Issue #57)





   
What's your envs? Could you list all?  How could I reproduce your result?

**Comment by triple-Mu** [comment]
> 你好，关于出现错误标签这个问题能帮我看下如何处理吗
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 
> 发件人:                                                                                                                        "triple-Mu/YOLOv8-TensorRT"                                                                                    ***@***.***&gt;;
> 
> 发送时间:&nbsp;2023年3月30日(星期四) 晚上10:55
> 
> ***@***.***&gt;;
> 
> ***@***.******@***.***&gt;;
> 
> 主题:&nbsp;Re: [triple-Mu/YOLOv8-TensorRT] error label (Issue #57)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>    
> 
> What's your envs? Could you list all?  How could I reproduce your result?
> 
>  
> 
> —
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

您的这个问题我无法复现，因为我没有在win平台测试过。。

**Comment by dadada-123** [comment]
我给您提供.pt文件，你能在linux下帮我测试下是正常的不




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "triple-Mu/YOLOv8-TensorRT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月2日(星期天) 晚上6:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [triple-Mu/YOLOv8-TensorRT] error label (Issue #57)





  
你好，关于出现错误标签这个问题能帮我看下如何处理吗
 
------------------&nbsp;原始邮件&nbsp;------------------
 
发件人:                                                                                                                        "triple-Mu/YOLOv8-TensorRT"                                                                                    @.***&gt;;
 
发送时间:&nbsp;2023年3月30日(星期四) 晚上10:55
 
@.***&gt;;
 
@.@.&gt;;
 
主题:&nbsp;Re: [triple-Mu/YOLOv8-TensorRT] error label (Issue #57)
 
What's your envs? Could you list all?  How could I reproduce your result?
 
—
 
Reply to this email directly, view it on GitHub, or unsubscribe.
 
You are receiving this because you authored the thread.Message ID: @.***&gt;
  
您的这个问题我无法复现，因为我没有在win平台测试过。。

**Comment by triple-Mu** [comment]
> 我给您提供.pt文件，你能在linux下帮我测试下是正常的不
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "triple-Mu/YOLOv8-TensorRT" ***@***.***&gt;; 发送时间:&nbsp;2023年4月2日(星期天) 晚上6:38 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [triple-Mu/YOLOv8-TensorRT] error label (Issue #57) 你好，关于出现错误标签这个问题能帮我看下如何处理吗
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "triple-Mu/YOLOv8-TensorRT" @.***&gt;; 发送时间:&nbsp;2023年3月30日(星期四) 晚上10:55 @.***&gt;; @.@.&gt;; 主题:&nbsp;Re: [triple-Mu/YOLOv8-TensorRT] error label (Issue #57) What's your envs? Could you list all? How could I reproduce your result? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 您的这个问题我无法复现，因为我没有在win平台测试过。。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
那您发我吧 gpu@163.com 最好测试图片和类别名字也发我

**Comment by dadada-123** [comment]
我在导出onnx的时候提示警告，有没有可能是这个原因造成的，能不能将上次你转的onnx发我测试下。

**Comment by triple-Mu** [comment]
> 我在导出onnx的时候提示警告，有没有可能是这个原因造成的，能不能将上次你转的onnx发我测试下。
是这个吗？
链接: https://pan.baidu.com/s/1tXe8I5G29IIfUv9gzPxpTw 提取码: uzu7 
不好意思哈，才想起来您的问题

**Comment by henry-lee-97** [comment]
> Hello, when i use yolov8.exe to detect object, the object have two objs with same rect but different label and scores, what is the reason? I use pytorch .pt file to detect only have one obj. ![image](https://user-images.githubusercontent.com/93700580/228863974-4055d98e-ec5e-4ea5-8c4d-cdd7eb35aec8.png)

+1

**Comment by triple-Mu** [comment]
> > Hello, when i use yolov8.exe to detect object, the object have two objs with same rect but different label and scores, what is the reason? I use pytorch .pt file to detect only have one obj. ![image](https://user-images.githubusercontent.com/93700580/228863974-4055d98e-ec5e-4ea5-8c4d-cdd7eb35aec8.png)
> 
> 
> 
> +1

I can not reproduce in linux.
So could you try linux or wsl2？

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
