### ISSUE TITLE
infer with c++

### ISSUE THREAD

**Issue by Freeman-Cai** [triple-Mu/YOLOv8-TensorRT#58]
您好，我在jetson xaviewer上使用c++推理时，总是报出core dumped的错误，请问应该怎么解决呢

**Comment by triple-Mu** [comment]
可以提供如何导出和启动程序的命令吗？是否可以给出详细的日志？

**Comment by Freeman-Cai** [comment]
我先在自己服务器上，用export-det生成onnx文件，然后按照jetson.md中给出的示例代码生成engine文件。在执行“./yolov8 yolov8s.engine data/bus.jpg”时，程序输出如下：
“
model warmup 10 times 
Segmentation fault (core dumped)
”

**Comment by triple-Mu** [comment]
您的jetpack版本，cuda cudnn tensorrt版本呢？还有就是您的yolov8执行文件是否拷贝到根目录

**Comment by Freeman-Cai** [comment]
yolov8执行文件我拷贝到根目录了。具体配置如下：cuda11.4,tensorrt8.4.1.5,cudnn8401,jetpack5.0.2

**Comment by triple-Mu** [comment]
> 

你尝试在 c++ 代码里可能出现问题的行增加点打印吧，现在需要定位到哪行出问题了

**Comment by immohan6598** [comment]
Hi, 
I am trying to run it in the docker container facing the same issue 
segmentation fault

**Comment by triple-Mu** [comment]
> Hi, 
> 
> I am trying to run it in the docker container facing the same issue 
> 
> segmentation fault
> 
> 

Can you locate the error line number？

**Comment by mohanrobro** [comment]
![Screenshot from 2023-04-05 16-33-05](https://user-images.githubusercontent.com/64127196/230062321-5e5e49fb-3b9f-49f8-a603-adf123fb5ef9.png)

**Comment by triple-Mu** [comment]
> ![Screenshot from 2023-04-05 16-33-05](https://user-images.githubusercontent.com/64127196/230062321-5e5e49fb-3b9f-49f8-a603-adf123fb5ef9.png)

What's your trt cuda cudnn version?

**Comment by triple-Mu** [comment]
> ![Screenshot from 2023-04-05 16-33-05](https://user-images.githubusercontent.com/64127196/230062321-5e5e49fb-3b9f-49f8-a603-adf123fb5ef9.png)

Please make sure you engine path is right. Maybe you can use abs path

**Comment by mohanrobro** [comment]
I have cudnn 8.8.1 cuda 11.7 tensorrt 8.5.1

**Comment by triple-Mu** [comment]
> I have cudnn 8.8.1 cuda 11.7 tensorrt 8.5.1

It seems that you load a wrong engine path.

**Comment by mohanrobro** [comment]
![Screenshot from 2023-04-05 18-50-44](https://user-images.githubusercontent.com/64127196/230093136-b80526fc-0da8-44aa-ab1d-2a8bc4e64c5b.png)

**Comment by mohanrobro** [comment]
when i export model it is saying TensorRT: starting export with TensorRT 8.4.3.1...
this version is not same
is the error is due to this one?

**Comment by triple-Mu** [comment]
> when i export model it is saying TensorRT: starting export with TensorRT 8.4.3.1... this version is not same is the error is due to this one?

You should install tensorrt with the same version.

**Comment by immohan6598** [comment]
Sorry for the late reply.
I used the same version also still the issue is coming.
the issue is related to .trt and .engine

**Comment by triple-Mu** [comment]
Could you use python to infer?

**Comment by triple-Mu** [comment]
> Sorry for the late reply. I used the same version also still the issue is coming. the issue is related to .trt and .engine

Could you use python to infer?

**Comment by immohan6598** [comment]
Thanks, the python code works fine. Great work.
Do you have a plan to fix the c++ code?

**Comment by liang-zijian** [comment]
yolov8-seg.hpp中的338行函数postprocessing中，如果画面中检测不到物体，mask就会是empty，此时会导致core dump
![](https://s2.loli.net/2023/04/17/RhiqnAL9XVGblPQ.png)
添加了一个判断之后就能解决了
```C++
void YOLOv8_seg::postprocess(std::vector<Object>& objs,
	float score_thres,
	float iou_thres,
	int topk,
	int seg_channels,
	int seg_h,
	int seg_w
)
{
	auto input_h = this->input_bindings[0].dims.d[2];
	auto input_w = this->input_bindings[0].dims.d[3];
	auto num_anchors = this->output_bindings[0].dims.d[1];
	auto num_channels = this->output_bindings[0].dims.d[2];
	auto& dw = this->pparam.dw;
	auto& dh = this->pparam.dh;
	auto& width = this->pparam.width;
	auto& height = this->pparam.height;
	auto& ratio = this->pparam.ratio;
	auto* output = static_cast<float*>(this->host_ptrs[0]);
	cv::Mat protos = cv::Mat(seg_channels, seg_h * seg_w, CV_32F,
		static_cast<float*>(this->host_ptrs[1]));

	std::vector<int> labels;
	std::vector<float> scores;
	std::vector<cv::Rect> bboxes;
	std::vector<cv::Mat> mask_confs;
	std::vector<int> indices;
	for (int i = 0; i < num_anchors; i++)
	{
		float* ptr = output + i * num_channels;
		float score = *(ptr + 4);
		if (score > score_thres)
		{
			float x0 = *ptr++ - dw;
			float y0 = *ptr++ - dh;
			float x1 = *ptr++ - dw;
			float y1 = *ptr++ - dh;

			x0 = clamp(x0 * ratio, 0.f, width);
			y0 = clamp(y0 * ratio, 0.f, height);
			x1 = clamp(x1 * ratio, 0.f, width);
			y1 = clamp(y1 * ratio, 0.f, height);

			int label = *(++ptr);
			cv::Mat mask_conf = cv::Mat(1, seg_channels, CV_32F, ++ptr);
			mask_confs.push_back(mask_conf);
			labels.push_back(label);
			scores.push_back(score);
			bboxes.push_back(cv::Rect_<float>(x0, y0, x1 - x0, y1 - y0));

		}
	}

#if defined(BATCHED_NMS)
	cv::dnn::NMSBoxesBatched(
		bboxes,
		scores,
		labels,
		score_thres,
		iou_thres,
		indices
	);
#else
	cv::dnn::NMSBoxes(
		bboxes,
		scores,
		score_thres,
		iou_thres,
		indices
	);
#endif
	cv::Mat masks;
	int cnt = 0;
	for (auto& i : indices)
	{
		if (cnt >= topk)
		{
			break;
		}
		cv::Rect tmp = bboxes[i];
		Object obj;
		obj.label = labels[i];
		obj.rect = tmp;
		obj.prob = scores[i];
		masks.push_back(mask_confs[i]);
		objs.push_back(obj);
		cnt += 1;
	}
	if(masks.empty()){
		//mask is empty
	}
	else{
		cv::Mat matmulRes = (masks * protos).t();
		cv::Mat maskMat = matmulRes.reshape(indices.size(), { seg_w, seg_h });
		std::vector<cv::Mat> maskChannels;
		cv::split(maskMat, maskChannels);
		int scale_dw = dw / input_w * seg_w;
		int scale_dh = dh / input_h * seg_h;
		cv::Rect roi(
			scale_dw,
			scale_dh,
			seg_w - 2 * scale_dw,
			seg_h - 2 * scale_dh);
		for (int i = 0; i < indices.size(); i++)
		{
			cv::Mat dest, mask;
			cv::exp(-maskChannels[i], dest);
			dest = 1.0 / (1.0 + dest);
			dest = dest(roi);
			cv::resize(
				dest,
				mask,
				cv::Size((int)width, (int)height),
				cv::INTER_LINEAR
			);
			objs[i].boxMask = mask(objs[i].rect) > 0.5f;
		}
	}
}
```
希望能帮到您😄

**Comment by triple-Mu** [comment]
> yolov8-seg.hpp中的338行函数postprocessing中，如果画面中检测不到物体，mask就会是empty，此时会导致core dump ![](https://camo.githubusercontent.com/bb1593fbd397226b2197f071e5806b53f18c8cb6cd3eb7a0ed649028bcde7b69/68747470733a2f2f73322e6c6f6c692e6e65742f323032332f30342f31372f526869716e414c39585647626c50512e706e67) 添加了一个判断之后就能解决了
> 
> ```c++
> void YOLOv8_seg::postprocess(std::vector<Object>& objs,
> 	float score_thres,
> 	float iou_thres,
> 	int topk,
> 	int seg_channels,
> 	int seg_h,
> 	int seg_w
> )
> {
> 	auto input_h = this->input_bindings[0].dims.d[2];
> 	auto input_w = this->input_bindings[0].dims.d[3];
> 	auto num_anchors = this->output_bindings[0].dims.d[1];
> 	auto num_channels = this->output_bindings[0].dims.d[2];
> 	auto& dw = this->pparam.dw;
> 	auto& dh = this->pparam.dh;
> 	auto& width = this->pparam.width;
> 	auto& height = this->pparam.height;
> 	auto& ratio = this->pparam.ratio;
> 	auto* output = static_cast<float*>(this->host_ptrs[0]);
> 	cv::Mat protos = cv::Mat(seg_channels, seg_h * seg_w, CV_32F,
> 		static_cast<float*>(this->host_ptrs[1]));
> 
> 	std::vector<int> labels;
> 	std::vector<float> scores;
> 	std::vector<cv::Rect> bboxes;
> 	std::vector<cv::Mat> mask_confs;
> 	std::vector<int> indices;
> 	for (int i = 0; i < num_anchors; i++)
> 	{
> 		float* ptr = output + i * num_channels;
> 		float score = *(ptr + 4);
> 		if (score > score_thres)
> 		{
> 			float x0 = *ptr++ - dw;
> 			float y0 = *ptr++ - dh;
> 			float x1 = *ptr++ - dw;
> 			float y1 = *ptr++ - dh;
> 
> 			x0 = clamp(x0 * ratio, 0.f, width);
> 			y0 = clamp(y0 * ratio, 0.f, height);
> 			x1 = clamp(x1 * ratio, 0.f, width);
> 			y1 = clamp(y1 * ratio, 0.f, height);
> 
> 			int label = *(++ptr);
> 			cv::Mat mask_conf = cv::Mat(1, seg_channels, CV_32F, ++ptr);
> 			mask_confs.push_back(mask_conf);
> 			labels.push_back(label);
> 			scores.push_back(score);
> 			bboxes.push_back(cv::Rect_<float>(x0, y0, x1 - x0, y1 - y0));
> 
> 		}
> 	}
> 
> #if defined(BATCHED_NMS)
> 	cv::dnn::NMSBoxesBatched(
> 		bboxes,
> 		scores,
> 		labels,
> 		score_thres,
> 		iou_thres,
> 		indices
> 	);
> #else
> 	cv::dnn::NMSBoxes(
> 		bboxes,
> 		scores,
> 		score_thres,
> 		iou_thres,
> 		indices
> 	);
> #endif
> 	cv::Mat masks;
> 	int cnt = 0;
> 	for (auto& i : indices)
> 	{
> 		if (cnt >= topk)
> 		{
> 			break;
> 		}
> 		cv::Rect tmp = bboxes[i];
> 		Object obj;
> 		obj.label = labels[i];
> 		obj.rect = tmp;
> 		obj.prob = scores[i];
> 		masks.push_back(mask_confs[i]);
> 		objs.push_back(obj);
> 		cnt += 1;
> 	}
> 	if(masks.empty()){
> 		//mask is empty
> 	}
> 	else{
> 		cv::Mat matmulRes = (masks * protos).t();
> 		cv::Mat maskMat = matmulRes.reshape(indices.size(), { seg_w, seg_h });
> 		std::vector<cv::Mat> maskChannels;
> 		cv::split(maskMat, maskChannels);
> 		int scale_dw = dw / input_w * seg_w;
> 		int scale_dh = dh / input_h * seg_h;
> 		cv::Rect roi(
> 			scale_dw,
> 			scale_dh,
> 			seg_w - 2 * scale_dw,
> 			seg_h - 2 * scale_dh);
> 		for (int i = 0; i < indices.size(); i++)
> 		{
> 			cv::Mat dest, mask;
> 			cv::exp(-maskChannels[i], dest);
> 			dest = 1.0 / (1.0 + dest);
> 			dest = dest(roi);
> 			cv::resize(
> 				dest,
> 				mask,
> 				cv::Size((int)width, (int)height),
> 				cv::INTER_LINEAR
> 			);
> 			objs[i].boxMask = mask(objs[i].rect) > 0.5f;
> 		}
> 	}
> }
> ```
> 
> 希望能帮到您smile

可以提 PR 吗？非常感谢您发现问题！

**Comment by triple-Mu** [comment]
Thanks @liang-zijian.
BTW issue closed, feel free to reopen it if you have further questions. Thanks!

**Comment by yongkang-cienet** [comment]
> 我先在自己服务器上，用export-det生成onnx文件，然后按照jetson.md中给出的示例代码生成engine文件。在执行“./yolov8 yolov8s.engine data/bus.jpg”时，程序输出如下： “ model warmup 10 times Segmentation fault (core dumped) ”

请问现在问题有解决吗？
