### ISSUE TITLE
YOLOv8-Tensorrt on Jetson

### ISSUE THREAD

**Issue by dilarahisar** [triple-Mu/YOLOv8-TensorRT#61]
Hi, i am using Jetson Nano
I've run the yolov8 model with the following versions before. Are these versions suitable for your jetson-tenorrt tutorial?
python 3.8 for yolov8
pytorch 1.11.0
torchvision 0.12.0

**Comment by triple-Mu** [comment]
You can find more info in docs/jetson.md

**Comment by dilarahisar** [comment]
I've read this but I couldn't see the version information about what I asked

**Comment by triple-Mu** [comment]
> I've read this but I couldn't see the version information about what I asked
> 
> 

The python package version is ok. But it will be slow. Suggest you using c++.

**Comment by Addoxx** [comment]
Hey! I get an assertion error when I try to run inference. 
 
 Traceback (most recent call last):
  File "infer-det.py", line 82, in <module>
    main(args)
  File "infer-det.py", line 39, in main
    bboxes, scores, labels = det_postprocess(data)
  File "YOLOv8-TensorRT/models/torch_utils.py", line 37, in det_postprocess
    assert len(data) == 4
AssertionError

I am using a Jetson Orin with python 3.8, torch 1.12.0a0+2c916ef.nv22.3, torchvision 0.13.0, ultralytics 8.0.62. 

Please help

**Comment by triple-Mu** [comment]
> Hey! I get an assertion error when I try to run inference.
> 
> Traceback (most recent call last): File "infer-det.py", line 82, in main(args) File "infer-det.py", line 39, in main bboxes, scores, labels = det_postprocess(data) File "YOLOv8-TensorRT/models/torch_utils.py", line 37, in det_postprocess assert len(data) == 4 AssertionError
> 
> I am using a Jetson Orin with python 3.8, torch 1.12.0a0+2c916ef.nv22.3, torchvision 0.13.0, ultralytics 8.0.62.
> 
> Please help

It seems you do not export onnx with this repo.
``` shell
python3 export-det.py \
--weights yolov8s.pt \
--iou-thres 0.65 \
--conf-thres 0.25 \
--topk 100 \
--opset 11 \
--sim \
--input-shape 1 3 640 640 \
--device cuda:0

python3 build.py \
--weights yolov8s.onnx \
--iou-thres 0.65 \
--conf-thres 0.25 \
--topk 100 \
--fp16  \
--device cuda:0
```
Just using such command you will get a right engine.

**Comment by Addoxx** [comment]
Thanks for your quick turnaround on the issue. You are right, I was using an engine file exported from trtexec tool. However, when I tried to export onnx as you mentioned earlier, I get a Runtime error. 

Traceback (most recent call last):
  File "export-det.py", line 97, in <module>
    main(parse_args())
  File "export-det.py", line 72, in main
    torch.onnx.export(
  File "/home/gaardtech/.local/lib/python3.8/site-packages/torch/onnx/__init__.py", line 319, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/gaardtech/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 113, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/gaardtech/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 734, in _export
    params_dict = torch._C._jit_pass_onnx_deduplicate_initializers(graph, params_dict,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument other in method wrapper__equal)

**Comment by Addoxx** [comment]
Thanks for your quick turnaround on the issue. You are right, I was using an engine file exported from trtexec tool. However, when I tried to export onnx as you mentioned earlier, I get a Runtime error.

Traceback (most recent call last):
File "export-det.py", line 97, in
main(parse_args())
File "export-det.py", line 72, in main
torch.onnx.export(
File "/.local/lib/python3.8/site-packages/torch/onnx/init.py", line 319, in export
return utils.export(model, args, f, export_params, verbose, training,
File "/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 113, in export
_export(model, args, f, export_params, verbose, training, input_names, output_names,
File "/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 734, in _export
params_dict = torch._C._jit_pass_onnx_deduplicate_initializers(graph, params_dict,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument other in method wrapper__equal)

**Comment by triple-Mu** [comment]
> Thanks for your quick turnaround on the issue. You are right, I was using an engine file exported from trtexec tool. However, when I tried to export onnx as you mentioned earlier, I get a Runtime error.
> 
> 
> 
> Traceback (most recent call last):
> 
> File "export-det.py", line 97, in
> 
> main(parse_args())
> 
> File "export-det.py", line 72, in main
> 
> torch.onnx.export(
> 
> File "/.local/lib/python3.8/site-packages/torch/onnx/init.py", line 319, in export
> 
> return utils.export(model, args, f, export_params, verbose, training,
> 
> File "/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 113, in export
> 
> _export(model, args, f, export_params, verbose, training, input_names, output_names,
> 
> File "/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 734, in _export
> 
> params_dict = torch._C._jit_pass_onnx_deduplicate_initializers(graph, params_dict,
> 
> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument other in method wrapper__equal)

Do you export on jetson？
Suggest you export onnx on pc and copy onnx to jetson.

**Comment by Addoxx** [comment]
Yes I am exporting on Jetson. I got rid of the repo and cloned it again and it fixed the issue. I must have changed the source code so as to run the inference on webcam, causing the issue.

**Comment by triple-Mu** [comment]
> Yes I am exporting on Jetson. I got rid of the repo and cloned it again and it fixed the issue. I must have changed the source code so as to run the inference on webcam, causing the issue. 

Do you work well now？

**Comment by Addoxx** [comment]
Yes I am able to run inference successfully on images. I want to run inference using my webcam, could you please direct me on how to do that?
