### ISSUE TITLE
Engine output data has wrong shape when infering (infer-det.py)

### ISSUE THREAD

**Issue by schelmi1** [triple-Mu/YOLOv8-TensorRT#65]
Hi, i'am trying to infer with a tensorrt engine with **infer-det.py** but the engine output cant be postprocessed because it has the wrong shape.

torch_utils.py line 36
```python
 def det_postprocess(data: Tuple[Tensor, Tensor, Tensor, Tensor]):
    assert len(data) == 4
```

unfortunately the engine output shape is
**torch.Size([1, 9, 8400])**

infer-det.py line 37
```python
  # inference
  data = Engine(tensor)
  print(data.shape) #< added by me
```

Happens with both png and jpg images.
YOLOv8 model was exported as onnx using ultralytics.YOLO export.
Then converted to .engine with TensorRT trtexec.

environment:
Python 3.10.6
CUDA11.7
PyTorch '2.0.0+cu117'
TensorRT8.4.15 (Python tensorrt installed with python wheels in TensorRT)
Win 10

Any idea what this is causing?
I really want to try it because i'am running into performance issuse with my custom trained yolov8 models.

**edit:**
also happens with **infer-det-without-torch.py**, exact same error

**edit2:**
got it working with building the engine this way:
https://github.com/triple-Mu/YOLOv8-TensorRT/blob/main/docs/API-Build.md

**Comment by triple-Mu** [comment]
You should export onnx using export-det.py. And then using build.py for building engine.
If you get engine by orin yolov8 repo. if can just try csrc/detect/norm about cpp code.
