### ISSUE TITLE
An error occurs when converting onnx -> tflite

### ISSUE THREAD

**Issue by alxvmr** [triple-Mu/YOLOv8-TensorRT#66]
Hi! I converted yolov8n.pt to .onnx. Next, when converting to .tflite, an error occurs:

`ValueError: Shape must be at least rank 2 but is rank 1 for '{{node onnx_tf_prefix_/model.22/MatMul}} = BatchMatMulV2[T=DT_FLOAT, adj_x=false, adj_y=false](onnx_tf_prefix_/model.22/Softmax , onnx_tf_prefix_Constant_268)' with input shapes: [1,4,33600,16], [16].`

Translation from .pt to .onnx:
```
python3 export-det.py\
--weightsyolov8_best.pt \
--iou-thres 0.65 \
--conf-thres 0.25 \
--topk 20 \
--opset 17 \
--input-shape 1 3 1280 1280 \
--device cuda:0
```

Translation from .onnx:
`onnx-tf convert -i "yolov8_best.onnx" -o "yolov8_nms"`

**Comment by triple-Mu** [comment]
> Hi! I converted yolov8n.pt to .onnx. Next, when converting to .tflite, an error occurs:
> 
> 
> 
> `ValueError: Shape must be at least rank 2 but is rank 1 for '{{node onnx_tf_prefix_/model.22/MatMul}} = BatchMatMulV2[T=DT_FLOAT, adj_x=false, adj_y=false](onnx_tf_prefix_/model.22/Softmax , onnx_tf_prefix_Constant_268)' with input shapes: [1,4,33600,16], [16].`
> 
> 
> 
> Translation from .pt to .onnx:
> 
> ```
> 
> python3 export-det.py\
> 
> --weightsyolov8_best.pt \
> 
> --iou-thres 0.65 \
> 
> --conf-thres 0.25 \
> 
> --topk 20 \
> 
> --opset 17 \
> 
> --input-shape 1 3 1280 1280 \
> 
> --device cuda:0
> 
> ```
> 
> 
> 
> Translation from .onnx:
> 
> `onnx-tf convert -i "yolov8_best.onnx" -o "yolov8_nms"`


My repo export nms just for tensorrt.
So it does not work for tflite.
