### ISSUE TITLE
TensorRT Pose Infer error

### ISSUE THREAD

**Issue by TianchenFu** [triple-Mu/YOLOv8-TensorRT#71]
Hi, I was running the pose estimation code in a docker container provided by Nvidia `nvcr.io/nvidia/tensorrt:22.07-py3`
CUDA: 11.7
cuDNN: 8.4.1
TensorRT : 8.4.1

when I try to run the infer, error occur 

``` 
ERROR: 1: [stdArchiveReader.cpp::StdArchiveReader::30] Error Code 1: Serialization (Serialization assertion magicTagRead == kMAGIC_TAG failed.Magic tag does not match)
ERROR: 4: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)
Segmentation fault (core dumped)
```

**Comment by triple-Mu** [comment]
Do you export engine in docker too?

**Comment by TianchenFu** [comment]
yes

**Comment by triple-Mu** [comment]
> yes

ONNX2TensorRT？

**Comment by triple-Mu** [comment]
It may cause some bug. Could you please using onnx2tensorrt.

**Comment by TianchenFu** [comment]
TY, so can I still use the onnx file create by the python code in `Pose.md`

**Comment by TianchenFu** [comment]
Thanks! it worked
