### ISSUE TITLE
为什么 csrc/detect/end2end 我跑不起来例子，很多头文件都没有!

### ISSUE THREAD

**Issue by fengshangren** [triple-Mu/YOLOv8-TensorRT#74]
#include <unistd.h>
#include "NvInfer.h"

#include "NvInferPlugin.h"

这三个头文件，在哪弄，我找不到啊，一直报错

**Comment by fengshangren** [comment]
triple-Mu/ncnn-examples/blob/main/cpp/yolov8/src/triplemu-yolov8.cpp

这个推理源码和csrc/detect/end2end的不一样啊，我应该用哪个来做目标检测

**Comment by triple-Mu** [comment]
这是tensorrt库提供的。您可以去官网查看安装方法。如果是ncnn的话本仓库还不支持。。

**Comment by fengshangren** [comment]
> 这是tensorrt库提供的。您可以去官网查看安装方法。如果是ncnn的话本库还不支持。。

triple-Mu/ncnn-examples/blob/main/cpp/yolov8/src/triplemu-yolov8.cpp 但是你这个示例是用的NCNN啊，这也是可以用来推理yolov8的吧

**Comment by triple-Mu** [comment]
> > 这是tensorrt库提供的。您可以去官网查看安装方法。如果是ncnn的话本库还不支持。。
> 
> 
> 
> triple-Mu/ncnn-examples/blob/main/cpp/yolov8/src/triplemu-yolov8.cpp 但是你这个示例是用的NCNN啊，这也是可以用来推理yolov8的吧

您是说知乎的文章吗？
知乎文章里的ncnn内容要查看 ncnn-examples 仓库。文章结尾为了推广我这个tensorrt的仓库才放的这个仓库连接，两者没有什么太大关系。

**Comment by fengshangren** [comment]
> > > 这是tensorrt库提供的。您可以去官网查看安装方法。如果是ncnn的话本库还不支持。。
> > 
> > 
> > triple-Mu/ncnn-examples/blob/main/cpp/yolov8/src/triplemu-yolov8.cpp 但是你这个例子是用的NCNN啊，这也是可以用来推理yolov8的吧
> 
> 您是说知道什么的文章吗？ 知道文章里的ncnn内容要查看ncnn-examples库。文章结尾是为了推广我这个tensorrt的库才放的这个库关联，现有的关联，太大关系。

那只是用来做yolov8目标识别这一块是用tensorrt好点，还是NCNN好点

**Comment by triple-Mu** [comment]
> > > > 这是tensorrt库提供的。您可以去官网查看安装方法。如果是ncnn的话本库还不支持。。
> 
> > > 
> 
> > > 
> 
> > > triple-Mu/ncnn-examples/blob/main/cpp/yolov8/src/triplemu-yolov8.cpp 但是你这个例子是用的NCNN啊，这也是可以用来推理yolov8的吧
> 
> > 
> 
> > 您是说知道什么的文章吗？ 知道文章里的ncnn内容要查看ncnn-examples库。文章结尾是为了推广我这个tensorrt的库才放的这个库关联，现有的关联，太大关系。
> 
> 
> 
> 那只是用来做yolov8目标识别这一块是用tensorrt好点，还是NCNN好点

如果您用 gpu 的话，tensorrt好一些，速度更快。如果是 cpu 或者嵌入式设备用 ncnn 好一些，因为 gpu 只有 nvidia 的设备才会提供。

**Comment by fengshangren** [comment]
> > > > > 这是tensorrt库提供的。您可以去官网查看安装方法。如果是ncnn的话本库还不支持。。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > triple-Mu/ncnn-examples/blob/main/cpp/yolov8/src/triplemu-yolov8.cpp 但是你这个例子是用的NCNN啊，这也是可以用来推理yolov8的吧
> > 
> > 
> > > 
> > 
> > 
> > > 您是说知道什么的文章吗？ 知道文章里的ncnn内容要查看ncnn-examples库。文章结尾是为了推广我这个tensorrt的库才放的这个库关联，现在有壁垒系。
> > 
> > 
> > 那只是用来做yolov8目标识别这个块是用tensorrt好点，还是NCNN好点
> 
> 如果您使用gpu的话，tensorrt好一些，速度更快。如果是cpu或者输入式设备使用ncnn好一些，因为gpu只有nvidia的设备才会提供。

我只是WINDOWS系统用用，我两种都会用到吧，如果GPU用不了那也只有用CPU，CPU不会差太多也无所谓
