### ISSUE TITLE
Remove Non-Maximum Suppression operation

### ISSUE THREAD

**Issue by wangjianan-123** [triple-Mu/YOLOv8-TensorRT#76]
If I only want to get the raw output of the model instead of the output after adding NMS operation, how can I do it for YOLOv8?
thanks！

**Comment by triple-Mu** [comment]
> If I only want to get the raw output of the model instead of the output after adding NMS operation, how can I do it for YOLOv8?
> 
> thanks！

You can try csrc/detect/norm

**Comment by wangjianan-123** [comment]
If I need to get  an engine format model whose output is not post-processed with NMS, but is the same as the output of its pt format model, what should I do?  thanks

**Comment by triple-Mu** [comment]
See more info in https://github.com/triple-Mu/YOLOv8-TensorRT/blob/main/docs/Normal.md

**Comment by wangjianan-123** [comment]
thanks!!!
