### ISSUE TITLE
Possibility of inferring only one class?

### ISSUE THREAD

**Issue by Chalkeys** [triple-Mu/YOLOv8-TensorRT#78]
I've got a custom yolov8 model that has 3 classes and I'm wondering if there is a way to infer only one specific class at the inference stage by stating the desired class number during the whole .pt->.onnx->.engine process? I went over most of the code but couldn't find one. Thanks!

**Comment by triple-Mu** [comment]
> I've got a custom yolov8 model that has 3 classes and I'm wondering if there is a way to infer only one specific class at the inference stage by stating the desired class number during the whole .pt->.onnx->.engine process? I went over most of the code but couldn't find one. Thanks!

Suppose you have classes ['a', 'b', 'c'], you can add some condition in https://github.com/triple-Mu/YOLOv8-TensorRT/blob/main/infer-det.py#L45:
``` python
if cls_id == 0: # class a
    ...
elif cls_id == 1: # class b
    ....
elif cls_id == 2: # class c
    ...

if cls == 'a': # class a
    ...
elif cls == 'b': # class b
    ....
elif cls == 'c': # class c
    ...
```

**Comment by Chalkeys** [comment]
> > I've got a custom yolov8 model that has 3 classes and I'm wondering if there is a way to infer only one specific class at the inference stage by stating the desired class number during the whole .pt->.onnx->.engine process? I went over most of the code but couldn't find one. Thanks!
> 
> Suppose you have classes ['a', 'b', 'c'], you can add some condition in https://github.com/triple-Mu/YOLOv8-TensorRT/blob/main/infer-det.py#L45:
> 
> ```python
> if cls_id == 0: # class a
>     ...
> elif cls_id == 1: # class b
>     ....
> elif cls_id == 2: # class c
>     ...
> 
> if cls == 'a': # class a
>     ...
> elif cls == 'b': # class b
>     ....
> elif cls == 'c': # class c
>     ...
> ```

Gottcha, thought it was for plotting only. Thanks!

**Comment by triple-Mu** [comment]
> > > I've got a custom yolov8 model that has 3 classes and I'm wondering if there is a way to infer only one specific class at the inference stage by stating the desired class number during the whole .pt->.onnx->.engine process? I went over most of the code but couldn't find one. Thanks!
> > 
> > 
> > Suppose you have classes ['a', 'b', 'c'], you can add some condition in https://github.com/triple-Mu/YOLOv8-TensorRT/blob/main/infer-det.py#L45:
> > ```python
> > if cls_id == 0: # class a
> >     ...
> > elif cls_id == 1: # class b
> >     ....
> > elif cls_id == 2: # class c
> >     ...
> > 
> > if cls == 'a': # class a
> >     ...
> > elif cls == 'b': # class b
> >     ....
> > elif cls == 'c': # class c
> >     ...
> > ```
> 
> Gottcha, thought it was for plotting only. Thanks!

You are welcome!
