### ISSUE TITLE
an error while use the yolov8-pose.engine to inference

### ISSUE THREAD

**Issue by GalSang17** [triple-Mu/YOLOv8-TensorRT#79]
The engine file exported directly using the export provided by the v8 project cannot be directly reasoned. like this:

(py38) yangyang@ysd-18:~/GenTrt/YOLOv8-DSPTC/csrc/pose/normal/build$ ./yolov8-pose ../yolov8l-pose.engine ../bus.jpg 
ERROR: 1: [stdArchiveReader.cpp::StdArchiveReader::30] Error Code 1: Serialization (Serialization assertion magicTagRead == kMAGIC_TAG failed.Magic tag does not match)
ERROR: 4: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)
段错误 (核心已转储)

so, I use the v8 project to export the onnx file, and then use the onnx2trt tool to generate the engine, but the following error is thrown during reasoning:

(py38) yangyang@ysd-18:~/GenTrt/YOLOv8-DSPTC/csrc/pose/normal/build$ ./yolov8-pose ../yolov8l-pose.engine ../p1.mp4 
model warmup 10 times
CUDA Error:
    File:       /home/yangyang/GenTrt/YOLOv8-DSPTC/csrc/pose/normal/./include/yolov8-pose.hpp
    Line:       300
    Error code: 1
    Error text: invalid argument

my envs:
CUDA:11.6
cuDNN:8.4.1
TensorRT:8.4.3.1
onnx:1.12.0
could you please help me? thanks.

**Comment by triple-Mu** [comment]
Know issue:
https://github.com/triple-Mu/YOLOv8-TensorRT/issues/71

> The engine file exported directly using the export provided by the v8 project cannot be directly reasoned. like this:
> 
> (py38) yangyang@ysd-18:~/GenTrt/YOLOv8-DSPTC/csrc/pose/normal/build$ ./yolov8-pose ../yolov8l-pose.engine ../bus.jpg ERROR: 1: [stdArchiveReader.cpp::StdArchiveReader::30] Error Code 1: Serialization (Serialization assertion magicTagRead == kMAGIC_TAG failed.Magic tag does not match) ERROR: 4: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.) 段错误 (核心已转储)
> 
> so, I use the v8 project to export the onnx file, and then use the onnx2trt tool to generate the engine, but the following error is thrown during reasoning:
> 
> (py38) yangyang@ysd-18:~/GenTrt/YOLOv8-DSPTC/csrc/pose/normal/build$ ./yolov8-pose ../yolov8l-pose.engine ../p1.mp4 model warmup 10 times CUDA Error: File: /home/yangyang/GenTrt/YOLOv8-DSPTC/csrc/pose/normal/./include/yolov8-pose.hpp Line: 300 Error code: 1 Error text: invalid argument
> 
> my envs: CUDA:11.6 cuDNN:8.4.1 TensorRT:8.4.3.1 onnx:1.12.0 could you please help me? thanks.

Know issue:
https://github.com/triple-Mu/YOLOv8-TensorRT/issues/71

**Comment by GalSang17** [comment]
> Know issue: #71
> 
> > The engine file exported directly using the export provided by the v8 project cannot be directly reasoned. like this:
> > (py38) yangyang@ysd-18:~/GenTrt/YOLOv8-DSPTC/csrc/pose/normal/build$ ./yolov8-pose ../yolov8l-pose.engine ../bus.jpg ERROR: 1: [stdArchiveReader.cpp::StdArchiveReader::30] Error Code 1: Serialization (Serialization assertion magicTagRead == kMAGIC_TAG failed.Magic tag does not match) ERROR: 4: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.) 段错误 (核心已转储)
> > so, I use the v8 project to export the onnx file, and then use the onnx2trt tool to generate the engine, but the following error is thrown during reasoning:
> > (py38) yangyang@ysd-18:~/GenTrt/YOLOv8-DSPTC/csrc/pose/normal/build$ ./yolov8-pose ../yolov8l-pose.engine ../p1.mp4 model warmup 10 times CUDA Error: File: /home/yangyang/GenTrt/YOLOv8-DSPTC/csrc/pose/normal/./include/yolov8-pose.hpp Line: 300 Error code: 1 Error text: invalid argument
> > my envs: CUDA:11.6 cuDNN:8.4.1 TensorRT:8.4.3.1 onnx:1.12.0 could you please help me? thanks.
> 
> Known issue: #71

yes, i see it, i have try trtexec, but still this error, why?

**Comment by GalSang17** [comment]
> > > Know issue: #71
> > > > The engine file exported directly using the export provided by the v8 project cannot be directly reasoned. like this:
> > > > (py38) yangyang@ysd-18:~/GenTrt/YOLOv8-DSPTC/csrc/pose/normal/build$ ./yolov8-pose ../yolov8l-pose.engine ../bus.jpg ERROR: 1: [stdArchiveReader.cpp::StdArchiveReader::30] Error Code 1: Serialization (Serialization assertion magicTagRead == kMAGIC_TAG failed.Magic tag does not match) ERROR: 4: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.) 段错误 (核心已转储)
> > > > so, I use the v8 project to export the onnx file, and then use the onnx2trt tool to generate the engine, but the following error is thrown during reasoning:
> > > > (py38) yangyang@ysd-18:~/GenTrt/YOLOv8-DSPTC/csrc/pose/normal/build$ ./yolov8-pose ../yolov8l-pose.engine ../p1.mp4 model warmup 10 times CUDA Error: File: /home/yangyang/GenTrt/YOLOv8-DSPTC/csrc/pose/normal/./include/yolov8-pose.hpp Line: 300 Error code: 1 Error text: invalid argument
> > > > my envs: CUDA:11.6 cuDNN:8.4.1 TensorRT:8.4.3.1 onnx:1.12.0 could you please help me? thanks.
> > > 
> > > 
> > > Known issue: #71
> > 
> > 
> > yes, i see it, i have try trtexec, but still this error, why?
> 
> How about your trtexec tool version about tensorrt? It seems that you build engine with other version and infer with 8.4.3.1?

same as 8.4.3.1

**Comment by GalSang17** [comment]
> > > > Know issue: #71
> > > > > The engine file exported directly using the export provided by the v8 project cannot be directly reasoned. like this:
> > > > > (py38) yangyang@ysd-18:~/GenTrt/YOLOv8-DSPTC/csrc/pose/normal/build$ ./yolov8-pose ../yolov8l-pose.engine ../bus.jpg ERROR: 1: [stdArchiveReader.cpp::StdArchiveReader::30] Error Code 1: Serialization (Serialization assertion magicTagRead == kMAGIC_TAG failed.Magic tag does not match) ERROR: 4: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.) 段错误 (核心已转储)
> > > > > so, I use the v8 project to export the onnx file, and then use the onnx2trt tool to generate the engine, but the following error is thrown during reasoning:
> > > > > (py38) yangyang@ysd-18:~/GenTrt/YOLOv8-DSPTC/csrc/pose/normal/build$ ./yolov8-pose ../yolov8l-pose.engine ../p1.mp4 model warmup 10 times CUDA Error: File: /home/yangyang/GenTrt/YOLOv8-DSPTC/csrc/pose/normal/./include/yolov8-pose.hpp Line: 300 Error code: 1 Error text: invalid argument
> > > > > my envs: CUDA:11.6 cuDNN:8.4.1 TensorRT:8.4.3.1 onnx:1.12.0 could you please help me? thanks.
> > > > 
> > > > 
> > > > Known issue: #71
> > > 
> > > 
> > > yes, i see it, i have try trtexec, but still this error, why?
> > 
> > 
> > How about your trtexec tool version about tensorrt? It seems that you build engine with other version and infer with 8.4.3.1?
> 
> same as 8.4.3.1 ![image](https://user-images.githubusercontent.com/49866330/234511531-35a905bc-b6a4-43e3-8b0e-cf92f48dbe15.png)

yeah, i know why. i use mode.export(formot='onnx', half=Ture), it can't use it in this script, so it worked!
but now another issue catch: when i use fp16, a lot of warnings will display, like this screen:
![image](https://user-images.githubusercontent.com/49866330/234513065-0cd11f34-3b6c-4ad8-b1d1-f6a39641cc6e.png)

**Comment by triple-Mu** [comment]
> 

It does not matter
The weight of fp32 will cause overflow or truncation when converted to fp16.
You can make sure by visualize.

**Comment by triple-Mu** [comment]
> > > 
> > 
> > 
> > It does not matter The weight of fp32 will cause overflow or truncation when converted to fp16. You can make sure by visualize.
> 
> okk, thank you! good jobs!

You are welcome!
