### ISSUE TITLE
Is it possible to support both YOLOv5 and YOLOv7 segmentation?

### ISSUE THREAD

**Issue by peterchen183** [triple-Mu/YOLOv8-TensorRT#80]
`num_classes = num_channels - seg_channels - 4; // v7 & v8`
`num_classes = num_channels - seg_channels - 5; // v5`

`cv::Mat protos = cv::Mat(seg_channels, seg_h * seg_w, CV_32F, static_cast<float*>(this->host_ptrs[0])); // v5, v7 & v8`

**Comment by triple-Mu** [comment]
Maybe not.
I just test YOLOv8 now.

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
