### ISSUE TITLE
TRT:EfficientNMS_TRT(-1) is not a registered function/op

### ISSUE THREAD

**Issue by siiiiilvio** [triple-Mu/YOLOv8-TensorRT#83]
I am getting this error when trying to run inference on the exported End2End ONNX with NMS.

This is how I'm running the inference (via script): 

```
import onnxruntime as rt
import numpy as np

sess = rt.InferenceSession("model.onnx")

input_name = sess.get_inputs()[0].name
output_name = sess.get_outputs()[0].name

input_data = np.random.rand(1, 3, 640, 640).astype(np.float32)

output = sess.run([output_name], {input_name: input_data})

print(output)
```

[ONNXRuntimeError] : 1 : FAIL : Load model from model.onnx failed:Fatal error: TRT:EfficientNMS_TRT(-1) is not a registered function/op

While running the export I also ran into this Warning:

`$ python3 export-det.py --weights model.pt --iou-thres 0.65 --conf-thres 0.5 --topk 100 --opset 11 --sim --input-shape 1 3 640 640 --device cuda:0`

Model summary (fused): 168 layers, 11126358 parameters, 0 gradients, 28.4 GFLOPs
[W shape_type_inference.cpp:1920] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
[W shape_type_inference.cpp:1920] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
[W shape_type_inference.cpp:1920] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
[W shape_type_inference.cpp:1920] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
============= Diagnostic Run torch.onnx.export version 2.0.0+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 4 WARNING 0 ERROR ========================
4 WARNING were not printed due to the log level.

ONNX export success, saved as model.onnx

Current configuration:

`Ubuntu 20.04`

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
```

```
Name: tensorrt
Version: 8.6.1
Summary: A high performance deep learning inference library
Home-page: https://developer.nvidia.com/tensorrt
Author: NVIDIA Corporation
Author-email: 
License: Proprietary
Location: /home/ubuntu/.local/lib/python3.8/site-packages
```

I have also tried with Cuda 11.8, same issue.

**Comment by triple-Mu** [comment]
We only support tensorrt now.
Please see infer-det.py for more infomation.

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
