### ISSUE TITLE
it's possible to convert yolov8 instance segmentation with end2end ?

### ISSUE THREAD

**Issue by belarbi2733** [triple-Mu/YOLOv8-TensorRT#84]
it's possible to convert yolov8 instance segmentation with end2end ?

i want to have 
 output_names = [
                "num_dets",
                "det_boxes",
                "det_scores",
                "det_classes",
                "det_masks",
            ]
it's possible tank you

**Comment by triple-Mu** [comment]
> it's possible to convert yolov8 instance segmentation with end2end ?
> 
> 
> 
> i want to have 
> 
>  output_names = [
> 
>                 "num_dets",
> 
>                 "det_boxes",
> 
>                 "det_scores",
> 
>                 "det_classes",
> 
>                 "det_masks",
> 
>             ]
> 
> it's possible tank you

Maybe not now.
But I will try it.

**Comment by mohammedphoenix** [comment]
can you please help it's for my thesis please thank you

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
