### ISSUE TITLE
Is tracking on jetson devices suported

### ISSUE THREAD

**Issue by AyushExel** [triple-Mu/YOLOv8-TensorRT#85]
Hey, amazing work with this repo. I was wondering if you also have a walkthrough of deploying/using tracking tasks on jetson devices? Thanks!
cc @pax7

**Comment by triple-Mu** [comment]
> Hey, amazing work with this repo. I was wondering if you also have a walkthrough of deploying/using tracking tasks on jetson devices? Thanks!
> 
> cc @pax7
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

I have test bytetrack. It is easy and fast.
Maybe we can add bytetrack in detection.

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!

**Comment by dahan198** [comment]
Hi @triple-Mu,
I wanted to check in about @pax7's request from May 14. Could you please commit your example that uses YOLOv8-TensorRT and ByteTrack in detection to the repository?
