### ISSUE TITLE
deepstream python app on jetson

### ISSUE THREAD

**Issue by sergii-matiukha** [triple-Mu/YOLOv8-TensorRT#86]
How to make INT8 engine for yolov8 model with imgsz=3040,  for use in deepstream python app on jetson? And how much does the accuracy drop when switching from Fp32 to INT8?

**Comment by triple-Mu** [comment]
> How to make INT8 engine for yolov8 model with imgsz=3040,  for use in deepstream python app on jetson? And how much does the accuracy drop when switching from Fp32 to INT8?

I haven't test int8 inference.
This repo provide a deepstream c++ demo in csrc/deepstream.

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
