### ISSUE TITLE
main.cpp error

### ISSUE THREAD

**Issue by MoussaGRICHE** [triple-Mu/YOLOv8-TensorRT#89]
Hi @triple-Mu ,

I have trained yolov8n model with only 2 classes (car and motorcycle)

When I change the main.cpp 

      const std::vector<std::string> CLASS_NAMES = {
	"car", "motorcycle" };

       const std::vector<std::vector<unsigned int>> COLORS = {
	 { 237, 177, 32 }, { 126, 47, 142 } };

and make the yolov8 file, I get an error:

    model warmup 10 times
    Segmentation fault (core dumped)

But when I don't change the main.cpp file, the inference works good but detects others objects that I don't wand to be detected.

I am running the inference yolov8 on jetson Nano.

Do you have an idea about this issus?

Thank you.

**Comment by triple-Mu** [comment]
You should filter label in for loop.
The network will detect all 80 labels so it may cause index out of range error.

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
