### ISSUE TITLE
No detections with normal inference code

### ISSUE THREAD

**Issue by xiang-wuu** [triple-Mu/YOLOv8-TensorRT#90]
I tried serializing the engine file with network builder api with end-to-end network including NMS plugin which is working fine, but i modified the `api.py` by commenting the code for `EfficientNMS_TRT` plugin part, and set `BBOXES.get_output(0)` &  `SCORES.get_output(0)` as network output bindings, the engine file generates without any issue, but when used `csrc/detect/normal/main.cpp` for inference i am getting no detection's and observed that all the scores generated appears very low in confidence value  which does not pass the minimum `if (score > score_thres)` confidence threshold criteria due to which all the detected outputs is get filtered out. Any help on this would be appreciated.

**Comment by triple-Mu** [comment]
`csrc/detect/normal/main.cpp` only support the onnx exported by origin `ultralytics` repo.
If you want to modify the output  by api and do inference, you'd best modify `csrc/detect/end2end/include/yolov8.hpp`.

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
