### ISSUE TITLE
Speedup Pose on Jetson ? 

### ISSUE THREAD

**Issue by pax-tmb** [triple-Mu/YOLOv8-TensorRT#91]
Hi @triple-Mu - do you have supporting Speedup Pose , YOLOv8 -pose on Jetson on your near term roadmap?

You already support Detection and Segmentation:

https://github.com/triple-Mu/YOLOv8-TensorRT/blob/main/docs/Jetson.md

**Comment by triple-Mu** [comment]
Here is a demo.
https://github.com/triple-Mu/YOLOv8-TensorRT/commit/d9687b12c1a2756d48529d4f3f1fdd638630e361
