### ISSUE TITLE
Is int8 acceleration possible?

### ISSUE THREAD

**Issue by ywangwxd** [triple-Mu/YOLOv8-TensorRT#92]
I see your tensorrt model is fp16.

**Comment by triple-Mu** [comment]
> I see your tensorrt model is fp16.

I guess as you said.
But the improvement may not be obvious.
Also, you are welcome to submit a pr to help add this feature.

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
