### ISSUE TITLE
request for infer-pose.py example

### ISSUE THREAD

**Issue by pax7** [triple-Mu/YOLOv8-TensorRT#94]
hi @triple-Mu 

can you please add an example that uses the .engine file in python for:

infer-pose.py

that is similar to the existing infer-det.py and infer-seg.py examples?

**Comment by triple-Mu** [comment]
> hi @triple-Mu 
> 
> 
> 
> can you please add an example that uses the .engine file in python for:
> 
> 
> 
> infer-pose.py
> 
> 
> 
> that is similar to the existing infer-det.py and infer-seg.py examples?
> 
> 
> 
> 

You can use yolov8 official demo for loading engine and infer images and video.

**Comment by triple-Mu** [comment]
Suggest you using `csrc/jeston/pose` for speed up.

**Comment by triple-Mu** [comment]
> 



> @triple-Mu - right, but that's c++, is there an equivalent of that in python?

Maybe I won't do that. `c++` demo is also easy.

**Comment by triple-Mu** [comment]
I didn't make any changes  about the pose model. Instead, I made modifications to both the detection and segmentation model post-processing. In order to ensure that the same thing is not repeated, so I did not provide the post-processing of the python version

**Comment by triple-Mu** [comment]
> @triple-Mu if you have the pose_postprocessing in python, can you please paste it in this thread, I add it to torch_utils.py locally and then test it and I can continue implementing my project in python. Right now the last missing piece is this pose_postprocessing :(

It is valuable to read and study yolov8 source code.

**Comment by triple-Mu** [comment]
> @triple-Mu - if you want to take a look, I'm basically offering a bounty for this solution - alternatively if you could point me in the right direction in the ultralytics code where I could start and figure out what I need to do to write the pose_postprocess that would be greatly appreciated!

I will give you a easy demo latter.

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
