### ISSUE TITLE
出现了一个错误File: ./include/yolov8.hpp

### ISSUE THREAD

**Issue by tongguanghong** [triple-Mu/YOLOv8-TensorRT#97]
Line: 137
Error code: 801
Error text: operation not supported
CHECK(cudaMallocAsync(
			&d_ptr,
			bindings.size * bindings.dsize,
			this->stream)
		);

**Comment by triple-Mu** [comment]
看上去你的cuda版本小于11.4.
你可以考虑使用 `csrc/jetson/detect` 下面的代码。

**Comment by triple-Mu** [comment]
提供一下 gcc/g++ 版本？

**Comment by tongguanghong** [comment]
9.4.0

**Comment by tongguanghong** [comment]
好的好的，谢谢了

**Comment by tongguanghong** [comment]
我现在使用cuda11.7和cudnn8.5.0，重新编译csrc/jetson/detect 下面的代码，运行成功了，但是/csrc/detect还是一样的错误，非常感谢

**Comment by triple-Mu** [comment]
> 我现在使用cuda11.7和cudnn8.5.0，重新编译csrc/jetson/detect 下面的代码，运行成功了，但是/csrc/detect还是一样的错误，非常感谢

👌🏻两份代码只有一个接口有区别。可能你的cuda环境混乱了。如果没有其他问题就关闭issue了
