### ISSUE TITLE
labels all shown as Person in infer-seg.py

### ISSUE THREAD

**Issue by song-GAO-1992** [triple-Mu/YOLOv8-TensorRT#99]
Hi, thanks for sharing this great job.
I meet up an issue when I used the infer-seg.py. All labels detected are shown as person. The model I used is the official released(yolov8s-seg.pt), and I convert the model into .engine following the steps from this project. 
I also checked models in Netron. I found there are some modifications in the models and the seg_postprocess() is different from official's. Could you please check this issue?

**Comment by triple-Mu** [comment]
> Hi, thanks for sharing this great job. I meet up an issue when I used the infer-seg.py. All labels detected are shown as person. The model I used is the official released(yolov8s-seg.pt), and I convert the model into .engine following the steps from this project. I also checked models in Netron. I found there are some modifications in the models and the seg_postprocess() is different from official's. Could you please check this issue?

Okay. The best way to check is uploading your onnx first.
This repo does some addition process such as argmax for score and get every anchor's label. So that we can easy get the anchor which is satisfy the threshold.

**Comment by song-GAO-1992** [comment]
> > Hi, thanks for sharing this great job. I meet up an issue when I used the infer-seg.py. All labels detected are shown as person. The model I used is the official released(yolov8s-seg.pt), and I convert the model into .engine following the steps from this project. I also checked models in Netron. I found there are some modifications in the models and the seg_postprocess() is different from official's. Could you please check this issue?
> 
> Okay. The best way to check is uploading your onnx first. This repo does some addition process such as argmax for score and get every anchor's label. So that we can easy get the anchor which is satisfy the threshold.

hi, I have upload this model below here:
链接: https://pan.baidu.com/s/1FyyHCvIvf93tcl6N6ma8Lw?pwd=1234 提取码: 1234

**Comment by slgao** [comment]
I have the same issue, I used my own customed YOLOv8 segmentation model to convert it to the Tensorrt engine, which has totally three classes, but the detection labels were all with index 0. I checked the unique values of the label 
array, there were actually 0, 1, and 2 indices. but the detected bbox and segms were all with label value 0. Can you please help ? Thank you!

**Comment by slgao** [comment]
> 

I have a Yolov8 pytorch model trained with my own customized data. Then converted to the Tensorrt engine using 
the export-seg.py and the build.py script.  Testing with infer-seg.py . My project is only using python script at the moment.

**Comment by triple-Mu** [comment]
> > 
> 
> 
> 
> I have a Yolov8 pytorch model trained with my own customized data. Then converted to the Tensorrt engine using 
> 
> the export-seg.py and the build.py script.  Testing with infer-seg.py . My project is only using python script at the moment. 

Do you modify config.py for class namea

**Comment by slgao** [comment]
yes, it always returned the first name item, which means the label is
always returning 0s, but I try to do the labels.unique(), the labels array
has multiple unique vales (0., 1., 2. ..).


BTW, I tried with the c++ code, this works perfectly with the same Tensorrt
Engine. But my project is in Python, It would be great if the Python script
works, if any one can help, I would appreciate it.

triple Mu ***@***.***> 於 2023年6月24日 週六 01:51 寫道：

**Comment by triple-Mu** [comment]
> 

How about now?

**Comment by song-GAO-1992** [comment]
> How about now?

I used the normal code. It worked fine. Is there any update now?

**Comment by triple-Mu** [comment]
> > How about now?
> 
> I used the normal code. It worked fine. Is there any update now?

Maybe not.

**Comment by HelloTDK** [comment]
我要遇到了同样的问题，config也修改过了，所有类别的检测结果都会显示成第一个类别无法区分
